import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newDocument,DrawingHistory,validateDocument} from '../client/creativity/document.mjs';
import {floodFill} from '../client/creativity/engine.mjs';
import {TraceCoverage} from '../client/creativity/practice.mjs';
import {GalleryService} from '../client/creativity/gallery.mjs';
import {FamilyGame} from '../client/family-game.mjs';
const stroke={type:'stroke',tool:'marker',color:'#ed3348',size:18,points:[[100,100,.7],[180,180,.7]]};
test('drawing undo/redo and clear preserve an editable document',()=>{const h=new DrawingHistory(newDocument('coloring','truck'));h.add(stroke);h.add({type:'clear'});h.undo();assert.deepEqual(h.document.ops,[stroke]);h.redo();assert.equal(h.document.ops.at(-1).type,'clear');h.undo();h.add({...stroke,color:'#248ae8'});assert.equal(h.redoOps.length,0);assert.deepEqual(validateDocument(JSON.parse(JSON.stringify(h.document))),h.document);});
test('bucket flood fill respects closed boundaries and can recolor black paint',()=>{const w=7,h=7,v=new Uint8ClampedArray(w*h*4).fill(255),ink=new Uint8ClampedArray(v.length),boundary=new Uint8ClampedArray(v.length);for(let y=0;y<h;y++){const k=(y*w+3)*4;v.set([25,25,25,255],k);boundary.set([25,25,25,255],k);}assert(floodFill(ink,v,w,h,1,1,'#202027',boundary));assert.equal(ink[(1*w+1)*4],32);assert.equal(ink[(1*w+5)*4+3],0);for(let i=0;i<ink.length;i+=4)if(ink[i+3])v.set(ink.slice(i,i+4),i);assert(floodFill(ink,v,w,h,1,1,'#248ae8',boundary));assert.equal(ink[(1*w+1)*4],36);assert.equal(floodFill(ink,v,w,h,3,1,'#ed3348',boundary),false);});
test('tracing credit depends on touching the guide, including fast swipes',()=>{const w=160,h=120,image=new Uint8ClampedArray(w*h*4);for(let y=55;y<65;y++)for(let x=20;x<140;x++)image[(y*w+x)*4+3]=255;const t=new TraceCoverage(image,w,h);t.segment([0,5],[150,5],10);assert.equal(t.progress,0);t.segment([20,60],[140,60],18);assert.ok(t.progress>.9);});
class MemoryArt{constructor(){this.rows=new Map();}async list(profile){return [...this.rows.values()].filter(r=>r.profile===profile).map(({id,title})=>({id,title}));}async put(profile,row){const clean={...row,profile,document:validateDocument(row.document)};this.rows.set(profile+'/'+row.id,clean);return {id:row.id,title:row.title};}async get(profile,id){const row=this.rows.get(profile+'/'+id);if(!row)throw Error('not in your gallery');return row;}}
test('chunked galleries stay bound to approved profiles and survive room recreation',async()=>{const store=new MemoryArt(),g=new GalleryService(store),doc=newDocument('coloring','doll');doc.ops.push(stroke);const text=JSON.stringify(doc);await g.request('ipad','halli','art-begin',{id:'picture-1',length:text.length,title:'My doll'});await assert.rejects(g.request('ipad','jace','art-part',{offset:0,text}),/again/);await assert.rejects(g.request('ipad','halli','art-part',{offset:7,text}),/part/);await g.request('ipad','halli','art-part',{offset:0,text});await g.request('ipad','halli','art-finish',{});assert.equal((await g.request('ipad','halli','art-list')).pictures.length,1);assert.equal((await g.request('other','jace','art-list')).pictures.length,0);await assert.rejects(g.request('other','jace','art-read',{id:'picture-1',offset:0}),/gallery/);const reopened=new GalleryService(store);assert.equal(JSON.parse((await reopened.request('new-ipad','halli','art-read',{id:'picture-1',offset:0})).text).sheet,'doll');await assert.rejects(g.request('ipad','halli','art-begin',{id:'bad',length:9000000}),/size/);});
test('invalid artwork is rejected without executing arbitrary markup or accepting image URLs',()=>{assert.throws(()=>validateDocument({...newDocument(),ops:[{type:'image',src:'https://unapproved.test/a'}]}));assert.throws(()=>validateDocument({...newDocument(),ops:[{...stroke,color:'url(https://unapproved.test)'}]}));assert.throws(()=>validateDocument({...newDocument(),ops:[{...stroke,points:[[NaN,1,.7]]}]}));});
test('entering and leaving creativity pauses driving and returns to the previous world scene',()=>{const game=new FamilyGame();game.select('host','jace');const p=game.players.get('host');p.vehicle='car';p.engine=true;p.speed=50;p.x=45;game.request('host','action',{action:'creativity'});assert.equal(p.scene,'creativity');assert.equal(p.speed,0);assert.equal(p.engine,false);game.tick(.05);assert.equal(p.x,45);game.request('host','action',{action:'art-exit'});assert.equal(p.scene,'world');p.scene='classic';game.request('host','action',{action:'creativity'});game.request('host','action',{action:'art-exit'});assert.equal(p.scene,'classic');assert.equal(p.profile,'jace');});
