import test from 'node:test';import assert from 'node:assert/strict';import {ParkSession,SPOTS,STATIONS,GAMES} from '../client/playpark/session.mjs';
const a={id:'a',name:'Mommy',profile:'mommy'},b={id:'b',name:'Unique',profile:'unique'};
function setup(game){const s=new ParkSession();s.request(a,{op:'join',game});s.request(b,{op:'join',game});return s;}
function wait(s,t){for(let i=0;i<Math.ceil(t/.05);i++)s.tick(.05);}
function press(s,p,name){wait(s,.17);return s.request(p,{op:'action',name});}
test('all seven activities support shared membership and snapshots isolate games',()=>{for(const game of Object.keys(GAMES)){const s=setup(game);assert.equal(s.snapshot(a.id).members.length,2);assert.equal(s.snapshot(b.id).side,1);s.request(b,{op:'join',game:game==='cook'?'swim':'cook'});assert.equal(s.snapshot(a.id).members.length,1);}});
test('movement is host authoritative, bounded and stops when input expires',()=>{const s=setup('hide');assert.throws(()=>s.request(a,{op:'input',x:NaN,z:0}),/Invalid/);assert.throws(()=>s.request(a,{op:'input',x:100,z:0}),/Invalid/);s.request(a,{op:'input',x:1,z:0});wait(s,.3);const x=s.members.get('a').x;assert.ok(x> -1);wait(s,1);const stopped=s.members.get('a').x;wait(s,1);assert.equal(s.members.get('a').x,stopped);});
test('hide and seek hides positions, enforces countdown, reveals searches and alternates roles',()=>{const s=setup('hide');press(s,a,'start');assert.equal(s.games.hide.seeker,'a');assert.equal(s.snapshot('a').members[1].x,undefined);const m=s.members.get('b');Object.assign(m,SPOTS[0]);press(s,b,'hide');assert.equal(m.hidden,0);wait(s,25);assert.equal(s.games.hide.phase,'seeking');const hidden=s.snapshot('a').members[1];assert.equal(hidden.x,undefined);assert.equal(hidden.hidden,null);assert.ok(Number.isFinite(s.snapshot('b').members[1].x));Object.assign(s.members.get('a'),{x:SPOTS[0].x,z:SPOTS[0].z});press(s,a,'search');wait(s,.1);assert.equal(m.found,true);assert.equal(s.games.hide.phase,'done');press(s,b,'start');assert.equal(s.games.hide.seeker,'b');s.leave('b');assert.equal(s.games.hide.phase,'waiting');});
test('fishing requires hook timing and reel/release balance to catch a fish',()=>{const s=setup('fishing');press(s,a,'cast');wait(s,.9);const f=s.members.get('a').fish;wait(s,f.bite+.1);assert.equal(f.phase,'bite');press(s,a,'hook');for(let i=0;i<300&&f.phase==='fight';i++){s.request(a,{op:'reel',down:f.tension<.65});s.tick(.05);}assert.equal(f.phase,'caught');assert.equal(s.games.fishing.caught,1);assert.equal(s.members.get('b').contribution,0);});
test('seesaw responds to alternating pushes and awards a shared star',()=>{const s=setup('seesaw');for(let i=0;i<140;i++){const g=s.games.seesaw;press(s,g.angle>=0?a:b,'pump');s.tick(.1);}assert.ok(s.games.seesaw.stars>0);assert.ok(s.members.get('a').contribution>0);assert.ok(s.members.get('b').contribution>0);});
test('swimming validates diving board, supports underwater/circles and collects shared rings',()=>{const s=setup('swim'),p=s.members.get('a');p.z=-5;assert.throws(()=>press(s,a,'dive'),/board/);p.z=5;p.x=0;press(s,a,'dive');assert.equal(p.mode,'dive');wait(s,2);assert.equal(p.mode,'swim');press(s,a,'under');assert.equal(p.mode,'under');wait(s,5.1);assert.equal(p.mode,'swim');press(s,a,'circle');const x=p.x;wait(s,.5);assert.notEqual(p.x,x);p.animation=0;p.mode='swim';for(const r of [...s.games.swim.rings]){Object.assign(p,r);s.tick(.05);}assert.equal(s.games.swim.rings.length,0);assert.equal(s.games.swim.score,8);});
test('cooking carries recipe ingredients, prepares food, flips it and serves a shared meal',()=>{
 const s=setup('cook');assert.throws(()=>press(s,a,'ingredient-0'),/refrigerator/);
 for(let i=0;i<3;i++){const p=i%2?a:b;Object.assign(s.members.get(p.id),STATIONS[0]);press(s,p,'ingredient-'+i);assert.equal(s.members.get(p.id).carry,s.snapshot(p.id).recipe[1][i]);Object.assign(s.members.get(p.id),STATIONS[1]);press(s,p,'work');assert.equal(s.members.get(p.id).carry,null);}
 for(let i=0;i<6;i++){const p=i%2?a:b;Object.assign(s.members.get(p.id),STATIONS[1]);press(s,p,'work');}assert.equal(s.games.cook.step,4);Object.assign(s.members.get('a'),STATIONS[2]);press(s,a,'work');wait(s,2.6);press(s,a,'work');assert.equal(s.games.cook.flipped,true);wait(s,2.6);press(s,a,'work');assert.equal(s.games.cook.step,5);assert.equal(s.members.get('a').carry,'plate');Object.assign(s.members.get('b'),STATIONS[3]);assert.throws(()=>press(s,b,'work'),/holding the plate/);Object.assign(s.members.get('a'),STATIONS[3]);press(s,a,'work');assert.equal(s.games.cook.served,1);assert.equal(s.games.cook.recipe,1);assert.ok(s.members.get('a').contribution&&s.members.get('b').contribution);
});
test('hedges block movement and ingredients can be put down without losing a recipe',()=>{const s=setup('hide'),p=s.members.get('a');p.x=-4;p.z=-2;for(let i=0;i<30;i++){s.request(a,{op:'input',x:1,z:0});s.tick(.05);}assert.ok(p.x<=-3.8);const c=setup('cook');Object.assign(c.members.get('a'),STATIONS[0]);press(c,a,'ingredient-0');press(c,a,'put-down');assert.equal(c.members.get('a').carry,null);assert.equal(c.games.cook.step,0);});
test('Transition Town basketball and softball use both players inputs and real ball simulations',()=>{const s=setup('basketball');const x=s.games.basketball.basket.players[1].x;s.request(b,{op:'input',x:1,z:0});wait(s,.2);assert.ok(s.games.basketball.basket.players[1].x>x);press(s,a,'primary');assert.ok(s.games.basketball.basket.shot);const t=setup('softball');press(t,b,'pitch');assert.equal(t.games.softball.phase,'pitch');const p=t.games.softball.pitch;wait(t,p.windup+p.duration-.2);press(t,a,'swing');assert.ok(['live','foul'].includes(t.games.softball.phase));});
test('animated swimmers and chefs have articulated limbs and carried food',async()=>{const {ActivityActor}=await import('../client/playpark/actors.mjs');const T=await import('../client/playpark/vendor/three.mjs');const scene=new T.Scene();const swimmer=new ActivityActor(scene,0,'swimmer');swimmer.update({x:1,z:2,mode:'swim',moving:true},0);const before=swimmer.arms[0].rotation.x;swimmer.update({x:1,z:2,mode:'swim',moving:true},.3);assert.notEqual(swimmer.arms[0].rotation.x,before);assert.equal(swimmer.body.rotation.x,Math.PI/2);swimmer.update({x:1,z:2,mode:'under'},.4);assert.ok(swimmer.root.position.y<0);const chef=new ActivityActor(scene,1,'chef');chef.update({x:0,z:0,carry:'plate',actionUntil:2},1);assert.equal(chef.carry.visible,true);assert.equal(chef.tool.visible,true);});
test('larger meadow supports crouching, entering, exiting and searching occupied shelters',()=>{
 const s=setup('hide'),p=s.members.get('b');press(s,a,'start');p.x=25;p.z=0;for(let i=0;i<30;i++){s.request(b,{op:'input',x:1,z:0});s.tick(.1);}assert.equal(p.x,28);p.input={x:0,z:0};p.x=23;p.z=0;press(s,b,'crouch');const x=p.x;s.request(b,{op:'input',x:1,z:0});s.tick(.1);assert.ok(p.x-x<.2);p.input={x:0,z:0};Object.assign(p,{x:SPOTS[0].x,z:SPOTS[0].z+1.5});press(s,b,'enter');assert.equal(p.inside,0);s.request(b,{op:'input',x:1,z:0});s.tick(.1);assert.equal(p.x,SPOTS[0].x);assert.equal(s.snapshot('a').members[1].x,undefined);assert.equal(s.snapshot('a').members[1].inside,null);p.input={x:0,z:0};press(s,b,'exit');assert.equal(p.inside,null);assert.ok(p.z>SPOTS[0].z+1);press(s,b,'enter');wait(s,25);Object.assign(s.members.get('a'),{x:p.x,z:p.z+1.8});press(s,a,'search');assert.equal(p.found,true);assert.equal(p.inside,null);
});
test('cover blocks location snapshots but crouching in the open does not grant invisibility',()=>{
 const s=setup('hide'),seeker=s.members.get('a'),hider=s.members.get('b');press(s,a,'start');wait(s,25);Object.assign(seeker,{x:-5,z:-2});Object.assign(hider,{x:-1,z:-2});assert.equal(s.snapshot('a').members[1].x,undefined);Object.assign(seeker,{x:25,z:0});Object.assign(hider,{x:25,z:4,stance:'crouch'});assert.equal(s.snapshot('a').members[1].x,25);assert.equal(s.snapshot('b').members[1].x,25);Object.assign(seeker,{x:5,z:-9});Object.assign(hider,{x:5,z:-4.8,stance:'crouch'});assert.equal(s.snapshot('a').members[1].x,undefined);hider.stance='stand';assert.equal(s.snapshot('a').members[1].x,5);
});
