import test from 'node:test';import assert from 'node:assert/strict';import {ParkSession,SPOTS,STATIONS,GAMES} from '../client/playpark/session.mjs';
const a={id:'a',name:'Mommy',profile:'mommy'},b={id:'b',name:'Unique',profile:'unique'};
function setup(game){const s=new ParkSession();s.request(a,{op:'join',game});s.request(b,{op:'join',game});return s;}
function wait(s,t){for(let i=0;i<Math.ceil(t/.05);i++)s.tick(.05);}
function press(s,p,name){wait(s,.17);return s.request(p,{op:'action',name});}
test('all seven activities support shared membership and snapshots isolate games',()=>{for(const game of Object.keys(GAMES)){const s=setup(game);assert.equal(s.snapshot(a.id).members.length,2);assert.equal(s.snapshot(b.id).side,1);s.request(b,{op:'join',game:game==='cook'?'swim':'cook'});assert.equal(s.snapshot(a.id).members.length,1);}});
test('movement is host authoritative, bounded and stops when input expires',()=>{const s=setup('hide');assert.throws(()=>s.request(a,{op:'input',x:NaN,z:0}),/Invalid/);assert.throws(()=>s.request(a,{op:'input',x:100,z:0}),/Invalid/);s.request(a,{op:'input',x:1,z:0});wait(s,.3);const x=s.members.get('a').x;assert.ok(x> -1);wait(s,1);const stopped=s.members.get('a').x;wait(s,1);assert.equal(s.members.get('a').x,stopped);});
test('hide and seek hides positions, enforces countdown, reveals searches and alternates roles',()=>{const s=setup('hide');press(s,a,'start');assert.equal(s.games.hide.seeker,'a');assert.equal(s.snapshot('a').members[1].x,undefined);const m=s.members.get('b');Object.assign(m,SPOTS[0]);press(s,b,'hide');assert.equal(m.hidden,0);wait(s,12);assert.equal(s.games.hide.phase,'seeking');const hidden=s.snapshot('a').members[1];assert.equal(hidden.x,undefined);assert.equal(hidden.hidden,null);assert.ok(Number.isFinite(s.snapshot('b').members[1].x));Object.assign(s.members.get('a'),{x:SPOTS[0].x,z:SPOTS[0].z});press(s,a,'search');wait(s,.1);assert.equal(m.found,true);assert.equal(s.games.hide.phase,'done');press(s,b,'start');assert.equal(s.games.hide.seeker,'b');s.leave('b');assert.equal(s.games.hide.phase,'waiting');});
test('fishing requires hook timing and reel/release balance to catch a fish',()=>{const s=setup('fishing');press(s,a,'cast');wait(s,.9);const f=s.members.get('a').fish;wait(s,f.bite+.1);assert.equal(f.phase,'bite');press(s,a,'hook');for(let i=0;i<300&&f.phase==='fight';i++){s.request(a,{op:'reel',down:f.tension<.65});s.tick(.05);}assert.equal(f.phase,'caught');assert.equal(s.games.fishing.caught,1);assert.equal(s.members.get('b').contribution,0);});
test('seesaw responds to alternating pushes and awards a shared star',()=>{const s=setup('seesaw');for(let i=0;i<140;i++){const g=s.games.seesaw;press(s,g.angle>=0?a:b,'pump');s.tick(.1);}assert.ok(s.games.seesaw.stars>0);assert.ok(s.members.get('a').contribution>0);assert.ok(s.members.get('b').contribution>0);});
test('swimming validates diving board, supports underwater/circles and collects shared rings',()=>{const s=setup('swim'),p=s.members.get('a');p.z=-5;assert.throws(()=>press(s,a,'dive'),/board/);p.z=5;p.x=0;press(s,a,'dive');assert.equal(p.mode,'dive');wait(s,2);assert.equal(p.mode,'swim');press(s,a,'under');assert.equal(p.mode,'under');wait(s,5.1);assert.equal(p.mode,'swim');press(s,a,'circle');const x=p.x;wait(s,.5);assert.notEqual(p.x,x);p.animation=0;p.mode='swim';for(const r of [...s.games.swim.rings]){Object.assign(p,r);s.tick(.05);}assert.equal(s.games.swim.rings.length,0);assert.equal(s.games.swim.score,8);});
test('cooking requires stations and both people can finish a shared recipe',()=>{const s=setup('cook');assert.throws(()=>press(s,a,'work'),/Ingredients/);for(let i=0;i<3;i++){const p=i%2?a:b;Object.assign(s.members.get(p.id),STATIONS[0]);press(s,p,'work');}for(let i=0;i<6;i++){const p=i%2?a:b;Object.assign(s.members.get(p.id),STATIONS[1]);press(s,p,'work');}assert.equal(s.games.cook.step,4);Object.assign(s.members.get('a'),STATIONS[2]);press(s,a,'work');assert.equal(s.games.cook.step,4);wait(s,5.1);press(s,a,'work');assert.equal(s.games.cook.step,5);Object.assign(s.members.get('b'),STATIONS[3]);press(s,b,'work');assert.equal(s.games.cook.served,1);assert.equal(s.games.cook.recipe,1);assert.ok(s.members.get('a').contribution&&s.members.get('b').contribution);});
test('Transition Town basketball and softball use both players inputs and real ball simulations',()=>{const s=setup('basketball');const x=s.games.basketball.basket.players[1].x;s.request(b,{op:'input',x:1,z:0});wait(s,.2);assert.ok(s.games.basketball.basket.players[1].x>x);press(s,a,'primary');assert.ok(s.games.basketball.basket.shot);const t=setup('softball');press(t,b,'pitch');assert.equal(t.games.softball.phase,'pitch');const p=t.games.softball.pitch;wait(t,p.windup+p.duration-.2);press(t,a,'swing');assert.ok(['live','foul'].includes(t.games.softball.phase));});
