import {test} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {openStore,initialize} from '../server/store.mjs';
test('private family boundary, invite approval, persistence and authoritative shared players',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'family-world-'));const db=openStore(dir);initialize(db,'test-only-family-passphrase');db.close();const port=19000+Math.floor(Math.random()*1000),origin=`http://localhost:${port}`;const child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:String(port),WORLD_ORIGIN:origin,WORLD_DATA_DIR:dir}});await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('exit',()=>reject(Error('Server did not start')));});
 const cookies={};async function call(path,body,who='mommy',requestOrigin=origin){const res=await fetch(origin+path,{method:body===undefined?'GET':'POST',headers:{Origin:requestOrigin,'Content-Type':'application/json',Cookie:cookies[who]||''},body:body===undefined?undefined:JSON.stringify(body),redirect:'manual'});const cookie=res.headers.get('set-cookie');if(cookie)cookies[who]=cookie.split(';')[0];return {status:res.status,res,body:res.headers.get('content-type')?.includes('json')?await res.json():null};}
 try{
 assert.equal((await call('/api/me')).status,401);assert.equal((await call('/classic/whiteboard.html')).status,302);assert.equal((await call('/client/../server/store.mjs')).status,404);
 assert.equal((await call('/api/login',{password:'test-only-family-passphrase'},'mommy','https://evil.test')).status,403);
 assert.equal((await call('/api/login',{password:'wrong'})).status,401);const login=await call('/api/login',{password:'test-only-family-passphrase'});assert.equal(login.status,200);assert.match(login.res.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
 assert.equal((await call('/api/me')).body.profiles.length,4);await call('/api/select',{profile:'mommy'});
 const expired=(await call('/api/invites',{profile:'unique'})).body.token;const edit=openStore(dir);edit.prepare('UPDATE invites SET expires=0').run();edit.close();assert.equal((await call('/api/invite/accept',{token:expired},'expired')).status,401);
 const invitation=(await call('/api/invites',{profile:'halli'})).body.token;assert.ok(invitation);assert.equal((await call('/api/invite/accept',{token:invitation},'halli')).status,200);assert.equal((await call('/api/invite/accept',{token:invitation},'stranger')).status,401);
 assert.deepEqual((await call('/api/me',undefined,'halli')).body.profiles.map(p=>p.id),['halli']);assert.equal((await call('/api/select',{profile:'mommy'},'halli')).status,403);assert.equal((await call('/api/invites',{profile:'jace'},'halli')).status,403);
 const guest=(await call('/api/invites',{guestName:'Approved Cousin'})).body;assert.match(guest.profile,/^guest-/);
 const hp=await call('/api/select',{profile:'halli'},'halli');assert.equal(hp.body.player.mode,'toddler');assert.equal((await call('/api/action',{action:'enter'},'halli')).status,409);
 const event=await fetch(origin+'/api/events',{headers:{Cookie:cookies.halli}});const reader=event.body.getReader();const chunk=await reader.read();const state=JSON.parse(new TextDecoder().decode(chunk.value).trim().slice(6));assert.equal(state.players.length,2);assert.equal(state.npcs.length,2);await reader.cancel();
 await call('/api/action',{action:'preferences',sound:false},'halli');await call('/api/logout',{},'halli');
 const second=(await call('/api/invites',{profile:'halli'})).body.token;await call('/api/invite/accept',{token:second},'halli');const again=await call('/api/select',{profile:'halli'},'halli');assert.equal(again.body.data.preferences.sound,false);
 const devices=(await call('/api/devices')).body.devices;const halliDevice=devices.find(d=>d.profile==='halli');await call('/api/revoke',{hash:halliDevice.hash});assert.equal((await call('/api/me',undefined,'halli')).status,401);assert.equal((await call('/classic/art.html',undefined,'halli')).status,302);
 const together=await call('/classic/together.html');const html=await together.res.text();assert.ok(!html.includes('<script src="https://cdn.jsdelivr.net'));assert.ok(html.includes("getElementById('host').disabled=true"));
 const jaceInvite=(await call('/api/invites',{profile:'jace'})).body.token;await call('/api/invite/accept',{token:jaceInvite},'jace');const third=(await call('/api/invites',{profile:'jace'})).body.token;await call('/api/invite/accept',{token:third},'another');await call('/api/select',{profile:'jace'},'jace');assert.equal((await call('/api/select',{profile:'jace'},'another')).status,409);
 await call('/api/select',{profile:'unique'});assert.equal((await call('/api/me')).body.role,'device');assert.equal((await call('/api/invites',{profile:'halli'})).status,403);
 }finally{child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));rmSync(dir,{recursive:true,force:true});}
});
