import {Playground} from './simulation.mjs?v=recess-1';
import {PlaygroundScene} from './scene.mjs?v=recess-1';
import {SPOTS,BASE,EQUIPMENT,dist} from './world.mjs';
const $=id=>document.getElementById(id),game=new Playground();let scene,muted=false,audio,last=0,acc=0,drag=null,stick={x:0,z:0},keys=new Set(),started=false;
function say(text){if(muted||!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.86;speechSynthesis.speak(u);}
function sound(kind){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const t=audio.currentTime;o.type=['bounce','kick','rim'].includes(kind)?'triangle':'sine';o.frequency.setValueAt(kind==='bounce'?150:kind==='rim'?650:kind==='win'?650:380,t);o.frequency.exponentialRampToValueAtTime(kind==='win'?980:90,t+.15);g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.start(t);o.stop(t+.21);}
function unlock(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch{}}
function choose(mode){unlock();game.switch(mode);$('activities').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));hud();}
$('activities').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.mode));
$('start').onclick=()=>{unlock();started=true;$('welcome').hidden=true;choose('hide');};
$('role').onclick=()=>game.start(game.role==='seeker'?'hider':'seeker');$('again').onclick=()=>game.start(game.role==='seeker'?'hider':'seeker');$('hide').onclick=()=>game.hide();$('base').onclick=()=>game.runBase();$('crouch').onclick=()=>{game.player.crouch=!game.player.crouch;};
$('difficulty').onchange=()=>{game.easy=$('difficulty').value==='easy';say(game.easy?'Easy mode. You run faster than your friends.':'Normal mode. Ready for a challenge?');};
$('view').onclick=()=>{scene.first=!scene.first;$('view').textContent=scene.first?'Third-person view':'First-person view';};
$('left').onclick=()=>scene.yaw+=Math.PI/4;$('right').onclick=()=>scene.yaw-=Math.PI/4;
$('sound').onclick=()=>{unlock();muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';if(muted)speechSynthesis?.cancel();};
$('pick').onclick=()=>game.pickup();$('shoot').onclick=()=>game.shoot(+$('aim').value,+$('power').value);$('kick').onclick=()=>game.kick(+$('aim').value,+$('power').value);$('dribble').onclick=()=>game.kick(0,.05);$('keeper').onchange=()=>game.keeper=$('keeper').checked;$('seat').onclick=()=>game.seat();$('pump').onclick=()=>game.pump();
$('ride').onclick=()=>game.ride();$('stopride').onclick=()=>game.stopRide();
$('help').onclick=()=>$('instructions').showModal();$('close-help').onclick=()=>$('instructions').close();
function release(){drag=null;stick={x:0,z:0};$('stick').hidden=true;keys.clear();}
const canvas=$('playground');canvas.onpointerdown=e=>{if(!started)return;unlock();canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,time:performance.now(),moved:false};};
canvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;drag.lastX=e.clientX;drag.lastY=e.clientY;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>12){drag.moved=true;const n=Math.max(45,Math.hypot(dx,dy));stick={x:dx/n,z:dy/n};const r=canvas.getBoundingClientRect();$('stick').hidden=false;$('stick').style.left=(drag.x-r.left)+'px';$('stick').style.top=(drag.y-r.top)+'px';}};
canvas.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;release();if(d.moved){if(game.mode==='basketball'&&game.basket.held&&e.clientY-d.y< -70&&performance.now()-d.time<400)game.shoot((e.clientX-d.x)/160,Math.min(1,(d.y-e.clientY)/250));return;}const hit=scene.pick(e.clientX,e.clientY);if(hit?.spot)game.investigate(hit.spot);else if(hit?.child){game.follow=hit.child;game.walk(game.children.find(c=>c.id===hit.child));game.follow=hit.child;}else if(hit)game.walk(hit);};canvas.onpointercancel=release;canvas.onlostpointercapture=release;
window.addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{release();acc=0;last=0;if(document.hidden)speechSynthesis?.cancel();});
let lastMessage='',lastHud=0;
function hud(){const hide=game.mode==='hide';$('hide-controls').hidden=!hide;$('sports-controls').hidden=!['basketball','soccer'].includes(game.mode);$('basket-controls').hidden=game.mode!=='basketball';$('soccer-controls').hidden=game.mode!=='soccer';$('seesaw-controls').hidden=game.mode!=='seesaw';$('explore-controls').hidden=game.mode!=='explore';$('hide').hidden=!hide||game.role!=='hider';$('base').hidden=!hide||game.role!=='hider';$('crouch').hidden=!hide||game.role!=='hider';$('again').hidden=game.phase!=='done';$('role').textContent=game.role==='seeker'?'Play as hider':'Play as seeker';$('crouch').textContent=game.player.crouch?'Stand up':'Crouch';$('seat').textContent=game.player.state==='seated'?'Get off':'Sit down';$('pump').disabled=game.player.state!=='seated';$('countdown').hidden=!(hide&&game.role==='seeker'&&game.phase==='count');$('countdown').textContent='Let’s count!\n'+Math.max(1,Math.ceil(game.left))+'\nYour friends are hiding';$('score').textContent=hide?(game.role==='seeker'?'You are seeking':'You are hiding')+' · '+(game.phase==='done'?'Round finished':Math.ceil(Math.max(0,game.left))+'s'):game.mode==='basketball'?game.baskets+' baskets':game.mode==='soccer'?game.goals+' goals':game.mode==='seesaw'?game.seesaw.stars+' teamwork stars':'School playground';if(lastMessage!==game.message){$('message').textContent=game.message;lastMessage=game.message;}$('shoot').disabled=!game.basket.held;$('playground').dataset.phase=game.phase;$('playground').dataset.playerX=game.player.x.toFixed(2);$('playground').dataset.playerZ=game.player.z.toFixed(2);map();}
function map(){const c=$('map').getContext('2d');c.clearRect(0,0,160,144);c.fillStyle='#edf4dcee';c.fillRect(0,0,160,144);c.fillStyle='#719763';c.fillRect(5,5,150,130);for(const o of EQUIPMENT){c.fillStyle=o.kind==='tree'||o.kind==='bush'?'#356749':'#c7a770';c.fillRect(80+o.x*2-o.w,70+o.z*2-o.d,Math.max(3,o.w*2),Math.max(3,o.d*2));}c.fillStyle='#ffe293';c.beginPath();c.arc(80,70,5,0,Math.PI*2);c.fill();c.fillStyle='#fff';c.strokeStyle='#1a5070';c.beginPath();c.arc(80+game.player.x*2,70+game.player.z*2,4,0,Math.PI*2);c.fill();c.stroke();}
try{scene=new PlaygroundScene(canvas);new ResizeObserver(()=>scene.resize()).observe(canvas);$('start').disabled=false;}catch(e){$('start').disabled=true;$('welcome-title').textContent='3D graphics could not start';$('welcome-copy').textContent='This playground needs WebGL 2. Try opening it in Safari or Chrome on your device. Your other games and video tours are still available.';$('graphics-error').textContent=e.message;}
function frame(now){const elapsed=last?Math.min(.08,(now-last)/1000):0;last=now;if(started&&!document.hidden){acc+=elapsed;while(acc>=1/60){const x=stick.x+Number(keys.has('ArrowRight')||keys.has('KeyD'))-Number(keys.has('ArrowLeft')||keys.has('KeyA')),z=stick.z+Number(keys.has('ArrowDown')||keys.has('KeyS'))-Number(keys.has('ArrowUp')||keys.has('KeyW'));const yaw=scene.first?game.player.heading+Math.PI:scene.yaw;game.direct(x*Math.cos(yaw)+z*Math.sin(yaw),z*Math.cos(yaw)-x*Math.sin(yaw),1/60);game.tick(1/60);acc-=1/60;}for(const event of game.events.splice(0)){if(event.text)say(event.text);if(!['say','count'].includes(event.kind))sound(event.kind);}if(now-lastHud>100){hud();lastHud=now;}}if(scene)scene.draw(game,elapsed||.016);requestAnimationFrame(frame);}requestAnimationFrame(frame);
