import {BASE,SPOTS,EQUIPMENT,COURT,SOCCER,dist,clamp,solid,occluded,route} from './world.mjs';
export class Playground {
 constructor(random=Math.random){this.random=random;this.time=0;this.mode='explore';this.phase='free';this.easy=true;this.role='seeker';this.round=0;this.events=[];this.player=this.child('jace',0,5);this.children=['Mia','Leo','Zoe'].map((n,i)=>this.child(n,-4+i*4,-5));this.basket=this.ball(COURT.spawn,.24);this.soccer=this.ball(SOCCER.spawn,.23);this.baskets=0;this.goals=0;this.keeper=true;this.keeperX=-5;this.seesaw={angle:0,velocity:0,stars:0,energy:0,cool:0,partner:0};this.message='Welcome to recess! Tap the ground to walk.';}
 child(id,x,z){return {id,x,z,y:0,heading:0,path:[],state:'idle',moving:false,crouch:false,hidden:null,anim:0,repath:0};}
 ball(p,r){return {...p,r,vx:0,vy:0,vz:0,held:false,scored:false};}
 emit(text,kind='say'){this.message=text;this.events.push({text,kind});}
 go(p,target){p.path=route(p,target);p.target={...target};}
 walk(target){this.follow=null;if(this.player.ride)return;if(this.player.hidden){const spot=SPOTS.find(s=>s.id===this.player.hidden);if(spot&&['house','tunnel'].includes(spot.kind)){this.player.x=spot.x;this.player.z=spot.z;}}if(this.phase==='count'&&this.role==='seeker'&&this.mode==='hide')return;this.player.hidden=null;this.player.crouch=false;this.player.investigate=null;this.go(this.player,target);}
 switch(mode){this.mode=mode;this.stopRide();this.player.path=[];this.player.hidden=null;this.player.crouch=false;this.player.y=0;this.player.state='idle';this.phase='free';this.children.forEach(c=>{c.hidden=null;c.state='idle';c.crouch=false;c.path=[];});if(mode==='hide')this.start(this.role);else if(mode==='basketball'){this.go(this.player,{x:21,z:15});this.emit('Walk to the basketball, pick it up, then aim and shoot.');}else if(mode==='soccer'){this.go(this.player,{x:-5,z:17});this.emit('Walk to the ball. Kick it toward the goal!');}else if(mode==='seesaw'){this.go(this.player,{x:6,z:-.2});this.emit('Walk to the seesaw, then tap Sit down.');}else this.emit('Explore the whole playground. Tap equipment to visit it.');}
 start(role=this.role){this.mode='hide';this.role=role;this.round++;this.phase=role==='seeker'?'count':'hide';this.left=10;this.player.state='idle';this.player.hidden=null;this.player.crouch=false;this.player.path=[];Object.assign(this.player,{x:0,z:5,y:0});this.lastCount=11;const spots=[...SPOTS];for(let i=spots.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[spots[i],spots[j]]=[spots[j],spots[i]];}this.children.forEach((c,i)=>{Object.assign(c,{x:(i-1)*2,z:-3,y:0,state:role==='seeker'?'scatter':'count',hidden:null,crouch:false,path:[],spot:spots[i],repath:0});if(role==='seeker')this.go(c,c.spot);});this.emit(role==='seeker'?'Your friends are hiding. Count with me!':'Your turn to hide! Choose a hiding place.');}
 investigate(id){const spot=SPOTS.find(s=>s.id===id);if(!spot)return;this.walk(spot);this.player.investigate=id;this.emit(this.role==='hider'&&this.mode==='hide'?'Walk to '+spot.name+' and get low.':'Let’s look at '+spot.name+'.');}
 hide(){const spot=SPOTS.find(s=>dist(this.player,s)<2.3);if(!spot){this.emit('Move close to equipment or bushes, then hide.');return false;}this.player.hidden=spot.id;if(['house','tunnel'].includes(spot.kind)){this.player.x=spot.cover.x;this.player.z=spot.cover.z;}this.player.crouch=true;this.player.path=[];this.emit('You are hiding by '+spot.name+'. Watch the seekers!');return true;}
 discover(c){if(c.state!=='hidden')return;if(c.hidden&&['house','tunnel'].includes(c.spot.kind)){c.x=c.spot.x;c.z=c.spot.z;}c.hidden=null;c.crouch=false;c.state='react';c.anim=.85;c.path=[];this.emit('There you are! Chase and tag before they reach base!','found');}
 runBase(){if(this.mode==='hide'&&this.role==='hider'){this.walk(BASE);this.player.crouch=false;this.emit('Run to the golden base!');}}
 move(p,dt,speed){p.moving=false;let target=p.path[0];if(!target)return;const d=dist(p,target);if(d<.12){p.path.shift();target=p.path[0];if(!target)return;}const dx=target.x-p.x,dz=target.z-p.z,n=Math.hypot(dx,dz),step=Math.min(n,speed*dt);p.heading=Math.atan2(dx,dz);const x=p.x+dx/n*step,z=p.z+dz/n*step;if(!solid(x,z)){p.x=x;p.z=z;p.moving=true;}else p.path=[];}
 direct(x,z,dt){if(!Number.isFinite(x+z)||this.player.ride||this.player.state==='seated'||(this.mode==='hide'&&(this.phase==='done'||this.phase==='count'&&this.role==='seeker')))return;const n=Math.max(1,Math.hypot(x,z));if(Math.hypot(x,z)<.1)return;if(this.player.hidden){const spot=SPOTS.find(s=>s.id===this.player.hidden);if(spot&&['house','tunnel'].includes(spot.kind)){this.player.x=spot.x;this.player.z=spot.z;}}this.player.path=[];this.player.hidden=null;this.player.investigate=null;this.follow=null;const speed=this.player.crouch?2:6.2,dx=x/n*speed*dt,dz=z/n*speed*dt;let moved=false;if(!solid(this.player.x+dx,this.player.z)){this.player.x+=dx;moved=true;}if(!solid(this.player.x,this.player.z+dz)){this.player.z+=dz;moved=true;}this.player.heading=Math.atan2(x,z);this.player.manualUntil=this.time+.1;this.player.moving=moved;}
 tick(dt){dt=clamp(dt,0,.04);this.time+=dt;if(this.follow){const c=this.children.find(c=>c.id===this.follow);if(c&&['run','react'].includes(c.state)){if((this.followAt||0)<this.time){this.go(this.player,c);this.followAt=this.time+.3;}}else this.follow=null;}if(this.player.ride){this.rideTick(dt);return;}this.player.anim=Math.max(0,this.player.anim-dt);if(this.player.state!=='seated'&&!(this.mode==='hide'&&this.phase==='done')){if((this.player.manualUntil||0)<this.time)this.move(this.player,dt,this.player.crouch?2:6.2);}if(this.player.investigate&&!this.player.path.length){const spot=SPOTS.find(s=>s.id===this.player.investigate);if(dist(this.player,spot)<2){if(this.mode==='hide'&&this.role==='hider')this.hide();else if(this.mode==='hide'){let found=false;for(const c of this.children)if(c.hidden===spot.id){this.discover(c);found=true;}if(!found)this.emit('Nobody here. Let’s try another place.');}this.player.investigate=null;}}
 if(this.mode==='hide')this.hideTick(dt);else for(const [i,c]of this.children.entries()){if(this.mode==='seesaw'&&i===0)continue;if(!c.path.length&&this.random()<dt*.2)this.go(c,SPOTS[Math.floor(this.random()*SPOTS.length)]);this.move(c,dt,1.7);}
 for(let left=dt;left>0;left-=1/120){const step=Math.min(left,1/120);this.ballTick(this.basket,step,'basketball');this.ballTick(this.soccer,step,'soccer');}
 if(this.mode==='soccer'&&this.keeper){const target=clamp(this.soccer.x,SOCCER.goal.x-2.5,SOCCER.goal.x+2.5);this.keeperX+=clamp(target-this.keeperX,-dt*2.2,dt*2.2);}
 const s=this.seesaw;s.cool-=dt;s.partner-=dt;if(this.player.state==='seated'){if(s.partner<=0&&s.angle<.05){s.velocity+=.9;s.partner=.8;}s.velocity+=(-s.angle*2.4-s.velocity*.6)*dt;s.angle=clamp(s.angle+s.velocity*dt,-.42,.42);if(Math.abs(s.angle)>=.42)s.velocity*=-.3;this.player.y=1.15-2.5*Math.sin(s.angle);this.children[0].y=1.15+2.5*Math.sin(s.angle);if(s.energy>=1){s.energy-=1;s.stars++;this.emit('A star for teamwork!','win');}}
 }
 hideTick(dt){const p=this.player;
 if(['count','hide'].includes(this.phase)){this.left-=dt;const count=Math.ceil(this.left);if(count>0&&count!==this.lastCount){this.lastCount=count;this.events.push({kind:'count',text:String(11-count)});}if(this.left<=0){this.phase='search';this.left=this.easy?180:120;this.emit('Ready or not, here we come!');if(this.role==='hider')this.children.forEach(c=>{c.state='search';c.searchAt=0;});}}
 if(this.phase==='done')return;
 for(const c of this.children){c.anim=Math.max(0,c.anim-dt);if(this.role==='seeker'){
  if(c.state==='scatter'){this.move(c,dt,7.2);if(!c.path.length){c.state='hidden';c.hidden=c.spot.id;c.crouch=true;if(['house','tunnel'].includes(c.spot.kind)){c.x=c.spot.cover.x;c.z=c.spot.cover.z;}}}
  if(this.phase==='search'&&c.state==='hidden'&&dist(p,c)<2.3&&!occluded(p,c)&&!['house','tunnel'].includes(c.spot.kind))this.discover(c);
  if(c.state==='react'&&c.anim<=0){c.state='run';this.go(c,BASE);}
  if(c.state==='run'){this.move(c,dt,this.easy?3.3:4.6);if(dist(p,c)<1.05&&!occluded(p,c)){c.state='tagged';c.path=[];c.anim=1;this.emit('Tag! You caught a friend!','tag');}else if(dist(c,BASE)<BASE.r){c.state='safe';c.path=[];c.anim=1;this.emit('Your friend reached base. Find the others!','safe');}}
 }else if(this.phase==='search'){
  c.searchAt-=dt;c.repath-=dt;
  if(c.state==='search'){
   if(!c.path.length&&c.searchAt<=0){c.spot=SPOTS[Math.floor(this.random()*SPOTS.length)];this.go(c,c.spot);c.searchAt=2.5;}
   this.move(c,dt,this.easy?2:2.8);
   const near=dist(c,p)<(this.easy?6:9),visible=!p.hidden&&!occluded(c,p),peek=p.hidden&&c.spot?.id===p.hidden&&dist(c,c.spot)<2.5;
   if(near&&visible||peek){c.state='react';c.anim=this.easy?1.6:.8;this.emit('They spotted you! Run to base!','found');if(p.hidden){const spot=SPOTS.find(s=>s.id===p.hidden);if(spot&&['house','tunnel'].includes(spot.kind)){p.x=spot.x;p.z=spot.z;}}p.hidden=null;p.crouch=false;}
  }else if(c.state==='react'&&c.anim<=0){c.state='chase';c.repath=0;}
  if(c.state==='chase'){if(c.repath<=0){this.go(c,p);c.repath=.45;}this.move(c,dt,this.easy?3.6:5.2);if(dist(c,p)<.95&&!occluded(c,p)){this.finish('Tagged! Good hiding. Let’s try again.');return;}}
 }
 }
 if(this.phase==='search'){this.left-=dt;if(this.role==='hider'&&dist(p,BASE)<BASE.r){this.finish('SAFE! You made it back to base!');return;}if(this.role==='seeker'&&this.children.every(c=>['safe','tagged'].includes(c.state))){this.finish(`Round finished! You tagged ${this.children.filter(c=>c.state==='tagged').length} friends.`);return;}if(this.left<=0)this.finish(this.role==='hider'?'You stayed hidden! Great job!':'Time for another round.');}
 }
 finish(text){this.phase='done';this.player.path=[];this.children.forEach(c=>{c.path=[];c.moving=false;});this.emit(text,'win');}
 ride(){if(this.mode!=='explore')return;const o=EQUIPMENT.find(o=>['slide','jungle','tunnel','swing'].includes(o.kind)&&dist(this.player,o)<Math.max(o.w,o.d)/2+2.5);if(!o){this.emit('Walk close to the slide, tunnel, swings or jungle gym first.');return;}this.player.ride={o,t:0};this.player.path=[];this.player.state='ride';this.emit('Here we go! Tap Step off whenever you like.');}
 stopRide(){if(!this.player.ride)return;const o=this.player.ride.o;this.player.ride=null;this.player.y=0;this.player.crouch=false;this.player.state='idle';const spot=SPOTS.find(s=>s.id===o.id);this.player.x=spot.x;this.player.z=spot.z;}
 rideTick(dt){const p=this.player,r=p.ride,o=r.o;r.t+=dt;const t=r.t;p.moving=true;if(o.kind==='slide'){if(t<3){p.x=o.x;p.z=o.z-3.4;p.y=t/3*2.5;p.heading=0;}else{const u=Math.min(1,(t-3)/2);p.x=o.x;p.z=o.z-.4+u*4.1;p.y=2.5*(1-(3*u*u-2*u*u*u))+.18;p.crouch=true;p.heading=0;if(u>=1)this.stopRide();}}if(o.kind==='tunnel'){p.x=o.x-3+t*.8;p.z=o.z;p.y=0;p.crouch=true;p.heading=Math.PI/2;if(t>7.5)this.stopRide();}if(o.kind==='jungle'){p.x=o.x-2.5+Math.min(1,t/6)*5;p.z=o.z;p.y=Math.min(1,t)*2;p.heading=Math.PI/2;if(t>7)this.stopRide();}if(o.kind==='swing'){const a=Math.sin(this.time*1.5)*.2;p.x=o.x-1.7;p.z=o.z-Math.sin(a)*2.45;p.y=3.3-Math.cos(a)*2.45;p.state='seated';p.heading=0;}}
 seat(){const o=EQUIPMENT.find(o=>o.kind==='seesaw');if(this.player.state==='seated'){this.player.state='idle';this.player.y=0;this.player.z=o.z+2;this.children[0].y=0;this.children[0].state='idle';return;}if(dist(this.player,{x:o.x-3,z:o.z+1.5})>3){this.emit('Walk to the seesaw first.');return;}Object.assign(this.player,{state:'seated',x:o.x-2.5,z:o.z,path:[],heading:Math.PI/2});Object.assign(this.children[0],{state:'seated',x:o.x+2.5,z:o.z,path:[],heading:-Math.PI/2});this.emit('Push when your seat is low. Your friend pushes too!');}
 pump(){const s=this.seesaw;if(this.player.state!=='seated'||s.cool>0)return;if(s.angle>-.05){s.velocity-=1.2;s.energy+=.22;s.cool=.65;this.emit('Good push!');}else this.emit('Wait until your seat comes down.');}
 pickup(){if(dist(this.player,this.basket)>1.8||this.basket.y>1){this.emit('Walk closer to the basketball.');return;}this.basket.held=true;this.emit('Aim at the hoop, then shoot!');}
 shoot(aim=0,power=.5){const b=this.basket;if(!b.held){this.pickup();return;}b.held=false;b.scored=false;const p=this.player,h=COURT.hoop,t=.95+dist(p,h)*.055,targetX=h.x+clamp(aim,-1,1)*2.8,targetZ=h.z+(clamp(power,0,1)-.5)*4;Object.assign(b,{x:p.x,y:1.5,z:p.z,vx:(targetX-p.x)/t,vz:(targetZ-p.z)/t,vy:(h.y-1.5+4.905*t*t)/t});p.heading=Math.atan2(targetX-p.x,targetZ-p.z);p.anim=.65;this.events.push({kind:'throw',text:''});}
 kick(aim=0,power=.6){const b=this.soccer;if(dist(this.player,b)>1.8){this.emit('Walk to the soccer ball first.');return;}const angle=this.player.heading+clamp(aim,-1,1)*.9,speed=3+clamp(power,0,1)*11;Object.assign(b,{vx:Math.sin(angle)*speed,vz:Math.cos(angle)*speed,vy:1+power*2,scored:false});this.player.anim=.5;this.events.push({kind:'kick',text:''});}
 ballTick(b,dt,kind){if(b.held){b.x=this.player.x;b.z=this.player.z+.4;b.y=1.1;return;}const oldY=b.y,oldZ=b.z;b.vy-=9.81*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.z+=b.vz*dt;if(b.y<b.r){b.y=b.r;if(Math.abs(b.vy)>1.2)this.events.push({kind:'bounce',text:''});b.vy=Math.abs(b.vy)>.45?-b.vy*.64:0;b.vx*=Math.exp(-dt*1.1);b.vz*=Math.exp(-dt*1.1);}if(Math.abs(b.x)>33.5){b.x=clamp(b.x,-33.5,33.5);b.vx*=-.6;}if(Math.abs(b.z)>29.5){b.z=clamp(b.z,-29.5,29.5);b.vz*=-.6;}
 // Solid playground props deflect loose balls; low balls cannot roll through structures.
 for(const o of EQUIPMENT){if(o.kind==='bush'||o.kind==='swing'||o.kind==='seesaw'||b.y>2.3)continue;const qx=clamp(b.x,o.x-o.w/2,o.x+o.w/2),qz=clamp(b.z,o.z-o.d/2,o.z+o.d/2),dx=b.x-qx,dz=b.z-qz,d=Math.hypot(dx,dz);if(d>0&&d<b.r){const nx=dx/d,nz=dz/d,dot=b.vx*nx+b.vz*nz;b.x=qx+nx*b.r;b.z=qz+nz*b.r;if(dot<0){b.vx-=1.6*dot*nx;b.vz-=1.6*dot*nz;}}}
 if(kind==='soccer')for(const x of[-8,-2]){const dx=b.x-x,dz=b.z-28,d=Math.hypot(dx,dz);if(d<b.r+.07&&d>.001&&b.y<2.55){const nx=dx/d,nz=dz/d,dot=b.vx*nx+b.vz*nz;b.x=x+nx*(b.r+.07);b.z=28+nz*(b.r+.07);if(dot<0){b.vx-=1.7*dot*nx;b.vz-=1.7*dot*nz;}}}
 if(kind==='basketball'){
 const h=COURT.hoop,rho=Math.hypot(b.x-h.x,b.z-h.z),rimY=b.y-h.y;
 if(Math.abs(rimY)<b.r+.045&&Math.abs(rho-.46)<b.r+.045){const nx=(b.x-h.x)/(rho||1),nz=(b.z-h.z)/(rho||1),rx=h.x+nx*.46,rz=h.z+nz*.46;let dx=b.x-rx,dy=b.y-h.y,dz=b.z-rz,l=Math.hypot(dx,dy,dz)||1;dx/=l;dy/=l;dz/=l;const dot=b.vx*dx+b.vy*dy+b.vz*dz;if(dot<0){b.vx-=1.65*dot*dx;b.vy-=1.65*dot*dy;b.vz-=1.65*dot*dz;this.events.push({kind:'rim',text:''});}}
 if(b.vz<0&&oldZ>=4.35+b.r&&b.z<4.35+b.r&&Math.abs(b.x-21)<1.2&&b.y>2.6&&b.y<4.1){b.z=4.35+b.r;b.vz*=-.7;}
 if(!b.scored&&b.vy<0&&oldY>=h.y&&b.y<h.y&&rho<.46-b.r*.5){b.scored=true;this.baskets++;this.netUntil=this.time+1;this.emit('Basket! Go get your ball!','win');}
 }else{
 if(this.keeper&&b.vz>0&&oldZ<27&&b.z>=27&&Math.abs(b.x-this.keeperX)<.7&&b.y<1.7){b.z=26.9;b.vz*=-.7;this.emit('Saved! Try the other side.','kick');}
 if(!b.scored&&oldZ<28&&b.z>=28&&Math.abs(b.x+5)<2.8&&b.y<2.5){b.scored=true;this.goals++;b.vz*=-.25;this.emit('Goal! The ball is still yours.','win');}
 }
 }
}
