const $=id=>document.getElementById(id),dialog=$('player'),video=$('video');let clips=[],selected=null,step=0,playing=false,watching=false,voice=false,completed=new Set(),opener=null;
try{completed=new Set(JSON.parse(localStorage.getItem('jhw-park-adventures-v1')||'[]'));}catch{}
const say=t=>{if(!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.9;speechSynthesis.speak(u);};
function progress(){$('progress').textContent=completed.size+' adventures explored';}
function dots(){$('steps').replaceChildren(...[0,1,2].map(i=>{const s=document.createElement('span');s.className=i<step?'done':'';return s;}));}
function cue(){dots();$('action').disabled=playing;$('action').hidden=step>=3||watching;$('replay').hidden=step<3;$('watch').hidden=watching||step>=3;$('cue').textContent=playing?'Here we go…':selected.prompts[step]||'Great exploring!';$('action').textContent=selected.prompts[step]||'Let’s go!';}
function close(){video.pause();video.removeAttribute('src');video.load();playing=false;watching=false;window.speechSynthesis?.cancel();if(dialog.open)dialog.close();opener?.focus();}
async function open(id){const clip=clips.find(c=>c.id===id);if(!clip)return;opener=document.activeElement;video.pause();selected=clip;step=0;playing=false;watching=false;$('title').textContent=clip.title;$('source').textContent=clip.source==='Family park movie'?'JACE & HALLI’S OWN PARK ADVENTURE':'FROM OUR SCHOOL RECESS';$('reward').hidden=true;$('status').textContent='';video.poster=clip.poster||'world/assets/park/approved-park.webp';video.src=clip.src;video.muted=true;video.controls=false;video.load();cue();if(!dialog.open)dialog.showModal();say(clip.title);}
function win(){if(step===3)return;step=3;playing=false;video.pause();$('reward').hidden=false;completed.add(selected.id);try{localStorage.setItem('jhw-park-adventures-v1',JSON.stringify([...completed]));}catch{}progress();cue();say('We did it!');}
function stopPoint(){if(!selected)return Infinity;if(selected.stops)return selected.stops[step];return Number.isFinite(video.duration)?video.duration*(selected.fractionalStops[step]||1):Infinity;}
video.addEventListener('timeupdate',()=>{if(!playing||watching)return;if(video.currentTime>=stopPoint()-.08){video.pause();playing=false;step++;if(step>=3){step=2;win();}else{cue();say(selected.prompts[step]);}}});video.onended=win;
video.onerror=()=>{playing=false;$('status').textContent='This clip could not load. Check your connection and tap Play again.';$('replay').hidden=false;$('replay').textContent='Play again';$('action').disabled=false;};
$('action').onclick=async()=>{if(!selected||playing)return;playing=true;cue();$('status').textContent='';try{await video.play();}catch{playing=false;cue();$('status').textContent='Tap the video’s play button to start.';video.controls=true;}};
$('watch').onclick=async()=>{watching=true;playing=true;video.controls=true;cue();try{await video.play();}catch{$('status').textContent='Tap play on the video.';}};
$('replay').onclick=()=>open(selected.id);$('close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
$('sound').onclick=()=>{voice=!voice;$('sound').textContent=voice?'Voice on':'Voice off';$('sound').setAttribute('aria-pressed',String(voice));if(!voice)window.speechSynthesis?.cancel();else say('Let’s play at our park!');};
$('world').onclick=()=>{close();if(parent!==window)parent.postMessage({channel:'jhw-park',type:'exit'},location.origin);else location.href='index.html';};
$('explore').onclick=()=>{$('adventures').scrollIntoView({behavior:'smooth'});say('Where should we play?');};document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));
document.addEventListener('visibilitychange',()=>{if(document.hidden&&selected){video.pause();playing=false;window.speechSynthesis?.cancel();cue();}});window.addEventListener('pagehide',()=>video.pause());
try{const r=await fetch('world/client/park/clips.json?v=1');if(!r.ok)throw Error();clips=await r.json();for(const clip of clips){const b=document.createElement('button');b.className='activity';b.dataset.clip=clip.id;const im=document.createElement('img');im.src=clip.poster||'world/assets/scenes/school-v1.webp';im.alt='';im.loading='lazy';const name=document.createElement('span');name.textContent=clip.title;const source=document.createElement('small');source.textContent=clip.source==='Family park movie'?'Our own adventure':'School recess';b.append(im,name,source);b.onclick=()=>open(clip.id);$('activities').append(b);}progress();}catch{$('progress').textContent='Adventures could not load. Please refresh.';}
