import {clamp,sweptHit,tossVelocity,stepFoam} from './physics.mjs?v=bubble-1';
const $=id=>document.getElementById(id),canvas=$('play'),ctx=canvas.getContext('2d'),root=$('garden');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let w=innerWidth,h=innerHeight,dpr=1,mode='buddy',time=0,last=0,raf,muted=false,audio,lastPop=0,responseUntil=0,spawnClock=0;
let bubbles=[],sparks=[],foam=[],board=[],strokes=[],pointers=new Map(),buddy={x:w*.52,y:h*.48,r:88,joy:0};
const descriptions={buddy:['Meet your bubble buddy','Touch, tickle, pop!'],blow:['A little breath. A big bubble!','Blow together · touch and hold · let go'],foam:['Scoop a cloud of bubbles','Pick it up. Toss it. Wheee!'],board:['A whole world of pop','Sweep your finger to pop and draw']};
const send=type=>{if(parent!==window)parent.postMessage({channel:'jhw-bubbles',type},location.origin);};
function unlock(){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function popSound(big=false){if(muted||!audio||audio.state!=='running'||audio.currentTime-lastPop<.035)return;lastPop=audio.currentTime;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(big?360:650+Math.random()*300,audio.currentTime);o.frequency.exponentialRampToValueAtTime(140,audio.currentTime+.11);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.1,audio.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.15);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.16);o.onended=()=>{o.disconnect();g.disconnect();};}
function feedback(text){$('response').textContent=text;$('response').classList.add('show');responseUntil=time+1.1;}
function bubble(x=Math.random()*w,y=Math.random()*h,r=30+Math.random()*30){return{x,y,r,vx:(Math.random()-.5)*24,vy:-12-Math.random()*18,hue:Math.random()*360,phase:Math.random()*6,age:0};}
function burst(b){popSound(b.r>65);for(let i=0;i<(reduced?5:12);i++){const a=i*Math.PI/6;sparks.push({x:b.x+Math.cos(a)*b.r,y:b.y+Math.sin(a)*b.r,vx:Math.cos(a)*90,vy:Math.sin(a)*90,life:.7,hue:b.hue||190});}if(sparks.length>180)sparks.splice(0,sparks.length-180);}
function boardFill(){board=[];const r=clamp(w/17,24,39),gap=r*2.2;for(let row=0,y=24;y<h+gap;y+=gap,row++)for(let x=18+(row%2)*gap/2;x<w+gap;x+=gap)board.push({...bubble(x,y,r),popped:false});}
function resize(){const oldW=w,oldH=h;w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);for(const b of [...bubbles,...foam]){b.x*=w/oldW;b.y*=h/oldH;}buddy.x=w*.52;buddy.y=h*.48;buddy.r=clamp(Math.min(w,h)*.17,55,100);pointers.clear();strokes=[];boardFill();}
function choose(next){pointers.clear();mode=next;root.dataset.mode=mode;root.classList.remove('board-only');bubbles=[];foam=[];sparks=[];strokes=[];spawnClock=0;feedback('');$('response').classList.remove('show');$('title').textContent=descriptions[mode][0];$('hint').textContent=descriptions[mode][1];$('fresh').hidden=mode!=='board';$('grownups').open=false;document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));canvas.setAttribute('aria-label',descriptions[mode].join('. ')+'. Space also plays.');if(mode==='board')boardFill();if(mode==='buddy')for(let i=0;i<13;i++)bubbles.push(bubble(Math.random()*w,h*.25+Math.random()*h*.55));if(mode==='foam')for(let i=0;i<55;i++)foam.push({...bubble(Math.random()*w,h*.66+Math.random()*50,14+Math.random()*24),vx:0,vy:0});}
function drawBubble(b,alpha=1,face=false){ctx.save();ctx.globalAlpha=alpha;ctx.translate(b.x,b.y);const stretch=face?1+Math.sin(time*4)*.025+buddy.joy*.05:1;ctx.scale(stretch,1/stretch);const r=b.r;const g=ctx.createRadialGradient(-r*.3,-r*.4,r*.04,0,0,r);g.addColorStop(0,'#ffffffb8');g.addColorStop(.24,face?'#d3f6ffbd':'#d6fbff25');g.addColorStop(.68,face?'#b1d5f5c9':'#b0f5ff19');g.addColorStop(.86,'#e3a7f397');g.addColorStop(.96,'#adf9fbd9');g.addColorStop(1,'#fffefbd9');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.lineWidth=Math.max(1.3,r*.045);const ring=ctx.createLinearGradient(-r,-r,r,r);ring.addColorStop(0,'#fff');ring.addColorStop(.25,'#b5f2ff');ring.addColorStop(.5,'#ecb0f5');ring.addColorStop(.75,'#ffeeae');ring.addColorStop(1,'#bbffeb');ctx.strokeStyle=ring;ctx.stroke();ctx.strokeStyle='#ffffffbd';ctx.lineWidth=r*.085;ctx.lineCap='round';ctx.beginPath();ctx.arc(0,0,r*.77,3.6,4.5);ctx.stroke();ctx.fillStyle='#ffffffc0';ctx.beginPath();ctx.ellipse(r*.42,r*.55,r*.15,r*.06,-.6,0,7);ctx.fill();if(face){const blink=Math.sin(time*.8)> .998;for(const x of [-.29,.29]){ctx.fillStyle='#273d57';ctx.beginPath();ctx.ellipse(r*x,-r*.02,r*.085,blink?r*.02:r*.14,0,0,7);ctx.fill();ctx.fillStyle='white';ctx.beginPath();ctx.arc(r*x-r*.023,-r*.064,r*.025,0,7);ctx.fill();ctx.fillStyle='#ee99beb0';ctx.beginPath();ctx.ellipse(r*x*1.5,r*.21,r*.14,r*.08,0,0,7);ctx.fill();}ctx.strokeStyle='#32445d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,r*.15,r*.2,.15,Math.PI-.15);ctx.stroke();}ctx.restore();}
function hitStroke(a,b){if(mode==='board'){for(const q of board)if(!q.popped&&sweptHit(a,b,q,q.r+10)){q.popped=true;burst(q);}strokes.push({a:{...a},b:{...b},hue:(time*26)%360});if(strokes.length>1600)strokes.splice(0,100);return;}for(let i=bubbles.length-1;i>=0;i--)if(sweptHit(a,b,bubbles[i],bubbles[i].r+12)){burst(bubbles[i]);bubbles.splice(i,1);}
if(mode==='buddy'&&sweptHit(a,b,buddy,buddy.r+15)){buddy.joy=1;feedback('Hello, Halli!');if(bubbles.length<32)for(let i=0;i<3;i++)bubbles.push(bubble(buddy.x+(Math.random()-.5)*180,buddy.y-50,25+Math.random()*20));popSound(true);}}
function point(e){return{x:e.clientX,y:e.clientY};}
function down(e){if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();unlock();canvas.setPointerCapture(e.pointerId);const p=point(e);pointers.set(e.pointerId,{...p,last:{...p},stamp:performance.now(),vx:0,vy:0,grown:0});if(mode==='foam'){const selected=foam.filter(b=>b.held===undefined&&Math.hypot(b.x-p.x,b.y-p.y)<120).slice(0,16);while(selected.length<12){const b={...bubble(p.x+(Math.random()-.5)*85,p.y+(Math.random()-.5)*70,15+Math.random()*18),vx:0,vy:0};foam.push(b);selected.push(b);}for(const b of selected){b.held=e.pointerId;b.dx=b.x-p.x;b.dy=b.y-p.y;}feedback('Scoop!');}else if(mode==='blow'){const q=bubble(p.x,p.y,22);q.held=e.pointerId;bubbles.push(q);}else hitStroke(p,p);}
function move(e){const p=pointers.get(e.pointerId);if(!p)return;e.preventDefault();const next=point(e),now=performance.now();Object.assign(p,tossVelocity(p,next,(now-p.stamp)/1000));if(mode==='buddy'||mode==='board')hitStroke(p,next);p.last={x:p.x,y:p.y};p.x=next.x;p.y=next.y;p.stamp=now;if(mode==='foam')for(const b of foam)if(b.held===e.pointerId){b.x=p.x+b.dx;b.y=p.y+b.dy;}if(mode==='blow')for(const b of bubbles)if(b.held===e.pointerId){b.x=p.x;b.y=p.y;}}
function up(e,cancelled=false){const p=pointers.get(e.pointerId);if(!p)return;const stale=performance.now()-p.stamp>120;for(const b of foam)if(b.held===e.pointerId){delete b.held;b.vx=cancelled||stale?0:p.vx;b.vy=cancelled||stale?-150:p.vy;}for(const b of bubbles)if(b.held===e.pointerId){delete b.held;b.vx=cancelled?0:p.vx*.12;b.vy=-35;b.r=Math.max(30,b.r);}if(!cancelled&&mode==='foam'){feedback('Wheee!');popSound(true);}if(!cancelled&&mode==='blow'){feedback('You made a bubble!');popSound(true);}pointers.delete(e.pointerId);}
canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',e=>up(e,true));canvas.addEventListener('lostpointercapture',e=>up(e,true));
canvas.addEventListener('keydown',e=>{if(e.code!=='Space'&&e.code!=='Enter')return;e.preventDefault();unlock();if(mode==='board'){const b=board.find(b=>!b.popped&&b.y>h*.25&&b.y<h*.7);if(b)hitStroke(b,b);}else if(mode==='foam'){foam.push({...bubble(w/2,h*.45,40),vx:150,vy:-350});}else{bubbles.push(bubble(w*.5,h*.55,65));buddy.joy=1;popSound();}});
function wand(){const x=w*.5,y=h*.69,r=clamp(h*.09,26,52);ctx.save();ctx.lineCap='round';ctx.strokeStyle='#ad538f';ctx.lineWidth=17;ctx.beginPath();ctx.moveTo(x-r*.45,y+r*.8);ctx.lineTo(x-r,h*.88);ctx.stroke();ctx.strokeStyle='#f7b1df';ctx.lineWidth=10;ctx.stroke();ctx.strokeStyle='#ffcbe9';ctx.lineWidth=9;ctx.beginPath();ctx.ellipse(x,y,r,r*1.12,.4,0,7);ctx.stroke();ctx.restore();drawBubble({x,y,r:r*.8},.35);}
function machine(){const x=w*.13,y=h*.68,r=clamp(w*.05,30,60);ctx.save();ctx.translate(x,y);ctx.fillStyle='#b873bd';ctx.strokeStyle='#ffe8fa';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(-r,-r*.7,r*2,r*1.6,18);ctx.fill();ctx.stroke();ctx.fillStyle='#684789';ctx.beginPath();ctx.ellipse(0,-r*.65,r*.64,r*.35,0,0,7);ctx.fill();ctx.fillStyle='#ffd98d';ctx.beginPath();ctx.arc(0,r*.2,r*.18,0,7);ctx.fill();ctx.restore();}
function frame(ms){const dt=Math.min((ms-last)/1000||.016,.033);last=ms;time+=dt;ctx.clearRect(0,0,w,h);if(time>responseUntil)$('response').classList.remove('show');spawnClock+=dt;
if(mode==='board'){ctx.lineCap='round';ctx.lineWidth=36;for(const s of strokes){ctx.strokeStyle=`hsla(${s.hue},75%,68%,.85)`;ctx.beginPath();ctx.moveTo(s.a.x,s.a.y);ctx.lineTo(s.b.x+.1,s.b.y);ctx.stroke();}for(const b of board)if(!b.popped)drawBubble(b,.94);}
if(mode==='blow')wand();if(mode==='foam'){machine();if(spawnClock>.23&&foam.length<105){foam.push({...bubble(w*.13,h*.61,15+Math.random()*20),vx:(Math.random()-.2)*100,vy:-130});spawnClock=0;}for(const b of foam){if(b.held===undefined)stepFoam(b,dt,w,h-105);drawBubble(b,.96);}if(foam.length>150){const i=foam.findIndex(b=>b.held===undefined);if(i>=0)foam.splice(i,1);}}
if(mode==='buddy'&&spawnClock>.65&&bubbles.length<18){bubbles.push(bubble(Math.random()*w,h+60));spawnClock=0;}
for(let i=bubbles.length-1;i>=0;i--){const b=bubbles[i];if(b.held!==undefined){b.r=Math.min(125,b.r+dt*45);}else{b.x+=(b.vx+Math.sin(time+b.phase)*8)*dt*(reduced?.3:1);b.y+=b.vy*dt*(reduced?.3:1);b.age+=dt;}drawBubble(b);if(b.y< -b.r||b.x< -180||b.x>w+180||b.age>35)bubbles.splice(i,1);}
if(mode==='buddy'){const p=pointers.values().next().value;const tx=p?clamp(p.x,100,w-100):w*.52+Math.sin(time*.6)*(reduced?0:35),ty=p?clamp(p.y,175,h-150):h*.49+Math.cos(time*.8)*(reduced?0:15);buddy.x+=(tx-buddy.x)*dt*2;buddy.y+=(ty-buddy.y)*dt*2;buddy.joy=Math.max(0,buddy.joy-dt);drawBubble(buddy,1,true);}
for(let i=sparks.length-1;i>=0;i--){const s=sparks[i];s.life-=dt;s.x+=s.vx*dt;s.y+=s.vy*dt;ctx.globalAlpha=Math.max(0,s.life/.7);ctx.fillStyle=`hsl(${s.hue},90%,85%)`;ctx.beginPath();ctx.arc(s.x,s.y,3+s.life*3,0,7);ctx.fill();if(s.life<=0)sparks.splice(i,1);}ctx.globalAlpha=1;raf=requestAnimationFrame(frame);}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{unlock();choose(b.dataset.mode);});$('fresh').onclick=()=>{unlock();boardFill();strokes=[];popSound();};$('immersive').onclick=()=>{choose('board');root.classList.add('board-only');};$('exit').onclick=()=>{if(root.classList.contains('board-only')){root.classList.remove('board-only');return;}if(parent!==window)send('exit');else location.href='index.html';};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(!muted));$('sound').setAttribute('aria-label',muted?'Turn sound on':'Turn sound off');if(muted)audio?.suspend();else unlock();};
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{cancelAnimationFrame(raf);for(const id of [...pointers.keys()])up({pointerId:id},true);if(document.hidden)audio?.suspend();else{last=performance.now();raf=requestAnimationFrame(frame);}});window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);audio?.close();});resize();choose('buddy');send('active');raf=requestAnimationFrame(frame);
