import {readMedia,saveMedia,removeMedia,checkMedia} from './media-store.mjs?v=church-1';
import {WELCOME,OPENING_PRAYER,CLOSING_PRAYER,PRAYER_PROMPT,DISMISSAL,AUDIO,LESSONS,SONGS,SERVICE_STEPS,nextLesson} from './data.mjs?v=church-1';
const $=id=>document.getElementById(id), stage=$('stage');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const put=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch{}};
const ROTATION='jhw.church.rotation.v1',PREFS='jhw.church.preferences.v1';
let preferences=get(PREFS,{local:false,sound:true}),step=0,lesson,token=0,paused=false,currentSpeech=null,currentAudio=null,player=null,ytPromise=null,repeatAction=null,countdown=null;
const timers=new Set(),cancellers=new Set();let localVideo=null,localURL=null;
const recorded=new Audio();recorded.preload='metadata';
const chatter=new Audio('world/assets/church/crowd-murmur.mp3');chatter.loop=true;chatter.volume=.16;
function status(text=''){$('status').textContent=text;}
function setSound(enabled){preferences.sound=enabled;put(PREFS,preferences);$('sound').textContent=enabled?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(enabled));recorded.muted=!enabled;chatter.muted=!enabled;if(localVideo)localVideo.muted=!enabled;if(!enabled){window.speechSynthesis?.cancel();currentSpeech=null;}if(player){try{enabled?player.unMute():player.mute();}catch{}}}
function stop(){token++;if(localVideo){localVideo.pause();localVideo.removeAttribute('src');localVideo.load();localVideo=null;}if(localURL){URL.revokeObjectURL(localURL);localURL=null;}for(const t of timers)clearInterval(t);timers.clear();for(const cancel of [...cancellers])cancel();cancellers.clear();window.speechSynthesis?.cancel();currentSpeech=null;recorded.pause();recorded.onended=null;recorded.onerror=null;recorded.ontimeupdate=null;currentAudio=null;chatter.pause();if(player){try{player.destroy();}catch{}player=null;}paused=false;document.body.classList.remove('paused');$('break').open&&$('break').close();countdown=null;}
function wait(ms,t=token){return new Promise(resolve=>{let left=ms,last=performance.now(),done=false;const finish=()=>{if(done)return;done=true;clearInterval(timer);timers.delete(timer);cancellers.delete(finish);resolve(t===token);};const timer=setInterval(()=>{const now=performance.now();if(!paused)left-=now-last;last=now;if(left<=0||t!==token)finish();},40);timers.add(timer);cancellers.add(finish);});}
function speak(text,t=token){return new Promise(resolve=>{
 if(t!==token)return resolve(false);if(!preferences.sound)return wait(Math.max(1300,text.split(/\s+/).length*360),t).then(resolve);
 if(!('speechSynthesis'in window)){status('Read these words together. Tap Continue when you are ready.');return wait(Math.max(2000,text.split(/\s+/).length*400),t).then(resolve);}
 let done=false,started=false,elapsed=0,last=performance.now();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.83;u.pitch=.93;
 const voices=speechSynthesis.getVoices().filter(v=>/^en[-_]/i.test(v.lang));u.voice=voices.find(v=>/Alex|Daniel|David|Mark|Tom|Aaron|Fred|Gordon|Arthur/i.test(v.name))||voices.find(v=>v.lang==='en-US')||voices[0]||null;
 const finish=()=>{if(done)return;done=true;clearInterval(watch);timers.delete(watch);cancellers.delete(cancel);if(currentSpeech===u)currentSpeech=null;resolve(t===token);};const cancel=()=>{speechSynthesis.cancel();finish();};
 u.onstart=()=>started=true;u.onend=finish;u.onerror=()=>{if(t===token)status('Voice is unavailable on this device. The words stay on screen.');finish();};
 const watch=setInterval(()=>{const now=performance.now();if(!paused)elapsed+=now-last;last=now;if(t!==token)return cancel();if(!started&&elapsed>5000){status('Tap Hear again if the device voice did not start.');cancel();}if(elapsed>Math.max(20000,text.length*150))cancel();},200);
 timers.add(watch);cancellers.add(cancel);currentSpeech=u;speechSynthesis.speak(u);
 });}
async function recording(src,start,end,text,t=token){
 if(!preferences.sound)return speak(text,t);
 const ok=await new Promise(resolve=>{let done=false,playing=false;const finish=good=>{if(done)return;done=true;clearTimeout(fail);recorded.pause();recorded.onended=null;recorded.onerror=null;recorded.ontimeupdate=null;recorded.onloadedmetadata=null;cancellers.delete(cancel);currentAudio=null;resolve(good&&t===token);};const cancel=()=>finish(false);cancellers.add(cancel);
 recorded.src=src;recorded.muted=!preferences.sound;currentAudio=recorded;
 const begin=()=>{if(done||t!==token)return;try{recorded.currentTime=start;}catch{}recorded.play().then(()=>playing=true).catch(()=>finish(false));};
 recorded.onloadedmetadata=begin;recorded.onended=()=>finish(true);recorded.onerror=()=>finish(false);recorded.ontimeupdate=()=>{if(recorded.currentTime>=end)finish(true);};
 const fail=setTimeout(()=>{if(!playing)finish(false);},4500);recorded.load();
 });
 if(!ok&&t===token)return speak(text,t);return ok;
}
function updateSteps(){$('steps').innerHTML=SERVICE_STEPS.map((s,i)=>`<span class="${i===step?'current':i<step?'done':''}" ${i===step?'aria-current="step"':''}>${i+1}. ${s}</span>`).join('');$('pause').hidden=step===0||step===7;$('repeat').hidden=!repeatAction;}
function setRepeat(fn){repeatAction=fn;$('repeat').hidden=!fn;}
function selectLesson(id){if(id&&id!=='shuffle'){lesson=LESSONS.find(l=>l.id===id)||LESSONS[0];return;}const next=nextLesson(get(ROTATION,{}));lesson=next.lesson;put(ROTATION,next.state);}
function ambience(){if(preferences.sound&&!paused)chatter.play().catch(()=>{});}
function renderWelcome(){stop();step=0;setRepeat(null);updateSteps();stage.innerHTML=`<div class="welcome"><div class="panel"><span class="eyebrow">Come sit with us</span><h1>It’s time<br>for church.</h1><p>Jace & Halli, find your seat beside Mommy.</p><div class="manners"><span>Quiet voices</span><span>Feet down</span><span>Listening ears</span></div><button id="enter-church" class="primary">Come in & hear welcome</button><p class="small">Today’s Bible story: ${esc(lesson.title)}</p></div></div>`;$('enter-church').onclick=welcome;status('Tap once to begin the church sounds.');}
async function welcome(){stop();const t=token;ambience();$('enter-church').disabled=true;status('Our church family is finding their seats.');await wait(2400,t);if(t!==token)return;chatter.volume=.045;status('Our preacher welcomes you.');stage.querySelector('p').textContent='Good morning, everybody. Please find your seat. We are about to start church service.';
 await recording(AUDIO.welcome,0,26.72,WELCOME,t);if(t!==token)return;chatter.pause();stage.querySelector('p').textContent='Welcome to Jace & Halli’s World Church of Christ. Pay attention to the lesson and remain seated during service.';const b=$('enter-church');b.disabled=false;b.textContent='Start Church';b.onclick=()=>go(1);setRepeat(welcome);status('Ready? Press Start Church.');}
function go(next){stop();step=next;setRepeat(()=>go(step));updateSteps();status('');if(next===1||next===5)song(next===1?'opening':'closing');else if(next===2||next===6)prayer(next===6);else if(next===3)lessonStart();else if(next===4)quiz(0);else if(next===7)dismiss();else renderWelcome();}
function loadYT(){if(window.YT?.Player)return Promise.resolve();if(ytPromise)return ytPromise;ytPromise=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Video player is unavailable.')),10000);window.onYouTubeIframeAPIReady=()=>{clearTimeout(timeout);resolve();};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{clearTimeout(timeout);reject(Error('Video player is unavailable.'));};document.head.append(s);});return ytPromise;}
function mediaShell(title,detail,buttonLabel){stage.innerHTML=`<div class="media-heading"><h2>${esc(title)}</h2><small>${esc(detail)}</small></div><div class="screen" id="screen"><img class="video-poster" src="world/assets/church/sanctuary.webp" alt="Our family sitting together in church"><div class="play-cover"><h2>${esc(title)}</h2><button id="play-media" class="primary">${esc(buttonLabel)}</button></div></div><div id="media-extra"></div><div class="media-actions"><button id="fallback" class="secondary"></button><button id="finished" class="secondary">We finished — continue</button></div>`;}
async function playVideo(media,onEnd,fallback){const t=token;const local=await readMedia(media.slot||lesson.id);if(t!==token)return;if(local){const v=document.createElement('video');v.controls=true;v.playsInline=true;v.setAttribute('playsinline','');v.preload='auto';v.style='width:100%;height:100%;object-fit:contain';v.poster='world/assets/church/sanctuary.webp';localURL=URL.createObjectURL(local);v.src=localURL;v.muted=!preferences.sound;localVideo=v;$('screen').replaceChildren(v);v.onended=()=>{if(t===token)onEnd();};v.onerror=()=>status('This saved clip cannot play. Use the story or song option below.');v.play().catch(()=>status('Tap Play on the video.'));return;}status('Loading our video inside church…');$('play-media').disabled=true;
 try{await loadYT();if(t!==token)return;const holder=document.createElement('div');holder.id='youtube-player';$('screen').replaceChildren(holder);
 let ended=false;const finish=()=>{if(ended||t!==token)return;ended=true;onEnd();};
 player=new YT.Player('youtube-player',{host:'https://www.youtube-nocookie.com',videoId:media.id,playerVars:{autoplay:1,playsinline:1,rel:0,controls:1,fs:1,start:media.start,end:media.end,origin:location.origin},events:{onReady:e=>{if(t!==token)return;const frame=e.target.getIframe();frame.setAttribute('title',media.label||media.title);frame.setAttribute('referrerpolicy','strict-origin-when-cross-origin');frame.setAttribute('allow','autoplay; encrypted-media; fullscreen; picture-in-picture');if(!preferences.sound)e.target.mute();e.target.playVideo();status('Tap the video’s play button if needed.');},onAutoplayBlocked:()=>status('Tap Play on the video to begin.'),onStateChange:e=>{if(t!==token)return;if(e.data===1)status('Listening ears. Stay seated beside Mommy.');if(e.data===0)finish();},onError:()=>{if(t!==token)return;status('This video could not play here. Use the option below to keep learning.');$('fallback').focus();}}});
 const limit=setInterval(()=>{if(t!==token)return;if(!paused&&player?.getCurrentTime?.()>=media.end-.2)finish();},200);timers.add(limit);
 }catch{if(t!==token)return;status('YouTube is unavailable here. Choose the option below.');$('play-media').disabled=false;$('play-media').textContent='Try video again';}
}
function song(which){const s=SONGS[which],target=step+1;mediaShell(s.title,'Sing together • voices only','Play our song');$('media-extra').innerHTML=`<div class="lyrics">${s.lyrics.map(l=>`<p>${esc(l)}</p>`).join('')}</div>`;$('fallback').textContent='Sing with Mommy';$('fallback').onclick=()=>singTogether(which);$('finished').onclick=()=>go(target);$('play-media').onclick=()=>playVideo({...s,slot:'song-'+which},()=>go(target),()=>singTogether(which));setRepeat(()=>go(step));$('play-media').click();}
async function singTogether(which){stop();const t=token,s=SONGS[which],target=step+1;stage.innerHTML=`<section class="panel center"><span class="eyebrow">Our voices are the music</span><h2>${esc(s.title)}</h2><div class="song-light" aria-hidden="true"></div><div class="lyrics">${s.lyrics.map(l=>`<p>${esc(l)}</p>`).join('')}</div><p>Sing these words together with Mommy.</p><button id="song-done" class="primary">We sang it!</button></section>`;$('song-done').onclick=()=>go(target);setRepeat(()=>singTogether(which));await speak('Let us sing together with Mommy. We use only our voices, with no instruments.',t);}
async function prayer(closing){const t=token,text=closing?CLOSING_PRAYER:OPENING_PRAYER;stage.innerHTML=`<section class="panel center"><span class="eyebrow">${closing?'Our closing prayer':'Our first prayer'}</span><h2>Let’s talk to God.</h2><div class="prayer-cues"><div><b>1</b>Bow your head</div><div><b>2</b>Close your eyes</div><div><b>3</b>Fold your hands</div></div><p class="prayer">${esc(text).replaceAll('. ','.\n')}</p><p class="small">Listen or say the words with me.</p></section>`;
 await recording(AUDIO.prayers,closing?25.68:0,closing?47.2:22.85,(closing?'Let us pray before we go. Bow your heads, close your eyes, and fold your hands. ':PRAYER_PROMPT+' ')+text,t);if(t!==token)return;await wait(1600,t);if(t===token)go(step+1);
}
async function lessonStart(){const t=token;if(preferences.local){await story(0);return;}mediaShell(lesson.title,`${Math.floor(lesson.video.seconds/60)}:${String(lesson.video.seconds%60).padStart(2,'0')} • ${lesson.reference}`,'Watch our Bible story');$('media-extra').innerHTML=`<p class="lyrics">${esc(lesson.intro)}</p>`;$('fallback').textContent='Read the story to us';$('fallback').onclick=()=>{stop();story(0);};$('finished').onclick=()=>go(4);let launched=false;$('play-media').onclick=()=>{if(launched)return;launched=true;window.speechSynthesis?.cancel();playVideo(lesson.video,()=>go(4),()=>story(0));};setRepeat(()=>go(3));await speak(lesson.intro,t);if(t===token&&!launched)$('play-media').click();}
async function story(index){const t=token, [title,text]=lesson.story[index];stage.innerHTML=`<section class="story-page"><span class="eyebrow">${esc(lesson.title)} • ${index+1} of ${lesson.story.length}</span><h2>${esc(title)}</h2><p>${esc(text)}</p><div><button id="story-next" class="primary">${index<lesson.story.length-1?'Next page':'Three little questions'}</button></div></section>`;$('story-next').onclick=()=>{stop();if(index<lesson.story.length-1)story(index+1);else go(4);};setRepeat(()=>{stop();story(index);});await speak(text,t);if(t!==token)return;await wait(2500,t);if(t===token)$('story-next').click();}
async function quiz(index){const t=token,q=lesson.quiz[index];let selected=-1,revealed=false;stage.innerHTML=`<section class="panel center"><span class="eyebrow">${esc(lesson.short)} • Question ${index+1} of 3</span><h2>${esc(q.q)}</h2><div class="answers">${q.choices.map((choice,i)=>`<button class="answer" data-answer="${i}"><b>${'ABC'[i]}</b><span>${esc(choice)}</span></button>`).join('')}</div><div class="countdown" id="countdown">Listen to all three choices.</div><p id="celebrate"></p><button id="question-next" class="primary" hidden>${index<2?'Next question':'Let’s sing again'}</button></section>`;
 for(const b of stage.querySelectorAll('[data-answer]'))b.onclick=()=>{if(revealed)return;selected=+b.dataset.answer;stage.querySelectorAll('.answer').forEach(x=>x.classList.toggle('selected',x===b));};
 $('question-next').onclick=()=>{stop();if(index<2)quiz(index+1);else go(5);};setRepeat(()=>{stop();quiz(index);});
 await speak(`${q.q} ${q.choices.map((c,i)=>`${'ABC'[i]}. ${c}.`).join(' ')} What do you think?`,t);if(t!==token)return;
 for(let s=5;s>0;s--){$('countdown').textContent=`Your turn! ${s}`;await wait(1000,t);if(t!==token)return;}
 revealed=true;$('countdown').textContent='Let’s find out!';for(const b of stage.querySelectorAll('[data-answer]')){b.disabled=true;b.classList.toggle('correct',+b.dataset.answer===q.answer);}
 $('celebrate').textContent=selected===q.answer?'You got it! Wonderful listening!':'We are learning together!';await speak(q.reply+' Wonderful listening!',t);if(t!==token)return;$('question-next').hidden=false;await wait(3000,t);if(t===token)$('question-next').click();
}
async function dismiss(){const t=token;stage.innerHTML=`<div class="welcome"><section class="panel"><span class="eyebrow">We learned together</span><h1>See you next time!</h1><p>Today we learned about ${esc(lesson.short)}.</p><div class="manners"><span>We listened</span><span>We sang</span><span>We prayed</span></div><p>Walk with Mommy. Now we can greet our church friends.</p><button id="another" class="primary">Another church visit</button></section></div>`;$('another').onclick=()=>{selectLesson();renderWelcome();};setRepeat(()=>go(7));await recording(AUDIO.prayers,50.03,58.54,DISMISSAL,t);if(t===token){chatter.volume=.16;ambience();status('Church is over. Use walking feet and stay with Mommy.');}}
function pause(){if(paused)return;paused=true;document.body.classList.add('paused');window.speechSynthesis?.pause();recorded.pause();chatter.pause();localVideo?.pause();player?.pauseVideo?.();$('break').showModal();}
function resume(){if(!paused)return;paused=false;document.body.classList.remove('paused');$('break').close();if(currentSpeech)speechSynthesis.resume();if(currentAudio&&preferences.sound)recorded.play().catch(()=>{});if(player)player.playVideo?.();localVideo?.play().catch(()=>{});if(step===0||step===7)ambience();}
$('pause').onclick=pause;$('resume').onclick=resume;$('break').addEventListener('cancel',e=>{e.preventDefault();resume();});
$('repeat').onclick=()=>repeatAction?.();$('sound').onclick=()=>setSound(!preferences.sound);
$('manners').onclick=()=>{pause();$('break').querySelector('p').textContent='Sit beside Mommy. Feet stay off the seats. Use a quiet voice so others can hear. When you need help or a break, tell Mommy quietly.';};
$('settings').onclick=()=>{if(step>0&&step<7&&!paused){pause();$('break').close();}$('parent').showModal();};$('parent').addEventListener('close',()=>{if(paused)resume();});
$('next-section').onclick=()=>{$('parent').close();go(Math.min(7,step+1));};$('restart').onclick=()=>{$('parent').close();selectLesson();renderWelcome();};$('choose').onclick=()=>{selectLesson($('lesson-choice').value);$('parent').close();renderWelcome();};
$('local-mode').checked=preferences.local;$('local-mode').onchange=e=>{preferences.local=e.target.checked;put(PREFS,preferences);};
$('leave').onclick=()=>{stop();if(window.parent!==window){window.parent.postMessage({channel:'jhw-church',type:'exit'},location.origin);}else location.href='./index.html';};
for(const l of LESSONS){const o=document.createElement('option');o.value=l.id;o.textContent=l.title;$('lesson-choice').append(o);}
$('sources').innerHTML=[...LESSONS.map(l=>({...l.video,title:l.title})),...Object.values(SONGS)].map(v=>`<p><strong>${esc(v.title)}</strong><br><a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/watch?v=${v.id}">${esc(v.label)}</a>${v.start?` · story segment ${Math.floor(v.start/60)}:${String(v.start%60).padStart(2,'0')}–${Math.floor(v.end/60)}:${String(v.end%60).padStart(2,'0')}`:''}</p>`).join('');
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(step>0&&step<7)pause();else{chatter.pause();recorded.pause();window.speechSynthesis?.cancel();}}});window.addEventListener('pagehide',stop);window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;if(e.data?.channel==='jhw-church'&&e.data.type==='stop')stop();});
selectLesson();setSound(preferences.sound);renderWelcome();

for(const [id,title] of [...LESSONS.map(l=>[l.id,l.title]),['song-opening','Yes, Jesus Loves Me'],['song-closing','This Little Light of Mine']]){const o=document.createElement('option');o.value=id;o.textContent=title;$('media-slot').append(o);}
async function mediaInfo(){const file=await readMedia($('media-slot').value);$('media-status').textContent=file?'Saved on this device: '+file.name:'No clip saved for this part yet.';}
$('media-slot').onchange=mediaInfo;$('media-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;const slot=$('media-slot').value;try{await checkMedia(file,slot.startsWith('song-')?90:300);await saveMedia(slot,file);await mediaInfo();}catch(err){$('media-status').textContent=err.message;}e.target.value='';};$('remove-media').onclick=async()=>{try{await removeMedia($('media-slot').value);await mediaInfo();}catch{$('media-status').textContent='Could not remove this clip.';}};mediaInfo();
