// Small synthesized arcade soundtrack. No downloads or microphone access.
export class RaceAudio {
 constructor(){this.enabled=true;this.started=false;}
 async unlock(){try{if(!this.ctx){const Audio=globalThis.AudioContext||globalThis.webkitAudioContext;if(!Audio)return;this.ctx=new Audio();const c=this.ctx;this.master=c.createGain();this.master.gain.value=this.enabled?.24:0;this.master.connect(c.destination);
  this.motor=c.createOscillator();this.motor.type='sawtooth';this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=280;this.motorGain=c.createGain();this.motorGain.gain.value=0;this.motor.connect(this.filter).connect(this.motorGain).connect(this.master);this.motor.start();
  const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;this.noise=c.createBufferSource();this.noise.buffer=buffer;this.noise.loop=true;this.skidFilter=c.createBiquadFilter();this.skidFilter.type='bandpass';this.skidFilter.frequency.value=1300;this.skidFilter.Q.value=.7;this.skid=c.createGain();this.skid.gain.value=0;this.noise.connect(this.skidFilter).connect(this.skid).connect(this.master);this.noise.start();this.noiseBuffer=buffer;}
  await this.ctx.resume();}catch{/* Audio can remain off when a device disallows it. */}}
 setEnabled(value){this.enabled=!!value;if(this.ctx)this.master.gain.setTargetAtTime(this.enabled?.24:0,this.ctx.currentTime,.06);}
 tone(freq,duration=.15,delay=0,volume=.3){if(!this.ctx||!this.enabled)return;const c=this.ctx,o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(this.master);o.start(t);o.stop(t+duration+.02);}
 engineStart(){this.tone(100,.25,0,.2);this.tone(140,.3,.1,.18);}
 event(e){if(e.type==='count')this.tone(440,.13);if(e.type==='go'){this.tone(880,.35);this.haptic(35);}if(e.type==='lap'){this.tone(660,.18);this.tone(880,.23,.13);}if(e.type==='position'&&e.better){this.tone(730,.1,0,.14);this.tone(980,.12,.08,.14);}if(e.type==='finish'){[523,659,784,1047].forEach((f,i)=>this.tone(f,.35,i*.15));this.haptic([40,70,40]);}if(e.type==='crash'){if(this.ctx&&this.enabled){const c=this.ctx,n=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();n.buffer=this.noiseBuffer;f.type='lowpass';f.frequency.value=350;g.gain.setValueAtTime(.6,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);n.connect(f).connect(g).connect(this.master);n.start();n.stop(c.currentTime+.2);}this.haptic(25);}}
 haptic(pattern){try{navigator.vibrate?.(pattern);}catch{}}
 update(player,active){if(!this.ctx)return;const t=this.ctx.currentTime,speed=player.v/player.car.max,rpm=38+speed*120+(speed*4%1)*23;this.motor.frequency.setTargetAtTime(rpm,t,.1);this.filter.frequency.setTargetAtTime(220+speed*700,t,.1);this.motorGain.gain.setTargetAtTime(active?.1+speed*.2:0,t,.1);const sliding=active&&player.v>25&&(Math.abs(player.steer)>.7||player.braking);this.skid.gain.setTargetAtTime(sliding?.09:0,t,.06);}
 quiet(){if(this.ctx){this.motorGain.gain.setTargetAtTime(0,this.ctx.currentTime,.05);this.skid.gain.setTargetAtTime(0,this.ctx.currentTime,.05);}}
}
