import {CreativityStudio} from './studio.mjs?v=1';
import {prepareIllustratedSheets} from './illustrated.mjs?v=studio-1';
export {prepareIllustratedSheets};
import {W,H,PALETTE,SHEETS,BOOK_PAGES,STAMPS,drawSheet,drawMotif} from './catalog.mjs?v=studio-2';
import {DrawingEngine} from './engine.mjs?v=studio-2';
import {newDocument} from './document.mjs?v=studio-1';
import {PRACTICES,WORDS,SIGHT,SHAPES,practiceLabel} from './practice.mjs?v=studio-1';
import {ArtworkStore,saveToRoom,readFromRoom} from './gallery.mjs?v=studio-1';
const ICONS={crayon:'M7 30V9L12 2L17 9V30ZM7 23H17M7 9H17',marker:'M7 30V13H18V30ZM9 13V7L16 3V13',brush:'M9 19L19 2L23 4L15 21M9 19Q0 20 4 31Q16 30 15 21Z',pencil:'M4 30L7 20L23 3L28 8L12 25ZM7 20L12 25',eraser:'M2 23L18 5Q20 3 22 5L30 13Q32 15 30 17L14 31H9ZM12 13L23 24',fill:'M2 18L16 4L29 17L16 30ZM16 4V1M2 18H29M29 21Q36 30 29 31Q23 30 29 21',stamp:'M10 17V9Q10 0 17 0Q24 0 24 9V17L31 24V30H3V24Z'};
function button(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.onclick=fn;return b;}
function paintPreview(canvas,doc,name){const tmp=document.createElement('canvas');const engine=new DrawingEngine(tmp,{name});engine.load(doc);canvas.width=240;canvas.height=160;canvas.getContext('2d').drawImage(tmp,0,0,240,160);engine.dispose();}
export class CreativityCenter{
 constructor({parent,room,sound,player,onClose,onSoundChange}){this.room=room;this.sound=sound;this.player=player;this.onClose=onClose;this.onSoundChange=onSoundChange;this.store=new ArtworkStore();this.savedId=null;this.dirty=false;this.saving=false;this.closed=false;this.timer=null;this.galleryToken=0;
 this.root=document.createElement('section');this.root.id='creativity-center';this.root.className=player.mode==='toddler'?'art toddler-art':'art';this.root.setAttribute('aria-label','Coloring and Creativity Center');
 this.root.innerHTML=`<header class="art-header"><button data-action="room">Art room</button><button data-action="back">Exit center</button><button data-action="coloring">Coloring book</button><button data-action="whiteboard">Whiteboard</button><button data-action="gallery">My gallery</button><button data-action="save" class="art-save">Save picture</button><button data-action="more">More</button></header><nav class="art-tools" aria-label="Drawing tools"></nav><div class="art-workspace"><div class="art-page-heading"><button data-action="choose">Choose a page</button><span id="art-title" aria-label="Swipe this page tab to turn coloring pages"></span><button data-action="listen" aria-label="Hear the activity">Listen</button><button data-action="previous" aria-label="Previous page">Previous</button><button data-action="next" aria-label="Next page">Next</button></div><div class="art-stage"><canvas id="art-drawing" aria-label="Touch drawing board" tabindex="0"></canvas><div class="art-celebration" aria-hidden="true"></div></div><div class="art-status"><span role="status" id="art-status">Pick a color and draw.</span><progress id="art-progress" value="0" max="100" aria-label="Tracing progress" hidden></progress></div></div><nav class="art-palette" aria-label="Color palette"></nav><dialog class="art-picker"><form method="dialog"><button class="art-close">Close</button></form><h2></h2><div class="art-picker-body"></div></dialog>`;
 parent.append(this.root);this.canvas=this.root.querySelector('#art-drawing');this.status=this.root.querySelector('#art-status');this.dialog=this.root.querySelector('dialog');this.picker=this.root.querySelector('.art-picker-body');this.toolTray=this.root.querySelector('.art-tools');this.palette=this.root.querySelector('.art-palette');
 this.engine=new DrawingEngine(this.canvas,{name:player.name,mode:player.mode,feedback:(m,k)=>this.feedback(m,k),changed:()=>this.changed()});this.engine.onProgress=v=>{const p=this.root.querySelector('progress');p.value=Math.round(v*100);p.hidden=!this.engine.coverage?.targets.size;};
 for(const tool of Object.keys(ICONS)){const b=button(tool==='fill'?'Bucket':tool==='brush'?'Paintbrush':tool[0].toUpperCase()+tool.slice(1),()=>{this.sound.unlock();this.engine.tool=tool;this.updateTools();if(tool==='stamp')this.chooseStamps();});b.dataset.tool=tool;b.setAttribute('aria-label',tool==='fill'?'Fill bucket':tool);b.insertAdjacentHTML('afterbegin',`<svg viewBox="0 0 36 36" aria-hidden="true"><path d="${ICONS[tool]}"/></svg>`);this.toolTray.append(b);}
 this.undo=button('Undo',()=>{this.engine.undo();this.updateTools();});this.redo=button('Redo',()=>{this.engine.redo();this.updateTools();});this.insideButton=button('Stay inside',()=>{this.engine.inside=!this.engine.inside;this.updateTools();this.feedback(this.engine.inside?'Crayons stay inside the shape you start in.':'Free coloring. Draw anywhere.','notice');});this.toolTray.append(this.undo,this.redo,button('Size',()=>this.chooseSize()),this.insideButton);
 for(const [name,color]of PALETTE){const b=button('',()=>{this.sound.unlock();this.engine.color=color;this.updateTools();this.sound.say(name,true);});b.title=name;b.setAttribute('aria-label',name);b.dataset.color=color;b.style.setProperty('--paint',color==='rainbow'?'linear-gradient(135deg,#ed3348,#ffdc32,#23ad66,#248ae8,#8c4ed6,#f476b8)':color);this.palette.append(b);}
 const actions={room:()=>this.returnToRoom(),back:()=>this.close(),coloring:()=>this.chooseSheets(),whiteboard:()=>this.openWhiteboard(),gallery:()=>this.gallery(),save:()=>this.save(),more:()=>this.more(),choose:()=>this.engine.document.mode==='coloring'?this.chooseSheets():this.choosePractice(),listen:()=>{this.sound.unlock();this.sound.say(this.label(),true);},previous:()=>this.previous(),next:()=>this.next()};for(const b of this.root.querySelectorAll('[data-action]'))b.onclick=actions[b.dataset.action];
 const pageTab=this.root.querySelector('#art-title');pageTab.onpointerdown=e=>{if(this.engine.document.mode!=='coloring')return;this.pageSwipe={x:e.clientX,y:e.clientY,id:e.pointerId};pageTab.setPointerCapture(e.pointerId);};pageTab.onpointerup=e=>{const s=this.pageSwipe;this.pageSwipe=null;if(!s||s.id!==e.pointerId)return;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*2)dx<0?this.next():this.previous();};
 this.observer=new ResizeObserver(()=>this.fit());this.observer.observe(this.root.querySelector('.art-stage'));this.updateTools();this.loadDraft();this.root.dataset.view='room';this.studio=new CreativityStudio({parent:this.root,player,sound,onStation:id=>this.enterStation(id),onExit:()=>this.close()});this.studio.ready.then(()=>this.refreshGalleryWall());
 }
 async refreshGalleryWall(){try{if(this.closed||!this.studio.renderer)return;const {pictures}=await this.room.request('art-list',{}),canvases=[];for(const picture of pictures.slice(0,2)){const row=await readFromRoom(this.room,picture.id);if(this.closed)return;const c=document.createElement('canvas');paintPreview(c,row.document,this.player.name);canvases.push(c);}this.studio.setPictures(canvases);}catch{}}
 async enterStation(id){if(this.closed)return;this.studio.pause();this.root.dataset.view='desk';this.fit();if(id==='coloring')this.chooseSheets();else if(id==='whiteboard')this.openWhiteboard();else if(id==='gallery')this.gallery();}
 async returnToRoom(){if(this.saving)return;this.engine.end();await this.persistDraft();this.dialog.close();this.root.dataset.view='room';this.studio.resume();}
 async loadDraft(){try{const d=await this.store.draft(this.player.profile);if(this.closed||this.dirty)return;if(d){this.engine.load(d.document);this.feedback('Your last drawing is ready.','notice');}else this.engine.load(newDocument('whiteboard'));this.updatePage();}catch{this.feedback('Draw freely. Download a copy if this browser cannot save.','notice');this.updatePage();}}
 fit(){if(this.root.dataset.view==='room')return;const r=this.root.querySelector('.art-stage').getBoundingClientRect(),s=Math.min((r.width-20)/W,(r.height-20)/H);this.canvas.style.width=Math.max(1,W*s)+'px';this.canvas.style.height=Math.max(1,H*s)+'px';}
 label(){const d=this.engine.document;return d.mode==='coloring'?SHEETS.find(p=>p.id===d.sheet)?.title:practiceLabel(d.practice,this.player.name);}
 updatePage(){const d=this.engine.document;this.root.querySelector('[data-action=previous]').hidden=d.mode!=='coloring';this.insideButton.hidden=d.mode!=='coloring';this.root.querySelector('#art-title').textContent=this.label();this.root.querySelector('[data-action="choose"]').textContent=d.mode==='coloring'?'Pages':'Practice';this.root.querySelector('[data-action="coloring"]').setAttribute('aria-pressed',String(d.mode==='coloring'));this.root.querySelector('[data-action="whiteboard"]').setAttribute('aria-pressed',String(d.mode==='whiteboard'));this.updateTools();this.configureMatching();this.fit();}
 updateTools(){this.insideButton?.setAttribute('aria-pressed',String(this.engine.inside));for(const b of this.toolTray.querySelectorAll('[data-tool]'))b.setAttribute('aria-pressed',String(this.engine.tool===b.dataset.tool));for(const b of this.palette.children)b.setAttribute('aria-pressed',String(this.engine.color===b.dataset.color));this.undo.disabled=!this.engine.history.document.ops.length;this.redo.disabled=!this.engine.history.redoOps.length;}
 changed(){if(!this.engine)return;this.dirty=true;this.updateTools();clearTimeout(this.timer);this.timer=setTimeout(()=>this.persistDraft(),650);}
 draftKey(doc){return this.player.profile+'~'+doc.mode+'~'+(doc.mode==='coloring'?doc.sheet:doc.practice.id+'~'+doc.practice.value);}
 async persistDraft(){if(!this.engine)return;const doc=this.engine.document;try{await this.store.draft(this.draftKey(doc),doc);await this.store.draft(this.player.profile,doc);}catch{if(!this.closed)this.feedback('Drawing works, but draft storage is unavailable. Use More → Download PNG to keep it.','notice');}}
 feedback(text,kind){this.status.textContent=text;if(kind==='celebrate'){this.sound.tone(720,.16);this.sound.say(text,true);const tray=this.root.querySelector('.art-celebration');tray.replaceChildren();for(let i=0;i<9;i++){const c=document.createElement('canvas');c.width=c.height=72;drawMotif(c.getContext('2d'),'star',PALETTE[i%7][1]);c.style.left=(10+i*9)+'%';c.style.animationDelay=i*.035+'s';tray.append(c);}setTimeout(()=>tray.replaceChildren(),2200);} }
 showPicker(title){this.galleryToken++;this.dialog.querySelector('h2').textContent=title;this.picker.replaceChildren();if(!this.dialog.open)this.dialog.showModal();}
 async chooseDocument(doc){if(this.saving){this.feedback("Your picture is saving. Please wait a moment.","notice");return;}if(this.changing)return;this.changing=true;this.engine.end();await this.persistDraft();let draft;try{draft=await this.store.draft(this.draftKey(doc));}catch{}if(this.closed)return;this.savedId=null;this.engine.load(draft?.document||doc);this.changing=false;this.dialog.close();this.updatePage();this.sound.unlock();this.sound.say(this.label(),true);if(doc.mode==='coloring'){this.engine.tool='fill';this.updateTools();this.feedback('Tap a space to color it. Choose a crayon to draw. Swipe the page tab to turn pages.','notice');}else this.feedback('Pick a color and draw on your board.','notice');}
 chooseSheets(){this.showPicker('Choose your coloring adventure');const cover=document.createElement('p');cover.className='art-book-cover';cover.textContent='Jace & Halli’s coloring adventures · '+BOOK_PAGES.length+' pages';this.picker.append(cover);for(const page of BOOK_PAGES){const b=button(page.title,()=>this.chooseDocument(newDocument('coloring',page.id)),'art-page-choice');const preview=document.createElement('canvas');preview.width=240;preview.height=160;const c=preview.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,240,160);c.scale(.25,.25);drawSheet(c,page.id);b.prepend(preview);this.picker.append(b);}}
 openWhiteboard(){if(this.saving)return;this.engine.tool='crayon';this.updateTools();this.chooseDocument(newDocument('whiteboard'));this.sound.say('Your whiteboard. Draw anything you like. Tap Practice to try a game.',true);}
 choosePractice(){this.showPicker('Whiteboard play & practice');for(const p of PRACTICES){this.picker.append(button(p.title,()=>this.practiceValues(p.id),'art-practice-choice'));}}
 practiceValues(id){if(id==='blank'){this.chooseDocument(newDocument());return;}let values=id==='upper'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''):id==='lower'?'abcdefghijklmnopqrstuvwxyz'.split(''):id==='number'?Array.from({length:21},(_,i)=>String(i)):id==='shape'||id==='match'?SHAPES:id==='color'?PALETTE.map(p=>p[0]):id==='word'?WORDS:id==='sight'?SIGHT:id==='lines'?['0','1','2','3']:[this.player.name];this.showPicker(PRACTICES.find(p=>p.id===id).title);for(const value of values){const b=button(id==='lines'?['Straight path','Wave path','Zigzag path','Winding path'][Number(value)]:value,()=>this.chooseDocument(newDocument('whiteboard','',{id,value})),'art-practice-choice');if(id==='word'){const c=document.createElement('canvas');c.width=c.height=90;const motif={eat:'apple',more:'ball',up:'up',down:'down',yes:'yes',no:'no',please:'hand','thank you':'heart'}[value]||value;c.getContext('2d').scale(.9,.9);drawMotif(c.getContext('2d'),motif,'white');b.prepend(c);}this.picker.append(b);}}
 chooseSize(){this.showPicker('How big is your brush?');for(const [name,size]of [['Little',8],['Medium',18],['Big',35],['Extra big',65]]){const b=button(name,()=>{this.engine.size=size;this.dialog.close();this.feedback(name+' brush.','notice');},'art-size-choice');const dot=document.createElement('i');dot.style.width=dot.style.height=size+'px';b.prepend(dot);this.picker.append(b);}}
 chooseStamps(){this.showPicker('Pick a stamp, then tap your picture');for(const stamp of STAMPS){const b=button(stamp,()=>{this.engine.stamp=stamp;this.dialog.close();this.feedback('Tap to stamp a '+stamp+'.','notice');},'art-stamp-choice');const c=document.createElement('canvas');c.width=c.height=100;drawMotif(c.getContext('2d'),stamp,'#ffdc32');b.prepend(c);this.picker.append(b);}}
 previous(){const d=this.engine.document;if(d.mode==='coloring'){const i=BOOK_PAGES.findIndex(p=>p.id===d.sheet);this.turnPage(newDocument('coloring',BOOK_PAGES[(i+BOOK_PAGES.length-1)%BOOK_PAGES.length].id));}}
 turnPage(doc){this.root.classList.add('turning-page');this.chooseDocument(doc);setTimeout(()=>this.root.classList.remove('turning-page'),300);}
 next(){const d=this.engine.document;if(d.mode==='coloring'){const i=BOOK_PAGES.findIndex(p=>p.id===d.sheet);this.turnPage(newDocument('coloring',BOOK_PAGES[(i+1)%BOOK_PAGES.length].id));return;}const p=d.practice;const values=p.id==='upper'?'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''):p.id==='lower'?'abcdefghijklmnopqrstuvwxyz'.split(''):p.id==='number'?Array.from({length:21},(_,i)=>String(i)):p.id==='shape'||p.id==='match'?SHAPES:p.id==='word'?WORDS:p.id==='sight'?SIGHT:p.id==='color'?PALETTE.map(p=>p[0]):p.id==='lines'?['0','1','2','3']:null;if(values)this.chooseDocument(newDocument('whiteboard','',{id:p.id,value:values[(values.indexOf(p.value)+1)%values.length]}));else this.choosePractice();}
 configureMatching(){this.engine.overlay=null;this.engine.tapActivity=null;const p=this.engine.document.practice;if(p?.id!=='match'){this.engine.present();return;}const others=SHAPES.filter(s=>s!==p.value);this.matches=[p.value,others[0],others[1]].sort(()=>Math.random()-.5);const drawShape=(c,s,x,y,size,fill)=>{c.save();c.translate(x,y);c.scale(size/100,size/100);c.strokeStyle='#23495e';c.lineWidth=3;c.fillStyle=fill;if(s==='circle'){c.beginPath();c.arc(50,50,43,0,Math.PI*2);c.fill();c.stroke();}else if(s==='square'){c.fillRect(7,7,86,86);c.strokeRect(7,7,86,86);}else if(s==='triangle'){const path=new Path2D('M50 6L96 94H4Z');c.fill(path);c.stroke(path);}else drawMotif(c,s,fill);c.restore();};this.engine.overlay=c=>{c.fillStyle='#23495e';c.font='bold 32px sans-serif';c.textAlign='center';c.fillText('Find the '+p.value,480,68);drawShape(c,p.value,410,110,140,'#f3f7fc');this.matches.forEach((s,i)=>drawShape(c,s,170+i*245,385,135,['#ffdc32','#f476b8','#23ad66'][i]));};this.engine.tapActivity=point=>{if(point[1]<360||point[1]>535)return false;const i=Math.floor((point[0]-147)/245);if(i<0||i>2)return false;if(this.matches[i]===p.value){this.feedback('Great job! You found the '+p.value+'.','celebrate');this.status.textContent='You did it! Tap Next for another shape.';}else{this.sound.say('Try again. Find the '+p.value+'.',true);this.feedback('Try another shape. You can do it!','notice');}return true;};this.engine.present();}
 async save(){if(this.saving)return;this.engine.end();this.saving=true;const b=this.root.querySelector('[data-action="save"]');b.disabled=true;this.feedback('Saving your picture…','notice');const id=this.savedId||crypto.randomUUID(),document=this.engine.document,title=this.label();try{await saveToRoom(this.room,id,title,document);this.savedId=id;this.dirty=JSON.stringify(this.engine.document)!==JSON.stringify(document);try{await this.store.put(this.player.profile,{id,title,document});}catch{}this.feedback('Saved in '+this.player.name+'’s gallery!','celebrate');this.refreshGalleryWall();}catch(e){this.feedback(e.message+' Your drawing stays here. Download a copy in More.','notice');}finally{this.saving=false;b.disabled=false;}}
 async gallery(){if(this.saving)return;this.engine.end();await this.persistDraft();if(this.closed)return;this.showPicker(this.player.name+'’s gallery');const token=this.galleryToken;const text=document.createElement('p');text.textContent='Opening your pictures…';this.picker.append(text);try{const {pictures}=await this.room.request('art-list',{});if(this.closed||token!==this.galleryToken)return;text.textContent=pictures.length?'Tap a picture to keep coloring. Saved on the family hosting device.':'Your gallery is waiting for your first picture. Tap Save picture after drawing.';for(const item of pictures){const b=button(item.title,async()=>{if(this.saving)return;b.disabled=true;try{const row=await readFromRoom(this.room,item.id);if(this.closed)return;this.engine.load(row.document);this.savedId=row.id;this.dialog.close();this.updatePage();this.feedback('Your saved picture is ready.','notice');}catch(e){this.feedback(e.message,'notice');}finally{b.disabled=false;}},'art-gallery-choice');const preview=document.createElement('canvas');preview.width=240;preview.height=160;b.prepend(preview);this.picker.append(b);if(pictures.indexOf(item)<8){const row=await readFromRoom(this.room,item.id);if(this.closed||token!==this.galleryToken)return;paintPreview(preview,row.document,this.player.name);}}}catch(e){if(token===this.galleryToken)text.textContent=e.message;}}
 more(){this.showPicker('Your art supplies');this.picker.append(button('Clear page',()=>{this.showPicker('Start fresh?');const p=document.createElement('p');p.textContent='You can Undo after clearing.';this.picker.append(p,button('Clear this page',()=>{this.engine.clear();this.dialog.close();this.feedback('A fresh page. Undo brings your drawing back.','notice');}),button('Keep drawing',()=>this.dialog.close()));}),button('Download PNG',()=>{this.engine.end();this.canvas.toBlob(blob=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=this.player.name+'-'+this.label().replace(/[^a-z0-9]/gi,'-')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);},'image/png');this.dialog.close();}),button(this.sound.enabled?'Sound off':'Sound on',()=>{this.sound.mute(!this.sound.enabled);this.onSoundChange?.(this.sound.enabled);this.dialog.close();this.feedback(this.sound.enabled?'Sound on.':'Sound off.','notice');}));}
 dispose(){this.studio?.dispose();this.engine.end();this.persistDraft();this.closed=true;clearTimeout(this.timer);this.galleryToken++;this.observer.disconnect();this.engine.dispose();this.dialog.close();this.root.remove();}
 async close(){if(this.saving){this.feedback('Your picture is saving. Please wait a moment.','notice');return;}this.engine.end();await this.persistDraft();this.dispose();this.onClose();}
}
