import {ILLUSTRATED} from './illustrated.mjs?v=studio-1';
// Physical room presentation. Drawing and room authority stay in their existing modules.
import {drawPortrait} from '../characters.mjs';
const THREE_URL='https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.min.js';
const STATIONS=[{id:'coloring',name:'Coloring table',point:[-3,1.1,-1.8],view:[-3,2,1.6]},{id:'whiteboard',name:'Whiteboard',point:[3.3,2.4,-4.77],view:[3.3,2,-1.2]},{id:'gallery',name:'My gallery',point:[-4.4,2.6,-4.73],view:[-4,2,-1.4]}];
export class CreativityStudio{
 constructor({parent,player,sound,onStation,onExit}){
  this.player=player;this.sound=sound;this.onStation=onStation;this.onExit=onExit;this.closed=false;this.moving=false;this.turn=0;this.yaw=0;this.pitch=0;this.targets=[];
  this.root=document.createElement('section');this.root.className='creativity-studio';this.root.setAttribute('aria-label','Creativity Center art room');
  this.root.innerHTML=`<canvas class="studio-view" aria-label="Look around the three dimensional art room"></canvas><header class="studio-header"><button class="studio-exit">Back to world</button><div><strong>Jace & Halli’s Creativity Center</strong><span>Color. Draw. Make something yours.</span></div><canvas width="120" height="150" aria-label="Your character"></canvas></header><div class="studio-stations"></div><div class="studio-message" role="status">Opening the art room…</div><footer class="studio-controls"><button class="studio-turn-left" aria-label="Turn left">Turn left</button><button class="studio-walk">Walk</button><button class="studio-turn-right" aria-label="Turn right">Turn right</button><span>Drag to look around. Tap a table or board to use it.</span></footer>`;
  parent.append(this.root);this.canvas=this.root.querySelector('.studio-view');this.status=this.root.querySelector('.studio-message');this.root.querySelector('header canvas').setAttribute('aria-label',player.name);drawPortrait(this.root.querySelector('header canvas'),player.profile);
  this.root.querySelector('.studio-exit').onclick=()=>onExit();
  for(const s of STATIONS){const b=document.createElement('button');b.textContent=s.name;b.dataset.station=s.id;b.onclick=()=>this.visit(s.id);this.root.querySelector('.studio-stations').append(b);}
  this.hold('.studio-walk',v=>this.moving=v);this.hold('.studio-turn-left',v=>this.turn=v?-1:0);this.hold('.studio-turn-right',v=>this.turn=v?1:0);
  this.canvas.onpointerdown=e=>{this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};this.canvas.setPointerCapture(e.pointerId);};
  this.canvas.onpointermove=e=>{if(this.drag?.id!==e.pointerId)return;this.yaw-=(e.clientX-this.drag.x)*.005;this.pitch=Math.max(-.5,Math.min(.4,this.pitch-(e.clientY-this.drag.y)*.003));this.drag.x=e.clientX;this.drag.y=e.clientY;};
  this.canvas.onpointerup=e=>{if(!this.drag)return;const d=this.drag;this.drag=null;if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<12&&this.ray){const r=this.canvas.getBoundingClientRect();this.ray.setFromCamera({x:(e.clientX-r.left)/r.width*2-1,y:1-(e.clientY-r.top)/r.height*2},this.camera);const hit=this.ray.intersectObjects(this.targets,true)[0];if(hit){let o=hit.object;while(o&&!o.userData.station)o=o.parent;if(o)this.visit(o.userData.station);}}};
  this.canvas.onpointercancel=()=>{this.drag=null;};this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(this.frame);this.contextLost=true;this.moving=false;this.status.textContent='The art room paused. Drawing is still available below.';this.showAccess();});
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(this.root);this.ready=this.prepare();
 }
 hold(selector,fn){const b=this.root.querySelector(selector);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);fn(true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>fn(false);}
 async prepare(){try{const T=await import(THREE_URL);if(this.closed)return;this.T=T;this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.scene=new T.Scene();this.scene.background=new T.Color('#a8d9ed');this.scene.fog=new T.Fog('#a8d9ed',20,65);this.camera=new T.PerspectiveCamera(58,1,.1,80);this.camera.position.set(0,2.6,6);this.ray=new T.Raycaster();this.makeRoom(T);this.resize();this.status.textContent='Welcome, '+this.player.name+'. Choose a place to create.';this.frame=0;this.resume();}catch(e){if(this.closed)return;this.status.textContent='This browser cannot show the 3D room. You can still use the coloring book and whiteboard.';this.root.dataset.graphics='unavailable';this.showAccess();}}
 showAccess(){this.root.classList.add('studio-access');this.root.querySelector('.studio-controls').hidden=true;}
 makeRoom(T){
  const mat=color=>new T.MeshStandardMaterial({color,roughness:.75});const cream=mat('#fff4de'),wood=mat('#cc9657'),blue=mat('#6caec2'),pink=mat('#ec9cb6'),yellow=mat('#f8cf67'),white=mat('#fffdf5'),green=mat('#8fc180');
  const add=(g,m,x,y,z,parent=this.scene)=>{const mesh=new T.Mesh(g,m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;};
  const round=(w,h,d,r=.12)=>{const s=new T.Shape(),x=-w/2,y=-h/2;r=Math.min(r,w/3,h/3,d/3);s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);const g=new T.ExtrudeGeometry(s,{depth:d-2*r,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:r,bevelThickness:r,curveSegments:8});g.translate(0,0,-d/2+r);return g;};
  const box=(w,h,d,m,x,y,z,parent)=>add(round(w,h,d),m,x,y,z,parent);
  const cyl=(r,h,m,x,y,z,parent)=>add(new T.CylinderGeometry(r,r,h,24),m,x,y,z,parent);
  const text=(value,w,h,m,x,y,z,parent=this.scene)=>{const c=document.createElement('canvas');c.width=768;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#fff9e9';ctx.fillRect(0,0,768,256);ctx.fillStyle='#24536c';ctx.font='bold 65px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(value,384,128,715);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;return add(new T.PlaneGeometry(w,h),new T.MeshStandardMaterial({map:texture,roughness:.9}),x,y,z,parent);};
  this.scene.add(new T.HemisphereLight('#fff7df','#92a891',2));const sun=new T.DirectionalLight('#fff2d5',3);sun.position.set(-6,9,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.5,far:35});sun.shadow.bias=-.001;this.scene.add(sun);
  const floor=document.createElement('canvas');floor.width=floor.height=512;const ctx=floor.getContext('2d');for(let y=0;y<512;y+=64){ctx.fillStyle=y%128?'#d6b283':'#e5c69f';ctx.fillRect(0,y,512,64);ctx.fillStyle='#b98d60';ctx.fillRect(0,y,512,2);for(let x=(y%128?100:0);x<512;x+=180)ctx.fillRect(x,y,2,64);ctx.strokeStyle='#c7a173';ctx.globalAlpha=.35;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(0,y+8+i*10);ctx.bezierCurveTo(140,y+14+i*9,310,y+4+i*10,512,y+10+i*9);ctx.stroke();}ctx.globalAlpha=1;}const ft=new T.CanvasTexture(floor);ft.wrapS=ft.wrapT=T.RepeatWrapping;ft.repeat.set(3,3);ft.colorSpace=T.SRGBColorSpace;box(14,.2,15,new T.MeshStandardMaterial({map:ft,roughness:.8}),0,-.12,0);
  box(5.7,5,.22,cream,-4.15,2.4,-5.4);box(5.7,5,.22,cream,4.15,2.4,-5.4);box(2.6,1.45,.22,cream,0,.65,-5.4);box(2.6,1.1,.22,cream,0,4.35,-5.4);box(.22,5,11,cream,-7,2.4,0);box(.22,5,11,cream,7,2.4,0);box(14,.18,.25,wood,0,.15,-5.2);box(.3,.18,11,wood,-6.8,.15,0);box(.3,.18,11,wood,6.8,.15,0);
  // A raised curved arch, wall moulding and inset window frames make this a room, not a backdrop.
  box(8,.48,.3,blue,0,4.3,-5.17);text('Jace & Halli’s Creativity Center',7.7,.42,null,0,4.3,-4.99);
  for(const x of [0]){box(.13,2.4,.17,wood,x-1.24,2.7,-5.12);box(.13,2.4,.17,wood,x+1.24,2.7,-5.12);box(2.6,.12,.17,wood,x,3.9,-5.12);box(.09,2.1,.2,white,x,2.7,-4.89);box(2.3,.09,.2,white,x,2.7,-4.89);box(2.85,.15,.45,white,x,1.52,-4.9);}
  // Coloring desk with real book, chairs, pencils, paper and paint cups.
  const table=new T.Group();table.userData.station='coloring';table.position.set(-3,0,-1.8);this.scene.add(table);this.targets.push(table);
  box(3.1,.2,2.1,wood,0,1.05,0,table);for(const x of [-1.25,1.25])for(const z of [-.8,.8])cyl(.1,1,wood,x,.5,z,table);
  box(1.1,.07,.85,blue,0,1.19,.12,table);const page=box(1,.03,.78,white,0,1.245,.12,table);const sheet=text('Our coloring book',.88,.25,null,0,1.29,.13,table);sheet.rotation.x=-Math.PI/2;if(ILLUSTRATED.has('truck-v2')){const cover=document.createElement('canvas');cover.width=512;cover.height=384;const cc=cover.getContext('2d');cc.fillStyle='#fff9e9';cc.fillRect(0,0,512,384);cc.drawImage(ILLUSTRATED.get('truck-v2'),18,45,476,317);cc.fillStyle='#24536c';cc.font='bold 26px sans-serif';cc.textAlign='center';cc.fillText('Our coloring adventures',256,32);sheet.material.map.dispose();const ct=new T.CanvasTexture(cover);ct.colorSpace=T.SRGBColorSpace;sheet.material.map=ct;sheet.material.needsUpdate=true;sheet.scale.y=2.7;}
  for(let i=0;i<6;i++){const m=mat(['#ed3348','#ff941c','#ffdc32','#23ad66','#248ae8','#8c4ed6'][i]);const pen=cyl(.038,.5,m,-1.05+i*.13,1.2,-.62,table);pen.rotation.z=Math.PI/2;}
  for(const [x,color]of [[1.07,'#f476b8'],[.75,'#248ae8']]){cyl(.15,.3,mat(color),x,1.27,-.6,table);for(let i=0;i<3;i++){const p=cyl(.025,.65,wood,x+(i-1)*.05,1.55,-.6,table);p.rotation.z=(i-1)*.15;}}
  for(const x of [-3.9,-2.1]){box(.8,.15,.8,pink,x,.58,.1);box(.8,.9,.12,pink,x,.95,.47);for(const dx of [-.28,.28])for(const z of [-.17,.38])cyl(.045,.55,wood,x+dx,.28,z);}
  text('COLOR & CREATE',2.6,.42,null,-3,1.57,-2.7);
  // The whiteboard and gallery are touch targets in world space.
  const board=new T.Group();board.userData.station='whiteboard';this.scene.add(board);this.targets.push(board);box(3.5,2.1,.25,blue,3.3,2.4,-4.95,board);box(3.18,1.81,.27,white,3.3,2.4,-4.77,board);box(3.6,.16,.6,wood,3.3,1.22,-4.65,board);text('Draw • Write • Play',2.6,.5,null,3.3,2.55,-4.6,board);for(let i=0;i<5;i++){const p=cyl(.055,.35,mat(['#ed3348','#23ad66','#248ae8','#8c4ed6','#f476b8'][i]),2.15+i*.25,1.34,-4.55,board);p.rotation.z=Math.PI/2;}
  const gallery=new T.Group();gallery.userData.station='gallery';this.scene.add(gallery);this.targets.push(gallery);text(this.player.name+'’s Gallery',2.8,.48,null,-3.6,3.7,-4.94,gallery);this.galleryPlanes=[];for(const x of [-4.4,-2.7]){box(1.45,1.2,.15,wood,x,2.6,-4.97,gallery);box(1.22,.97,.18,white,x,2.6,-4.85,gallery);this.galleryPlanes.push(text('Your art goes here',1.18,.9,null,x,2.6,-4.73,gallery));}
  // Rounded shelf, sketch books, plant foliage and soft circular play rug.
  box(1.7,1.5,.65,wood,5.65,.75,-2.8);for(const y of [.2,.8,1.4])box(1.7,.07,.75,white,5.65,y,-2.7);for(let i=0;i<8;i++)box(.13,.47,.44,mat(['#f476b8','#6caec2','#f8cf67'][i%3]),5.06+i*.15,1.1,-2.69);
  cyl(.38,.52,mat('#da916d'),-5.8,.26,-3.5);cyl(.035,1.45,green,-5.8,1,-3.5);for(let i=0;i<6;i++){const leaf=add(new T.SphereGeometry(.43,16,10),green,-5.8+Math.cos(i)*.35,1.5+i*.05,-3.5+Math.sin(i)*.3);leaf.scale.set(1,.5,1);}
  box(28,.12,25,green,0,-.25,-18);box(2.2,.07,20,mat('#ead9b2'),0,-.12,-17);for(const [x,z]of [[-3,-10],[4,-13],[-5,-18],[5,-22]]){cyl(.16,2.6,wood,x,1.05,z);for(let i=0;i<3;i++)add(new T.SphereGeometry(1.05,18,12),green,x+Math.cos(i*2)*.5,2.7+i*.3,z+Math.sin(i*2)*.5);}for(let x=-10;x<11;x+=.65){box(.1,1,.15,white,x,.45,-11);box(.65,.12,.13,white,x,.65,-11);}
  const rug=cyl(2,.035,mat('#b3dce1'),1.7,.014,1.3);rug.scale.z=.65;const inner=cyl(1.73,.04,mat('#f1db9f'),1.7,.018,1.3);inner.scale.z=.65;
  for(const [x,z]of [[-3.8,1.5],[4.5,2.4]]){box(.55,.12,.7,yellow,x,.16,z);box(.5,.1,.64,pink,x+.07,.27,z+.05);}
 }
 setPictures(canvases){if(!this.T||this.closed)return;canvases.slice(0,2).forEach((c,i)=>{const plane=this.galleryPlanes[i];if(!plane)return;plane.material.map?.dispose();const t=new this.T.CanvasTexture(c);t.colorSpace=this.T.SRGBColorSpace;plane.material.map=t;plane.material.needsUpdate=true;});}
 resize(){if(!this.renderer||this.closed)return;const r=this.root.getBoundingClientRect();this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();}
 visit(id){if(this.travel||this.closed)return;const s=STATIONS.find(s=>s.id===id);if(!s)return;this.sound.unlock();this.sound.say(s.name,true);if(!this.renderer||this.contextLost){this.onStation(id);return;}this.moving=false;this.travel={s,start:performance.now(),from:this.camera.position.clone()};this.status.textContent='Going to the '+s.name.toLowerCase()+'…';}
 resume(){if(this.closed)return;this.root.hidden=false;if(!this.renderer||this.contextLost)return;cancelAnimationFrame(this.frame);this.last=performance.now();this.loop(this.last);}
 pause(){cancelAnimationFrame(this.frame);this.moving=false;this.turn=0;this.root.hidden=true;}
 loop(t){if(this.closed||this.root.hidden)return;const T=this.T,dt=Math.min(.04,(t-this.last)/1000);this.last=t;if(this.travel){const {s,start,from}=this.travel,u=Math.min(1,(t-start)/850),v=u*u*(3-2*u);this.camera.position.lerpVectors(from,new T.Vector3(...s.view),v);this.camera.lookAt(...s.point);if(u===1){this.travel=null;this.pause();this.onStation(s.id);return;}}else{this.yaw-=this.turn*dt;this.camera.rotation.order='YXZ';this.camera.rotation.y=this.yaw;this.camera.rotation.x=this.pitch;if(this.moving){this.camera.position.x=Math.max(-6,Math.min(6,this.camera.position.x-Math.sin(this.yaw)*dt*2.1));this.camera.position.z=Math.max(-3.7,Math.min(6,this.camera.position.z-Math.cos(this.yaw)*dt*2.1));}this.camera.position.y=2.6;}
  for(const s of STATIONS){const p=new T.Vector3(...s.point).project(this.camera);const b=this.root.querySelector('[data-station="'+s.id+'"]');b.hidden=p.z>1||Math.abs(p.x)>1.2||Math.abs(p.y)>1.2;const r=this.root.getBoundingClientRect();b.style.left=(p.x+1)*r.width/2+'px';b.style.top=(1-p.y)*r.height/2+'px';}
  this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(v=>this.loop(v));
 }
 dispose(){this.closed=true;cancelAnimationFrame(this.frame);this.observer.disconnect();this.scene?.traverse(o=>{o.geometry?.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];for(const m of materials){m?.map?.dispose();m?.dispose();}});this.renderer?.dispose();this.root.remove();}
}
