export const COLORS=[['red','#d92e3d'],['orange','#f28420'],['yellow','#f6ce34'],['green','#43a567'],['blue','#318bdb'],['indigo','#514393'],['purple','#9b65c2'],['pink','#ec76b0'],['brown','#956340'],['black','#303744'],['white','#fff']].map(([name,hex])=>({id:name,name,hex}));
export const DAYS=[['Sunday','Church day. We listen, sing, and use our quiet voices.','church'],['Monday','A new school week begins. Let’s learn and play.','class'],['Tuesday','We practice, play, and try something new.','class'],['Wednesday','School today, and church is part of our family’s Wednesday.','church'],['Thursday','Library night! We choose a book and read together.','books'],['Friday','The weekend is almost here! We finish our school week.','play'],['Saturday','A weekend day for family time and play.','home']].map(([name,line,picture],i)=>({id:String(i),name,line,picture}));
export const LETTER_WORDS=['Apple','Banana','Cat','Dinosaur','Elephant','Fish','Guitar','Halli','Ice cream','Jace','Keke','Leaf','Moon','Nest','Orange','Pig','Quilt','Rabbit','Sun','Train','Unique','Van','Whale','Xylophone','Yarn','Zebra'];
export const LETTERS=LETTER_WORDS.map((word,i)=>({id:String.fromCharCode(65+i),name:String.fromCharCode(65+i),word}));
export const NUMBERS=Array.from({length:10},(_,i)=>({id:String(i),name:String(i)}));
export const SEASONS=[
 {id:'spring',name:'Spring',line:'Spring brings new leaves and flowers. Some days are rainy. A light jacket and rain boots help on wet days. Easter often comes in spring.',picture:0,clothes:'raincoat'},
 {id:'summer',name:'Summer',line:'Summer can be hot and sunny. We wear light clothes and a sun hat. We drink water, rest in the shade, and play outside. The Fourth of July is in summer.',picture:2,clothes:'shirt'},
 {id:'fall',name:'Fall',line:'Fall is also called autumn. Leaves may turn orange, red, and yellow. A cozy jacket helps on cool days. Halloween and Thanksgiving come in fall.',picture:3,clothes:'raincoat'},
 {id:'winter',name:'Winter',line:'Winter is the coldest season. We may see frost or snow. We wear a warm coat, hat, and mittens. Christmas comes near the start of winter.',picture:4,clothes:'raincoat'}
];
export const WEATHER=[{id:'sunny',name:'Sunny',line:'The sun is shining. Find some shade when you feel hot.',clothes:'shirt'},{id:'rainy',name:'Rainy',line:'Raindrops fall from clouds. Wear rain boots and a raincoat.',clothes:'raincoat'},{id:'cloudy',name:'Cloudy',line:'Clouds cover some of the sky. Look outside: is it warm or cool?',clothes:'shirt'},{id:'windy',name:'Windy',line:'Wind moves the leaves. Hold on to your hat!',clothes:'raincoat'},{id:'snowy',name:'Snowy',line:'Snowflakes fall when it is very cold. Put on a warm coat, hat, and mittens.',clothes:'raincoat'}];
export const HOLIDAYS=[['christmas','Christmas','Christmas is a time when many families celebrate the birth of Jesus. We can give, help, and spend time together.','church'],['easter','Easter','At Easter, we remember that Jesus is alive. We celebrate with our family.','church'],['thanksgiving','Thanksgiving','We say thank you for people who care for us. What are you thankful for?','home'],['halloween','Halloween','We can wear a fun costume. We stay close to our grown-up and say thank you.','play'],['july','Fourth of July','We celebrate our country. Fireworks are for grown-ups. We can watch safely with our family.','play'],['valentine','Valentine’s Day','We show kindness and tell our family that we love them.','home'],['birthday','Birthdays','A birthday celebrates someone growing! We can sing, share, and be kind.','home']].map(([id,name,line,picture])=>({id,name,line,picture}));
export const SHAPES=['circle','square','triangle','star','heart'];
export const HALLI_WORDS={body:[['head','Touch your head. Head.'],['eyes','Blink your eyes. Eyes.'],['nose','Point to your nose. Nose.'],['mouth','Open and close your mouth. Mouth.'],['hands','Clap your hands. Hands.'],['feet','Wiggle your feet. Feet.']],clothes:[['shirt','Shirt. A shirt goes on your body.'],['raincoat','Coat. A coat helps keep you warm.'],['shoes','Shoes. Shoes go on your feet.'],['hat','Hat. A hat goes on your head.']],family:[['mommy','Mommy. Say Mommy.'],['jace','Jace. Jace is your big brother.'],['halli','Halli. That’s you!'],['unique','Unique. Unique is your big sister.'],['daddy','Daddy. Say Daddy.']]};
export const SONGS=[{id:'wheels',name:'The Wheels on the Bus',verses:['The wheels on the bus go round and round, round and round, round and round. The wheels on the bus go round and round, all through the town.','The doors on the bus go open and shut, open and shut, open and shut. The doors on the bus go open and shut, all through the town.','The people on the bus go up and down, up and down, up and down. The people on the bus go up and down, all through the town.']},{id:'bridge',name:'London Bridge',verses:['London Bridge is falling down, falling down, falling down. London Bridge is falling down, my fair lady.','Build it up with wood and clay, wood and clay, wood and clay. Build it up with wood and clay, my fair lady.']},{id:'twinkle',name:'Twinkle, Twinkle',verses:['Twinkle, twinkle, little star, how I wonder what you are. Up above the world so high, like a diamond in the sky. Twinkle, twinkle, little star, how I wonder what you are.']}];
export const TOYS={dinosaur:0,baby:1,pan:2,apple:3,banana:4,dog:5,cat:6,toast:7,milk:8,soup:9,shirt:10,raincoat:11,duck:12,brick:13,pot:14,bear:15};
const p=(text,scene,people=[],toy=null)=>({text,scene,people,toy});
export const BOOKS={jace:[
 {id:'brother',title:'Jace, the Kind Big Brother',pages:[p('Jace is playing. Halli comes close. She wants to play too.',0,['jace','halli'],'brick'),p('Jace takes a deep breath. He finds a big block for Halli.',0,['jace','halli'],'brick'),p('Halli drops her block. Jace helps pick it up.',0,['halli','jace'],'brick'),p('“Your turn, Halli!” Jace waits with gentle hands.',0,['jace','halli'],'bear'),p('They build a little tower. It tumbles. They can try again!',0,['halli','jace'],'brick'),p('Mommy smiles. Being a kind big brother means helping, waiting, and playing together.',0,['mommy','jace','halli'],'bear')]},
 {id:'church',title:'My Quiet Church Morning',pages:[p('Jace walks into church with his family. He uses walking feet.',1,['mommy','jace','halli']),p('Jace sits beside Mommy. He puts his feet in front of him.',1,['jace','mommy']),p('He hears a song. He can sing gently with his family.',1,['jace','halli']),p('When someone is speaking, Jace uses his listening ears.',1,['jace']),p('Jace needs help. He whispers to Mommy. Mommy helps him.',1,['mommy','jace']),p('Church is finished. Jace smiles and waves. He practiced being kind and listening.',1,['jace','halli','mommy'])]},
 {id:'listen',title:'Jace Listens to Mommy',pages:[p('Jace is busy playing. Mommy says, “It is time to get ready.”',0,['mommy','jace'],'dinosaur'),p('Jace stops his toy and looks toward Mommy.',0,['jace'],'dinosaur'),p('“First, put your toy in the basket.” Jace puts it away.',0,['jace'],'dinosaur'),p('“Now, find your shoes.” Jace asks for help when he needs it.',4,['jace','mommy']),p('Mommy gives one little direction at a time. Jace tries his best.',0,['mommy','jace']),p('They are ready! Listening helped them work together.',2,['mommy','jace','halli'])]},
 {id:'fair',title:'Our Turn to Play',pages:[p('Jace and a friend both want the toy truck.',2,['jace'],'brick'),p('Jace says, “Can I have a turn?” He keeps gentle hands.',2,['jace']),p('While he waits, Jace chooses a dinosaur.',2,['jace'],'dinosaur'),p('Now it is Jace’s turn. He says, “Thank you!”',2,['jace'],'brick'),p('When his turn ends, Jace passes the toy back.',2,['jace'],'brick'),p('Waiting and sharing make room for everyone to have fun.',2,['jace','halli'],'bear')]},
 {id:'fishing',title:'Fishing with Dada',pages:[p('Jace and Dada visit the lake together. Jace stays close to his grown-up.',3,['jace']),p('Dada helps Jace put on his life jacket near the water.',3,['jace']),p('They look at the calm lake. Jace notices the orange leaves.',3,['jace']),p('Dada helps with the fishing gear. Jace watches and listens.',3,['jace']),p('They wait quietly. A tiny ripple moves across the water.',3,['jace']),p('Whether they catch a fish or not, Jace loves spending time with Dada.',3,['jace'])]}
],halli:[
 {id:'pink',title:'Halli Sees Pink',pages:[p('Pink. Pink blanket.',4,['halli']),p('Pink. Halli’s bow.',4,['halli']),p('Baby. Pink pajamas.',4,['halli'],'baby'),p('Hug the baby. Gentle hug.',4,['halli'],'baby'),p('Night-night, baby. Night-night.',4,['halli'],'bear')]},
 {id:'family',title:'Hello, Family!',pages:[p('Hello, Halli!',0,['halli']),p('Hello, Jace! Big brother.',0,['jace','halli']),p('Hello, Mommy! I love you.',0,['mommy','halli']),p('Hello, Unique! Big sister.',0,['unique','halli']),p('We are a family. Love, love, love.',0,['mommy','unique','jace','halli'])]},
 {id:'eat',title:'Eat, Eat!',pages:[p('Time to eat. Wash, wash.',5,['halli']),p('Banana. Yellow banana.',5,['halli'],'banana'),p('Bread. Soft bread.',5,['halli'],'toast'),p('A little taste. Yum, yum.',5,['halli'],'apple'),p('All done. Thank you!',5,['halli','jace'])]},
 {id:'play',title:'Halli Plays',pages:[p('Outside! Hello, sunshine.',2,['halli']),p('Up, up. Down, down.',2,['halli']),p('Ball. Roll, roll.',2,['halli'],'ball'),p('Jace plays too. Your turn.',2,['halli','jace'],'bear'),p('Bye-bye, playground!',2,['halli','jace'])]},
 {id:'sleep',title:'Sleepy Little Halli',pages:[p('The moon is up.',4,['halli']),p('Pajamas on. Cozy, cozy.',4,['halli'],'baby'),p('One little book.',4,['halli','mommy']),p('A gentle hug. I love you.',4,['mommy','halli']),p('Good night, Halli.',4,['halli'],'bear')]}
]};
export function shuffled(a,random=Math.random){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
export function choicesFor(correct,pool,random=Math.random){return shuffled([correct,...shuffled(pool.filter(x=>String(x)!==String(correct)),random).slice(0,2)],random);}
export function numberQuiz(random=Math.random){return shuffled(NUMBERS.map(x=>x.id),random).slice(0,5).map(id=>({correct:id,options:choicesFor(id,NUMBERS.map(x=>x.id),random)}));}
export function gradeFor(score,total){const r=score/total;return r>=.8?'A':r>=.6?'B':r>=.4?'C':r>0?'D':'F';}
