import {TOYS,COLORS,shuffled} from './data.mjs?v=school-1';
const atlasURL=new URL('../../assets/school/toys-v1.webp',import.meta.url).href;
const img=new Image();img.src=atlasURL;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function oval(c,x,y,rx,ry,color){c.beginPath();c.ellipse(x,y,rx,ry,0,0,Math.PI*2);c.fillStyle=color;c.fill();}
function rounded(c,x,y,w,h,r,fill){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();}
function sprite(c,id,x,y,size,rotation=0){if(!img.complete||!img.naturalWidth)return;const n=TOYS[id];if(n===undefined)return;const w=img.naturalWidth/4,h=img.naturalHeight/4;c.save();c.translate(x,y);c.rotate(rotation);c.globalCompositeOperation='multiply';c.drawImage(img,(n%4)*w,Math.floor(n/4)*h,w,h,-size/2,-size/2,size,size);c.restore();}
function block(c,b){const w=b.w||116,h=52,d=24;const {x,y,color}=b;c.save();c.shadowColor='#0004';c.shadowBlur=12;c.shadowOffsetY=7;rounded(c,x-w/2,y-h/2,w,h,7,color);c.shadowColor='transparent';c.fillStyle='#0002';c.fillRect(x-w/2,y+4,w,h/2-4);c.beginPath();c.moveTo(x-w/2,y-h/2);c.lineTo(x-w/2+d,y-h/2-d);c.lineTo(x+w/2+d,y-h/2-d);c.lineTo(x+w/2,y-h/2);c.closePath();c.fillStyle=color;c.fill();c.fillStyle='#fff3';c.fill();c.beginPath();c.moveTo(x+w/2,y-h/2);c.lineTo(x+w/2+d,y-h/2-d);c.lineTo(x+w/2+d,y+h/2-d);c.lineTo(x+w/2,y+h/2);c.closePath();c.fillStyle=color;c.fill();c.fillStyle='#0003';c.fill();for(let i=0;i<3;i++){oval(c,x-w/2+25+i*32,y-h/2-10,11,6,'#0002');oval(c,x-w/2+25+i*32,y-h/2-15,11,6,color);oval(c,x-w/2+23+i*32,y-h/2-17,5,2,'#fff5');}c.restore();}
export function mountToy(container,{kind,child='jace',audio,onFeedback=()=>{},onSave=()=>{},saved=null,roomImage=null}){
 const instructions={dinosaur:'Touch the meadow to make your dinosaur walk. Give it a roar or a jump!',blocks:'Drag a real-looking brick onto another brick to build. Tap a brick, then tap a new spot to move it.',dough:'Pick a color. Touch the mat to add dough. Drag it, squish it, or roll it!',baby:'Baby needs a little care. Feed her, cuddle her, then tuck her in.',kitchen:'Put food in the pan. Stir, cook, and serve your pretend meal!',sorting:'Drag each toy into the matching basket. You can also tap a toy, then its basket.',puzzle:'Fit all ten pieces into the picture. Drag a piece, or tap a piece and then its space.'};
 container.innerHTML=`<p class="toy-instructions">${instructions[kind]}</p><div class="toy-stage"><canvas width="1000" height="640" tabindex="0" aria-label="${instructions[kind]}"></canvas></div><div class="controls toy-controls"></div>`;
 const canvas=container.querySelector('canvas'),c=canvas.getContext('2d'),controls=container.querySelector('.toy-controls');let alive=true,frame=0,tick=0,drag=null,selected=null,lastTime=performance.now(),lastPoint=null,hasMoved=false,keyboardTarget=null;
 let pieces=[],doughColor=COLORS[0].hex,doughAction='add',babyState='hungry',babyTimer=0,panFood=[],cooking=0,stir=0,served=false,dino={x:420,y:380,targetX:420,targetY:380,jump:0,roar:0},puzzleImage=new Image(),placed=new Set();
 const report=text=>{onFeedback(text);audio.say(text);};
 function button(label,fn){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{audio.unlock();fn();};controls.append(b);return b;}
 function palette(){for(const color of COLORS.slice(0,8)){const b=button(color.name,()=>{doughColor=color.hex;controls.querySelectorAll('.selected').forEach(b=>b.classList.remove('selected'));b.classList.add('selected');audio.say(color.name);});b.style.borderBottom='8px solid '+color.hex;b.style.minWidth='70px';}}
 function reset(){selected=null;drag=null;placed.clear();if(kind==='blocks')pieces=Array.from({length:8},(_,i)=>({x:110+(i%4)*210,y:180+Math.floor(i/4)*230,color:COLORS[i%6].hex,w:116}));if(kind==='dough')pieces=[{x:340,y:320,r:78,rx:1,ry:1,color:'#e979aa'},{x:630,y:330,r:78,rx:1,ry:1,color:'#52aac4'}];if(kind==='sorting')pieces=shuffled(['apple','banana','dinosaur','cat','duck','brick']).map((id,i)=>({id,x:95+i*160,y:150,done:false}));if(kind==='puzzle')pieces=shuffled(Array.from({length:10},(_,id)=>id)).map((id,i)=>({id,x:800+(i%2)*125,y:85+Math.floor(i/2)*110,done:false}));}
 reset();
 if(Array.isArray(saved)&&(kind==='blocks'||kind==='dough'))pieces=saved.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&typeof p.color==='string').slice(0,50).map(p=>({...p,x:clamp(p.x,40,960),y:clamp(p.y,50,600)}));
 if(kind==='dinosaur'){button('Roar!',()=>{dino.roar=1;audio.roar();onFeedback('Roar! Your dinosaur is talking.');});button('Jump!',()=>{dino.jump=1;audio.tone(380,.16);});button('Give a snack',()=>{dino.targetX=820;dino.targetY=420;report('Stomp, stomp! Time for a pretend dinosaur snack.');});}
 if(kind==='blocks'){button('Add a brick',()=>{if(pieces.length>=35)return;pieces.push({x:150+Math.random()*650,y:120,color:COLORS[pieces.length%8].hex,w:116});audio.tone();});button('Start over',()=>{reset();onSave(pieces);});button('Count my bricks',()=>report(`${pieces.length} bricks. You are a builder!`));}
 if(kind==='dough'){palette();for(const action of ['add','squish','roll'])button(action[0].toUpperCase()+action.slice(1),()=>{doughAction=action;report(action==='add'?'Touch an empty spot to make some dough.':`Touch your dough to ${action} it.`);});button('Clear mat',()=>{pieces=[];onSave(pieces);});}
 if(kind==='baby'){button('Feed baby',()=>{babyState='eating';babyTimer=4;audio.tone(440,.2);report('Eat, eat! Baby is having a little meal.');});button('Gentle cuddle',()=>{babyState='happy';babyTimer=3;audio.cheer();onFeedback('A gentle cuddle. Baby feels loved.');});button('Night-night',()=>{babyState='asleep';report('Shhh. Baby is sleeping. Good night, baby.');});button('Wake baby',()=>{babyState='happy';report('Good morning, baby!');});}
 if(kind==='kitchen'){for(const id of ['apple','banana','toast','soup'])button(id,()=>{if(panFood.length<5){panFood.push(id);served=false;cooking=0;audio.say(id);}});button('Stir',()=>{if(!panFood.length)return report('Choose a food first.');stir+=1;audio.tone(500,.13);onFeedback('Round and round. Stir your pretend meal!');});button('Cook',()=>{if(!panFood.length)return report('Put food in the pan first.');cooking=1;audio.tone(140,.4);onFeedback('Your pretend food is warming up.');});button('Serve',()=>{if(!panFood.length)return report('Choose some food first.');served=true;report('Dinner is served! Thank you, little chef.');});button('Wash up',()=>{panFood=[];cooking=0;served=false;report('A clean kitchen, ready for next time!');});}
 if(kind==='sorting')button('Mix again',reset);
 if(kind==='puzzle'){puzzleImage.src=roomImage;button('Show the picture',()=>{peek=2;});button('Mix again',reset);}
 let peek=0;
 function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)/r.width*1000,y:(e.clientY-r.top)/r.height*640};}
 function hit(p){if(kind==='puzzle')return pieces.slice().reverse().find(b=>!b.done&&Math.abs(b.x-p.x)<57&&Math.abs(b.y-p.y)<39);if(kind==='sorting')return pieces.find(b=>!b.done&&Math.hypot(b.x-p.x,b.y-p.y)<76);return pieces.slice().reverse().find(b=>Math.abs(b.x-p.x)<(b.r||85)*(b.rx||1)&&Math.abs(b.y-p.y)<(b.r||50)*(b.ry||1));}
 function basketFor(id){return ['apple','cat'].includes(id)?0:['banana','duck'].includes(id)?1:2;}
 function down(e){audio.unlock();const p=point(e);canvas.setPointerCapture(e.pointerId);lastPoint=p;hasMoved=false;if(kind==='dinosaur'){dino.targetX=clamp(p.x,90,910);dino.targetY=clamp(p.y,270,480);return;}if(kind==='baby'){if(babyState!=='asleep'){babyState='happy';babyTimer=2;audio.tone(660,.18);onFeedback('Gentle pats. Baby smiles.');}return;}if(kind==='kitchen'){stir++;audio.tone(480,.12);return;}const piece=hit(p);if(piece){selected=piece;drag={piece,dx:p.x-piece.x,dy:p.y-piece.y};if(kind==='dough'&&doughAction!=='add'){if(doughAction==='squish'){piece.rx=clamp((piece.rx||1)+.2,1,2);piece.ry=clamp((piece.ry||1)-.12,.35,1);}else{piece.rx=clamp((piece.rx||1)+.25,1,2.5);piece.ry=.45;}audio.tone(230,.15);}}else if(selected){selected.x=p.x;selected.y=p.y;drop(selected);selected=null;}else if(kind==='dough'&&pieces.length<30){pieces.push({x:p.x,y:p.y,r:65,rx:1,ry:1,color:doughColor});audio.tone(350,.15);onSave(pieces);}}
 function move(e){if(!drag)return;const p=point(e);if(Math.hypot(p.x-lastPoint.x,p.y-lastPoint.y)>7)hasMoved=true;drag.piece.x=clamp(p.x-drag.dx,65,935);drag.piece.y=clamp(p.y-drag.dy,65,585);}
 function drop(b){if(kind==='blocks'){const under=pieces.filter(p=>p!==b&&Math.abs(p.x-b.x)<100&&p.y>b.y-10&&p.y-b.y<105).sort((a,b)=>a.y-b.y)[0];if(under){b.x=under.x;b.y=under.y-56;audio.tone(500,.1);}onSave(pieces);}if(kind==='dough')onSave(pieces);if(kind==='sorting'){const bin=basketFor(b.id),x=190+bin*310;if(Math.abs(b.x-x)<130&&b.y>340){b.x=x-40+Math.random()*80;b.y=440+Math.random()*35;b.done=true;audio.tone(650,.15);if(pieces.every(p=>p.done)){audio.cheer();report('All sorted! You matched the colors.');}else onFeedback('That toy is in its matching basket.');}else{b.x=95+pieces.indexOf(b)*160;b.y=150;onFeedback('Try the basket with the same color.');}}if(kind==='puzzle'){const x=220+(b.id%2)*300,y=120+Math.floor(b.id/2)*80;if(Math.abs(b.x-x)<145&&Math.abs(b.y-y)<40){b.x=x;b.y=y;b.done=true;placed.add(b.id);audio.tone(400+placed.size*45,.13);onFeedback(`${placed.size} of 10 pieces fit!`);if(placed.size===10){audio.cheer();report('You finished all ten pieces!');}}}}
 function up(e){if(drag){if(hasMoved||kind==='dough'){drop(drag.piece);selected=null;}drag=null;}if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);
 canvas.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' '].includes(e.key))return;e.preventDefault();if(kind==='dinosaur'){dino.targetX=clamp(dino.targetX+(e.key==='ArrowLeft'?-40:e.key==='ArrowRight'?40:0),90,910);dino.targetY=clamp(dino.targetY+(e.key==='ArrowUp'?-30:e.key==='ArrowDown'?30:0),270,480);if(e.key===' ')dino.jump=1;return;}keyboardTarget ||= pieces.find(p=>!p.done);if(!keyboardTarget)return;selected=keyboardTarget;if(e.key==='ArrowLeft')selected.x-=20;if(e.key==='ArrowRight')selected.x+=20;if(e.key==='ArrowUp')selected.y-=20;if(e.key==='ArrowDown')selected.y+=20;if(e.key==='Enter'){drop(selected);keyboardTarget=pieces.find(p=>!p.done&&p!==selected);}};
 function background(){const g=c.createLinearGradient(0,0,0,640);g.addColorStop(0,'#f7ead4');g.addColorStop(.68,'#d9b888');g.addColorStop(1,'#c19b6c');c.fillStyle=g;c.fillRect(0,0,1000,640);for(let i=0;i<9;i++){c.strokeStyle='#ad805028';c.beginPath();c.moveTo(0,80*i+Math.sin(i)*15);c.bezierCurveTo(240,80*i-20,770,80*i+30,1000,80*i);c.stroke();}rounded(c,25,25,950,585,32,'#fff5');}
 function drawDino(dt){c.fillStyle='#c8e8f4';c.fillRect(0,0,1000,640);const g=c.createLinearGradient(0,230,0,640);g.addColorStop(0,'#a4c969');g.addColorStop(1,'#4e8147');c.fillStyle=g;c.fillRect(0,245,1000,395);for(let i=0;i<12;i++){oval(c,i*95,255+Math.sin(i)*30,88,65,'#80ac51');}for(let i=0;i<50;i++){c.strokeStyle=i%2?'#7caf56':'#689743';c.lineWidth=4;c.beginPath();let x=(i*153)%1000,y=320+(i*73)%300;c.moveTo(x,y);c.lineTo(x+10,y-25);c.stroke();}const dx=dino.targetX-dino.x,dy=dino.targetY-dino.y,walk=Math.hypot(dx,dy)>4;dino.x+=dx*Math.min(1,dt*2.2);dino.y+=dy*Math.min(1,dt*2.2);dino.jump=Math.max(0,dino.jump-dt*1.7);dino.roar=Math.max(0,dino.roar-dt);const jump=Math.sin(dino.jump*Math.PI)*100;oval(c,dino.x,dino.y+102,107,22,'#17392145');c.save();c.translate(dino.x,dino.y-jump+(walk?Math.sin(tick*15)*6:0));if(dx<0)c.scale(-1,1);sprite(c,'dinosaur',0,0,310,dino.roar?Math.sin(tick*25)*.04:walk?Math.sin(tick*8)*.025:0);c.restore();sprite(c,'apple',845,500,80);if(dino.roar){c.fillStyle='#fff';c.font='900 54px Trebuchet MS';c.fillText('ROAR!',dino.x-70,dino.y-165);}}
 function drawBaby(dt){rounded(c,90,45,820,540,65,'#ecc2d2');for(let x=150;x<900;x+=120)oval(c,x,550,40,16,'#d398b8');oval(c,500,505,165,35,'#7941643a');const bounce=babyState==='happy'?Math.sin(tick*5)*10:0;sprite(c,'baby',500,310+bounce,430,babyState==='asleep'?-.12:0);if(babyState==='hungry'){const y=260+Math.sin(tick*4)*5;oval(c,448,y,6,13,'#78bfea');oval(c,557,y,6,13,'#78bfea');}if(babyState==='eating'){rounded(c,566,275,45,80,12,'#fff9e7');rounded(c,570,263,37,20,7,'#ed98b9');oval(c,588,261,7,10,'#f2d9ba');}if(babyState==='asleep'){rounded(c,360,345,295,145,30,'#d8a2c3');c.strokeStyle='#c27fad';c.lineWidth=8;c.strokeRect(378,360,260,114);c.font='bold 40px Trebuchet MS';c.fillStyle='#865278';c.fillText('z',675,230+Math.sin(tick)*12);c.fillText('z',715,190+Math.sin(tick)*12);}if(babyTimer>0){babyTimer-=dt;if(babyTimer<=0){babyState='happy';onFeedback('Baby smiles. You are taking good care of her.');}}}
 function drawKitchen(dt){rounded(c,35,40,930,510,30,'#d9e6db');rounded(c,80,100,600,420,25,'#a4b9b5');oval(c,380,315,210,155,'#6c8c8955');sprite(c,'pan',380,295,490);for(let i=0;i<panFood.length;i++){const a=(i/panFood.length)*Math.PI*2+stir*.8;sprite(c,panFood[i],served?800+Math.cos(a)*40:345+Math.cos(a)*70,served?320+Math.sin(a)*40:325+Math.sin(a)*45,95);}oval(c,805,325,130,90,'#fff');if(served)for(let i=0;i<panFood.length;i++)sprite(c,panFood[i],770+(i%2)*70,295+Math.floor(i/2)*53,85);if(cooking){cooking=Math.min(2,cooking+dt*.4);c.strokeStyle='#ffffffbc';c.lineWidth=9;for(let i=0;i<3;i++){c.beginPath();c.moveTo(280+i*75,220);c.bezierCurveTo(260+i*75,170,320+i*75,170,300+i*75,100+Math.sin(tick*3+i)*20);c.stroke();}}sprite(c,'pot',820,520,150);}
 function loop(now){if(!alive)return;const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;tick+=dt;background();if(kind==='dinosaur')drawDino(dt);if(kind==='baby')drawBaby(dt);if(kind==='kitchen')drawKitchen(dt);if(kind==='blocks'){pieces.filter(p=>p!==drag?.piece).sort((a,b)=>a.y-b.y).forEach(b=>block(c,b));if(drag)block(c,drag.piece);}if(kind==='dough'){for(const b of pieces){c.save();c.translate(b.x,b.y);c.scale(b.rx,b.ry);const grad=c.createRadialGradient(-25,-25,5,0,0,b.r);grad.addColorStop(0,'#ffffff');grad.addColorStop(.22,b.color);grad.addColorStop(1,b.color);c.shadowColor='#34271c50';c.shadowBlur=16;c.shadowOffsetY=10;oval(c,0,0,b.r,b.r,grad);c.shadowColor='transparent';oval(c,-b.r*.2,-b.r*.3,b.r*.35,b.r*.2,'#ffffff28');c.restore();}}if(kind==='sorting'){for(let i=0;i<3;i++){const x=190+i*310,color=['#d66e64','#e3bb50','#70a778'][i];rounded(c,x-128,355,256,182,25,color);c.strokeStyle='#77593355';c.lineWidth=5;for(let j=0;j<8;j++){c.beginPath();c.moveTo(x-115+j*32,370);c.lineTo(x-115+j*32,521);c.stroke();}c.fillStyle='#fff';c.font='bold 26px Trebuchet MS';c.textAlign='center';c.fillText(['Red & orange','Yellow','Green'][i],x,580);c.textAlign='start';}pieces.forEach(b=>sprite(c,b.id,b.x,b.y,b.done?100:133));}if(kind==='puzzle'){if(puzzleImage.complete&&puzzleImage.naturalWidth){c.globalAlpha=.2;c.drawImage(puzzleImage,70,80,600,400);c.globalAlpha=1;for(let i=0;i<10;i++){c.strokeStyle='#5f514a66';c.strokeRect(70+(i%2)*300,80+Math.floor(i/2)*80,300,80);}for(const b of pieces){c.save();c.shadowColor='#0006';c.shadowBlur=b.done?0:9;c.shadowOffsetY=b.done?0:4;const w=b.done?300:114,h=b.done?80:30.4;c.fillStyle='#fff';c.fillRect(b.x-w/2-2,b.y-h/2-2,w+4,h+4);c.drawImage(puzzleImage,(b.id%2)*puzzleImage.naturalWidth/2,Math.floor(b.id/2)*puzzleImage.naturalHeight/5,puzzleImage.naturalWidth/2,puzzleImage.naturalHeight/5,b.x-w/2,b.y-h/2,w,h);c.restore();}if(peek>0){peek-=dt;c.fillStyle='#fffdf6ef';c.fillRect(50,25,900,570);c.drawImage(puzzleImage,95,40,810,540);}}}if(selected&&!selected.done){c.strokeStyle='#f1bc35';c.lineWidth=5;c.strokeRect(selected.x-85,selected.y-65,170,130);}frame=requestAnimationFrame(loop);}
 frame=requestAnimationFrame(loop);
 return ()=>{alive=false;cancelAnimationFrame(frame);if(kind==='blocks'||kind==='dough')onSave(pieces);canvas.onkeydown=null;canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);};
}
