import { Renderer } from './render.mjs';
import { Sound } from './audio.mjs';
import { LOCATIONS } from './locations.mjs';
const $=id=>document.getElementById(id),renderer=new Renderer($('world')),sound=new Sound();
let me=null,data=null,bubbles=[],snapshot={players:[],npcs:[],cut:[],tag:{}},events=null,role='',profiles=[],online=false,busy=false,lastIt=null,input={gas:0,brake:0,steer:0},inputBusy=false;
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json();if(!r.ok){if(r.status===401&&me){stop();show('welcome');}throw Error(result.error);}return result;}
function show(id){['welcome','profiles','play'].forEach(x=>$(x).classList.toggle('hidden',x!==id));}
async function load(){try{const r=await api('me');role=r.role;profiles=r.profiles;if(r.selected){const resumed=await api('resume',{});me=resumed.player;data=resumed.data;bubbles=resumed.bubbles;sound.mute(data.preferences.sound);$('parent').classList.toggle('hidden',role!=='parent');$('back').textContent='Switch / sign out';show('play');updateUI();connect();return;}show('profiles');$('profile-list').replaceChildren();for(const p of profiles){const b=document.createElement('button');b.className='profile';const portrait=document.createElement('span');portrait.className='portrait';portrait.textContent=p.name[0].toUpperCase();const n=document.createElement('b');n.textContent=p.name.toUpperCase();const a=document.createElement('small');a.textContent=p.mode==='toddler'?'TOUCH & EXPLORE':p.mode==='preschool'?'PLAY & DISCOVER':p.mode==='adult'?'FAMILY ADVENTURES':'EXPLORE TOGETHER';b.append(portrait,n,a);b.onclick=()=>select(p.id);$('profile-list').append(b);}}catch{show('welcome');}}
$('login').onsubmit=async e=>{e.preventDefault();try{await api('login',{password:$('password').value});$('password').value='';$('login-error').textContent='';await load();}catch(e){$('login-error').textContent=e.message;}};
$('accept').onsubmit=async e=>{e.preventDefault();try{const raw=$('invite').value.trim();const t=raw.includes('#invite=')?raw.split('#invite=')[1]:raw;await api('invite/accept',{token:t});$('invite').value='';await load();}catch(e){$('login-error').textContent=e.message;}};
if(location.hash.startsWith('#invite=')){$('invite').value=location.hash.slice(8);history.replaceState(null,'',location.pathname);$('accept').closest('details').open=true;}
function stop(){events?.close();events=null;me=null;online=false;input={gas:0,brake:0,steer:0};sound.motor(null);}
async function logout(){stop();await api('logout',{});$('admin').close();show('welcome');}
$('profile-logout').onclick=logout;$('back').onclick=async()=>{await logout();$('login-error').textContent='Mommy can sign in to switch profiles or approve another device.';};
async function select(id){try{sound.unlock();const r=await api('select',{profile:id});me=r.player;data=r.data;bubbles=r.bubbles;role=me.profile==='mommy'?role:'device';sound.mute(data.preferences.sound);$('parent').classList.toggle('hidden',role!=='parent');$('back').textContent='Switch / sign out';show('play');updateUI();connect();sound.say('Welcome to our world. Hold Go to move. Turn the wheel to steer.',true);}catch(e){$('profile-error').textContent=e.message;}}
function connect(){events?.close();events=new EventSource('/api/events');events.onmessage=e=>{snapshot=JSON.parse(e.data);online=true;$('connection').textContent=`${snapshot.players.length} family player${snapshot.players.length===1?'':'s'} · shared world`;const p=snapshot.players.find(p=>p.id===me?.id);if(p){me=p;updateUI();}if(snapshot.tag.active&&snapshot.tag.it!==lastIt){lastIt=snapshot.tag.it;sound.tone(650);sound.say(lastIt===me?.id?'You’re it!':'Run! You’re playing tag.',true);navigator.vibrate?.(30);}};events.onerror=()=>{online=false;input.gas=0;$('connection').textContent='Reconnecting… movement paused';api('me').catch(()=>{});};}
function updateUI(){if(!me)return;document.body.classList.toggle('toddler',me.mode==='toddler');$('sound').textContent=sound.enabled?'Sound on':'Sound off';const outside=me.scene==='world';$('controls').classList.toggle('hidden',!outside);$('scene-exit').classList.toggle('hidden',outside);$('home-panel').classList.toggle('hidden',me.scene!=='home');$('classic-panel').classList.toggle('hidden',me.scene!=='classic');$('bubble-score').classList.toggle('hidden',me.scene!=='bubbles');$('hint').classList.toggle('hidden',!outside&&me.scene!=='bubbles');$('place').textContent=me.scene==='bubbles'?'Halli’s Bubble Garden':me.scene==='home'?'Our Home':me.scene==='classic'?'Game House':'Our Neighborhood';
 $('gas').textContent=me.vehicle==='walk'?'GO':'GAS';$('start').classList.toggle('hidden',me.vehicle==='walk'||!outside);$('start').textContent=me.engine?'Stop':'Start';$('vehicle').textContent=me.vehicle==='walk'?'Ride car':'Walk';$('vehicle').classList.toggle('hidden',me.vehicle==='mower');$('tag').classList.toggle('hidden',me.vehicle!=='walk');$('tag').textContent=snapshot.tag.active?'Stop tag':'Play tag';const near=LOCATIONS.find(l=>Math.hypot(me.x-l.x,me.y-(l.y+45))<120);$('enter').classList.toggle('hidden',!near||!outside||me.vehicle==='mower');if(near)$('enter').textContent=near.action==='mower'?'Mow grass':`Enter ${near.name}`;
 if(me.scene==='bubbles'){const level=1+Math.min(2,Math.floor(data.pops/15));$('bubble-score').textContent=`Level ${level} · ${data.pops} pops`;$('hint').textContent=level===1?'Tap a bubble. Pop, pop, pop!':level===2?'Pop a color. Say its name!':'Pop for a surprise word!';}else $('hint').textContent=me.vehicle==='mower'?'Start the mower, hold GAS, and steer across tall grass.':near?`You found ${near.name}. Tap ${near.action==='mower'?'Mow grass':'Enter'}!`:me.vehicle==='walk'?'Hold GO to walk. Turn the wheel. Arrow keys work too.':me.engine?'Hold GAS and turn the wheel. BRAKE slows down.':'Tap START to start your car.';
 sound.motor(me);
}
async function action(action,extra={}){if(busy||!me)return;busy=true;try{sound.unlock();const r=await api('action',{action,...extra});me=r.player;data=r.data;bubbles=r.bubbles;updateUI();if(action==='enter'&&me.scene==='bubbles')sound.say('Pop! Now you say pop.',true);if(action==='start')sound.tone(110,.2);}catch(e){$('hint').textContent=e.message;}finally{busy=false;}}
$('vehicle').onclick=()=>action('vehicle');$('start').onclick=()=>action('start');$('enter').onclick=()=>action('enter');$('tag').onclick=()=>action('tag');['scene-exit','home-outside','classic-outside'].forEach(id=>$(id).onclick=()=>action('exit'));
$('sound').onclick=()=>{sound.mute(!sound.enabled);action('preferences',{sound:sound.enabled});updateUI();};
function pedal(id,key){const el=$(id);el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);sound.unlock();input[key]=1;};el.onpointerup=el.onpointercancel=()=>{input[key]=0;};}pedal('gas','gas');pedal('brake','brake');
const wheel=$('wheel');let steering=false;function steer(e){const r=wheel.getBoundingClientRect();input.steer=Math.max(-1,Math.min(1,(e.clientX-r.left-r.width/2)/(r.width*.42)));wheel.setAttribute('aria-valuenow',Math.round(input.steer*100));wheel.querySelector('svg').style.transform=`rotate(${input.steer*80}deg)`;}
wheel.onpointerdown=e=>{e.preventDefault();steering=true;wheel.setPointerCapture(e.pointerId);steer(e);};wheel.onpointermove=e=>{if(steering)steer(e);};wheel.onpointerup=wheel.onpointercancel=()=>{steering=false;input.steer=0;wheel.querySelector('svg').style.transform='';};
const keySet=new Set();function keys(){input.gas=keySet.has('ArrowUp')||keySet.has('w')?1:0;input.brake=keySet.has('ArrowDown')||keySet.has('s')?1:0;input.steer=(keySet.has('ArrowRight')||keySet.has('d')?1:0)-(keySet.has('ArrowLeft')||keySet.has('a')?1:0);}
addEventListener('keydown',e=>{if(!me||e.target.matches('input,textarea,select'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){e.preventDefault();keySet.add(e.key);keys();}});addEventListener('keyup',e=>{keySet.delete(e.key);keys();});
function release(){keySet.clear();input={gas:0,brake:1,steer:0};sound.motor(null);}addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});
setInterval(async()=>{if(!me||!online||inputBusy)return;inputBusy=true;try{await api('input',document.hidden?{gas:0,brake:1,steer:0}:input);}catch{online=false;}finally{inputBusy=false;}},100);
$('world').onpointerdown=async e=>{if(me?.scene!=='bubbles'||busy)return;const r=$('world').getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const b=renderer.bubbleHits.find(b=>Math.hypot(x-b.x,y-b.y)<b.r);if(!b)return;const count=data.pops;await action('pop',{id:b.id});if(data.pops===count)return;renderer.pop(x,y);sound.tone(500+Math.random()*300);navigator.vibrate?.(15);if(data.pops<15)sound.prompt();else if(data.pops<30)sound.say(['Pink.','Blue.','Yellow.','Green.'][b.color]);else sound.say(['Ball. Roll a ball.','Car. Vroom, vroom!','Baby. Say baby.','More. Say more.'][b.color]);};
$('parent').onclick=async()=>{try{const r=await api('me');$('invite-profile').replaceChildren();for(const p of r.profiles.filter(p=>p.id!=='mommy')){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('invite-profile').append(o);}$('admin').showModal();await devices();}catch(e){$('hint').textContent=e.message;}};
async function devices(){const r=await api('devices');$('device-list').replaceChildren();for(const d of r.devices){const row=document.createElement('div'),label=document.createElement('span');label.textContent=d.current?'This device (Mommy)':`${d.profile||'Mommy'} · ${d.role}`;row.append(label);if(!d.current){const b=document.createElement('button');b.textContent='Revoke';b.onclick=async()=>{await api('revoke',{hash:d.hash});await devices();};row.append(b);}$('device-list').append(row);}}
$('invite-form').onsubmit=async e=>{e.preventDefault();try{const r=await api('invites',{profile:$('invite-profile').value,guestName:$('guest-name').value.trim()||undefined});$('invite-link').value=`${location.origin}/#invite=${r.token}`;$('admin-status').textContent='Invitation ready. Share it with the approved device. It expires in one hour.';$('guest-name').value='';}catch(e){$('admin-status').textContent=e.message;}};
$('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('invite-link').value);$('admin-status').textContent='Invitation copied.';}catch{$('invite-link').select();$('admin-status').textContent='Select and copy the invitation above.';}};
addEventListener('resize',()=>renderer.resize());function loop(t){renderer.draw(snapshot,me,bubbles,data,t);requestAnimationFrame(loop);}requestAnimationFrame(loop);await load();
