export class BowlingView{
 constructor(parent,{action,sound}){this.action=action;this.sound=sound;this.sequence=-1;this.state=null;this.aim=0;this.drag=null;this.shown=false;
  this.root=document.createElement('section');this.root.id='bowling-game';this.root.hidden=true;this.root.setAttribute('aria-label','Playable bowling lane');this.root.innerHTML='<div class="bowling-scores" aria-label="Bowling scores"></div><canvas tabindex="0" aria-label="Bowling lane. Swipe upward from the ball to throw. Or use the aim slider and Roll ball."></canvas><p class="bowling-message" role="status"></p><div class="bowling-console"><div class="bowling-colors" aria-label="Ball color"></div><label class="bowling-aim">Aim<input type="range" min="-90" max="90" value="0" aria-label="Aim the bowling ball"></label><button class="bowling-roll">Roll ball</button><button class="bowling-reset">New game</button></div>';
  parent.append(this.root);this.canvas=this.root.querySelector('canvas');this.ctx=this.canvas.getContext('2d');this.message=this.root.querySelector('.bowling-message');this.scores=this.root.querySelector('.bowling-scores');this.roll=this.root.querySelector('.bowling-roll');this.reset=this.root.querySelector('.bowling-reset');this.slider=this.root.querySelector('input');this.slider.oninput=()=>this.aim=Number(this.slider.value)/100;
  this.roll.onclick=()=>this.send(this.aim,.75);this.reset.onclick=()=>action('bowl-reset');
  const colors=this.root.querySelector('.bowling-colors');for(const [name,color]of[['Purple','#a673ef'],['Pink','#ff72ad'],['Blue','#56bcee'],['Gold','#efbd4e'],['Green','#68ca87']]){const b=document.createElement('button');b.style.background=color;b.setAttribute('aria-label',name+' bowling ball');b.onclick=()=>action('ball-color',{color});colors.append(b);}
  const point=e=>{const r=this.canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
  this.canvas.onpointerdown=e=>{if(!this.canRoll)return;const p=point(e),ball=this.project(0,.5);if(Math.hypot(p.x-ball.x,p.y-ball.y)>Math.max(80,ball.s*.3))return;e.preventDefault();this.sound.unlock();this.drag={...p,t:performance.now()};this.canvas.setPointerCapture(e.pointerId);};
  this.canvas.onpointermove=e=>{if(!this.drag)return;const p=point(e);this.aim=Math.max(-.95,Math.min(.95,(p.x-this.drag.x)/Math.max(70,this.w*.28)));this.slider.value=this.aim*100;};
  this.canvas.onpointerup=e=>{if(!this.drag)return;const p=point(e),dy=this.drag.y-p.y,elapsed=performance.now()-this.drag.t;this.drag=null;if(dy<12)return;this.send(this.aim,Math.min(1,Math.max(.3,dy/Math.max(100,elapsed))));};this.canvas.onpointercancel=()=>this.drag=null;
  this.canvas.onkeydown=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();this.send(this.aim,.75);}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();this.aim=Math.max(-.9,Math.min(.9,this.aim+(e.key==='ArrowLeft'?-.1:.1)));this.slider.value=this.aim*100;}};
  this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(this.canvas);
 }
 async send(aim,power){if(!this.canRoll||this.sending)return;this.sending=true;try{await this.action('bowl',{aim,power,start:0});}finally{this.sending=false;}}
 resize(){const r=this.canvas.getBoundingClientRect();this.w=r.width;this.h=r.height;const d=Math.min(devicePixelRatio||1,2);this.canvas.width=this.w*d;this.canvas.height=this.h*d;this.ctx.setTransform(d,0,0,d,0,0);}
 update(state,me){const shown=me?.scene==='bowling';this.root.hidden=!shown;if(shown&&!this.shown){this.root.style.backgroundImage=`linear-gradient(#0a073660,#09051ee8),url("${new URL('../assets/scenes/arcade-v1.webp',import.meta.url)}")`;this.resize();}this.shown=shown;if(!shown)return;this.state=state;this.me=me;if(!state)return;this.canRoll=state.phase==='ready'&&state.current===me.id;this.roll.disabled=!this.canRoll;this.slider.disabled=!this.canRoll;this.reset.disabled=state.phase==='rolling';const current=state.members.find(m=>m.id===state.current);const message=this.canRoll?'Your turn! Swipe the ball up, or aim and tap Roll.':state.phase==='ready'?current?.name+' is bowling.':state.message;if(this.message.textContent!==message)this.message.textContent=message;
  const key=JSON.stringify(state.members.map(m=>[m.id,m.rolls,m.color,state.current===m.id]));if(key!==this.scoreKey){this.scoreKey=key;this.scores.replaceChildren();for(const m of state.members){const el=document.createElement('div');el.className=m.id===state.current?'active':'';const name=document.createElement('b'),line=document.createElement('span');name.textContent=m.name;line.textContent='Frame '+m.status.frame+' · '+m.score.total+' points'+(m.rolls.length?' · '+m.score.frames.map(f=>f.mark).join(' '):'');el.append(name,line);this.scores.append(el);}}
  if(state.sequence!==this.sequence){this.sequence=state.sequence;if(state.phase==='result'){this.sound.tone(560,.14);this.sound.say(state.message,true);navigator.vibrate?.(25);}else if(state.phase==='rolling')this.sound.tone(150,.15);}
 }
 project(x,y){const t=Math.max(0,Math.min(1,y/16)),depth=1/(1+t*3.7);const s=Math.min(this.w*.34,220)*depth;return {x:this.w/2+x*s,y:this.h*.13+(this.h*.83)*(1-t)/(1+t*2.2),s};}
 polygon(points,fill){const c=this.ctx;c.fillStyle=fill;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fill();}
 ball(x,y,color){const c=this.ctx,p=this.project(x,y),r=Math.max(5,p.s*.2),g=c.createRadialGradient(p.x-r*.35,p.y-r*.4,1,p.x,p.y,r);g.addColorStop(0,'#fff');g.addColorStop(.2,color);g.addColorStop(1,'#261038');c.save();c.shadowBlur=15;c.shadowColor=color;c.fillStyle=g;c.beginPath();c.arc(p.x,p.y-r*.3,r,0,Math.PI*2);c.fill();c.shadowBlur=0;c.fillStyle='#261737';for(const [dx,dy]of[[-.2,-.2],[.18,-.2],[0,.15]]){c.beginPath();c.arc(p.x+dx*r,p.y+(dy-.3)*r,r*.09,0,Math.PI*2);c.fill();}c.restore();}
 pin(pin){const c=this.ctx,p=this.project(pin.x,pin.y),size=p.s*.58;c.save();c.translate(p.x,p.y);c.rotate((pin.vx<0?-1:1)*pin.tilt*1.5);c.scale(size/24,size/24);c.shadowColor='#8cf5ff';c.shadowBlur=pin.fallen?0:10;const g=c.createLinearGradient(-7,0,7,0);g.addColorStop(0,'#afcae6');g.addColorStop(.4,'#fff');g.addColorStop(1,'#b4b9d3');c.fillStyle=g;c.beginPath();c.moveTo(-5,0);c.bezierCurveTo(-12,-1,-10,-13,-5,-18);c.bezierCurveTo(-2,-22,-2,-26,-4,-29);c.bezierCurveTo(-8,-35,8,-35,4,-29);c.bezierCurveTo(2,-26,2,-22,5,-18);c.bezierCurveTo(10,-13,12,-1,5,0);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#ec599c';c.fillRect(-3,-24,6,2);c.fillRect(-3,-20,6,2);c.restore();}
 draw(){if(!this.shown||!this.state||!this.w)return;const c=this.ctx;c.clearRect(0,0,this.w,this.h);const P=(x,y)=>this.project(x,y);
  this.polygon([P(-1.28,0),P(1.28,0),P(1.28,16),P(-1.28,16)],'#100e2d');
  for(let i=0;i<18;i++){const x=-1+i/9;this.polygon([P(x,0),P(x+1/9,0),P(x+1/9,16),P(x,16)],i%3===0?'#dbad77':i%2?'#c99468':'#e1b782');}
  for(const x of[-1.18,1.18]){c.strokeStyle=x<0?'#49e9ff':'#f167ff';c.shadowBlur=12;c.shadowColor=c.strokeStyle;c.lineWidth=3;c.beginPath();const a=P(x,0),b=P(x,16);c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.shadowBlur=0;}
  this.state.pins.slice().sort((a,b)=>b.y-a.y).forEach(pin=>this.pin(pin));const ball=this.state.ball;if(ball&&ball.y<16)this.ball(ball.x,ball.y,ball.color);
  if(this.state.phase==='ready'){const m=this.state.members.find(m=>m.id===this.state.current);this.ball(0,.5,m?.color||'#a673ef');if(this.canRoll){c.strokeStyle='#fff9';c.lineWidth=2;c.setLineDash([5,8]);const a=P(0,1.8),b=P(this.aim,11);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.setLineDash([]);}}
 }
}
