import {MonsterRace,CIRCUITS,PAINTS,DESIGNS,truck} from './engine.mjs';
import {MonsterRenderer,drawTruck,truckReady} from './render.mjs';
import {TruckRoom,normalizeInput} from './network.mjs';
import {DrivingInput} from '../racing/controls.mjs?v=race-1';
import {RaceAudio} from '../racing/audio.mjs?v=race-1';
import {ordinal,formatTime} from '../racing/config.mjs?v=race-1';
const $=id=>document.getElementById(id),inputs=[new DrivingInput(),new DrivingInput()],renderers=[new MonsterRenderer($('canvas-0')),new MonsterRenderer($('canvas-1'))],audio=new RaceAudio();audio.setEnabled(false);
let settings={track:'speedway',paints:[PAINTS[0],PAINTS[3]],designs:[0,2]},mode='solo',editor=0,game=null,running=false,paused=false,last=0,accumulator=0,lastSend=0,remoteAt=0,remoteInput={gas:0,brake:1,steer:0},remoteSeq=-1,seq=0,raceId=0,snapshotSeq=-1,finished=false,networkPaused=false;
try{const s=JSON.parse(localStorage.getItem('jhw-monster-custom-v1'));if(s){settings.track=CIRCUITS.some(t=>t.id===s.track)?s.track:'speedway';settings.paints=[0,1].map(i=>PAINTS.includes(s.paints?.[i])?s.paints[i]:settings.paints[i]);settings.designs=[0,1].map(i=>Number.isInteger(s.designs?.[i])&&s.designs[i]>=0&&s.designs[i]<3?s.designs[i]:settings.designs[i]);}}catch{}
const room=new TruckRoom(onNetwork,text=>{$('network-status').textContent=text;});
function save(){try{localStorage.setItem('jhw-monster-custom-v1',JSON.stringify(settings));}catch{}if(mode==='online'&&room.joined&&!room.host)room.send({type:'design',paint:settings.paints[0],design:settings.designs[0]});}
function preview(){const c=$('preview').getContext('2d');c.clearRect(0,0,750,310);drawTruck(c,375,295,350,truck(settings.paints[editor],settings.designs[editor]));document.querySelectorAll('[data-paint]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.paint===settings.paints[editor])));document.querySelectorAll('[data-design]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.design===settings.designs[editor])));document.querySelectorAll('[data-track]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.track===settings.track)));document.querySelectorAll('[data-editor]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.editor===editor)));save();}
for(const [i,paint] of PAINTS.entries()){const b=document.createElement('button');b.dataset.paint=paint;b.style.setProperty('--paint',paint);b.setAttribute('aria-label',['Orange','Blue','Green','Pink','Purple','Yellow'][i]+' truck');b.onclick=()=>{settings.paints[editor]=paint;preview();};$('paints').append(b);}
for(const [i,design]of DESIGNS.entries()){const b=document.createElement('button');b.textContent=design;b.dataset.design=i;b.onclick=()=>{settings.designs[editor]=i;preview();};$('designs').append(b);}
for(const t of CIRCUITS){const b=document.createElement('button');b.dataset.track=t.id;b.textContent=t.name;const small=document.createElement('small');small.textContent='3 ramps · '+Math.round(t.length/100)/10+' km';b.append(small);b.onclick=()=>{settings.track=t.id;preview();};$('tracks').append(b);}
function clear(){inputs.forEach(i=>i.clear());document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
function setMode(m){if(running)return;room.close();mode=m;editor=0;$('room').hidden=m!=='online';$('driver-edit').hidden=m!=='split';$('start').disabled=m==='online';$('start').textContent=m==='online'?'CONNECT BOTH DEVICES':'START MY ENGINE';$('mode-note').textContent=m==='split'?'Two separate views and controls. Turn the tablet sideways for more space.':m==='online'?'Share the four-digit code with your other driver. Keep both screens awake.':'Race seven computer trucks, or explore at your own pace.';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===m)));preview();}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-editor]').forEach(b=>b.onclick=()=>{editor=+b.dataset.editor;preview();});
for(let i=0;i<2;i++){$('controls-'+i).innerHTML='<div><button data-control="left" aria-label="Player '+(i+1)+' steer left"><svg viewBox="0 0 32 32"><path d="M4 16 22 3v9h7v8h-7v9z"/></svg>LEFT</button><button data-control="right" aria-label="Player '+(i+1)+' steer right"><svg viewBox="0 0 32 32"><path d="m28 16-18-13v9H3v8h7v9z"/></svg>RIGHT</button></div><div><button data-control="brake" aria-label="Player '+(i+1)+' brake">BRAKE</button><button data-control="gas" aria-label="Player '+(i+1)+' gas">GAS</button></div>';for(const b of $('controls-'+i).querySelectorAll('button')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);inputs[i].press(e.pointerId,b.dataset.control);b.classList.add('pressed');audio.unlock();};for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{inputs[i].release(e.pointerId);b.classList.remove('pressed');});}}
function key(e,down){if(!running||/INPUT|TEXTAREA/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();inputs[mode==='split'&&e.code.startsWith('Arrow')?1:0].key(e.code,down);}if(down&&e.code==='Escape')togglePause();}
addEventListener('keydown',e=>key(e,true));addEventListener('keyup',e=>key(e,false));addEventListener('blur',()=>{clear();if(running&&mode!=='online')setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden){clear();audio.quiet();if(running&&mode!=='online')setPaused(true);else if(running&&room.host)setPaused(true);}last=0;});
function resize(){for(let i=0;i<2;i++){const r=$('screen-'+i).getBoundingClientRect();if(r.width&&r.height)renderers[i].resize(r.width,r.height,devicePixelRatio||1);}}
addEventListener('resize',resize);
function options(){return{...settings,paints:[...settings.paints],designs:[...settings.designs],players:mode==='solo'?1:2,assist:$('assist').checked,cruise:$('cruise').checked};}
function launch(config,guest=false){game=new MonsterRace(config);running=true;paused=false;networkPaused=false;finished=false;snapshotSeq=-1;remoteSeq=-1;seq=0;remoteAt=performance.now();last=0;accumulator=0;clear();$('garage').hidden=true;$('modal').hidden=true;$('screen-1').hidden=mode!=='split';document.body.classList.toggle('split',mode==='split');$('controls-0').hidden=false;$('controls-1').hidden=mode!=='split';$('pause').hidden=false;$('pause').textContent='Pause';resize();audio.unlock().then(()=>audio.engineStart());if(mode==='online'&&!guest){raceId++;room.send({type:'start',config,raceId});}}
$('start').onclick=()=>{if(mode==='online'&&(!room.joined||!room.host))return;launch(options());};
function garage(notify=true){if(notify&&mode==='online'&&room.joined){if(!room.host){room.close();$('start').disabled=true;$('start').textContent='CONNECT BOTH DEVICES';}else room.send({type:'garage'});}running=false;clear();audio.quiet();$('garage').hidden=false;$('modal').hidden=true;$('modal-body').replaceChildren();$('pause').hidden=true;document.body.classList.remove('split');$('screen-1').hidden=true;resize();}
$('garage-button').onclick=()=>garage();$('world').onclick=()=>{room.close();clear();audio.quiet();if(parent!==window)parent.postMessage({channel:'jhw-monster',type:'exit'},location.origin);else location.href='index.html';};
function setPaused(value){paused=value;clear();audio.quiet();$('pause').textContent=value?'Resume':'Pause';if(mode==='online'&&room.host)room.send({type:'pause',paused:value});}
function togglePause(){if(running)setPaused(!paused);}$('pause').onclick=togglePause;
$('sound').onclick=()=>{audio.setEnabled(!audio.enabled);audio.unlock();$('sound').textContent=audio.enabled?'Sound on':'Sound off';};
$('host').onclick=async()=>{try{await room.open();$('code').value=room.code;$('start').disabled=true;}catch(e){$('network-status').textContent=e.message;}};
$('join').onclick=async()=>{try{await room.open($('code').value.trim());$('start').disabled=true;}catch(e){$('network-status').textContent=e.message;}};
$('code').oninput=()=>{$('code').value=$('code').value.replace(/\D/g,'').slice(0,4);};
function validConfig(c){return c&&CIRCUITS.some(t=>t.id===c.track)&&c.players===2&&Array.isArray(c.paints)&&c.paints.length===2&&c.paints.every(p=>PAINTS.includes(p))&&Array.isArray(c.designs)&&c.designs.length===2&&c.designs.every(n=>Number.isInteger(n)&&n>=0&&n<3);}
function onNetwork(m){if(m.type==='connected'){$('start').disabled=!room.host;$('start').textContent=room.host?'START BOTH ENGINES':'WAITING FOR FIRST DRIVER';if(!room.host)save();return;}if(m.type==='disconnected'){clear();if(running&&!room.host){networkPaused=true;audio.quiet();$('banner-0').textContent='CONNECTION LOST';}return;}
 if(room.host){if(m.type==='design'&&PAINTS.includes(m.paint)&&Number.isInteger(m.design)&&m.design>=0&&m.design<3&&!running){settings.paints[1]=m.paint;settings.designs[1]=m.design;}if(m.type==='input'&&running&&m.raceId===raceId&&Number.isSafeInteger(m.seq)&&m.seq>remoteSeq){remoteSeq=m.seq;remoteInput=normalizeInput(m);remoteAt=performance.now();}return;}
 if(m.type==='start'&&validConfig(m.config)&&Number.isSafeInteger(m.raceId)){raceId=m.raceId;launch(m.config,true);}else if(m.type==='pause'){networkPaused=m.paused===true;}else if(m.type==='garage')garage(false);else if(m.type==='state'&&running&&m.raceId===raceId&&m.seq>snapshotSeq&&Array.isArray(m.racers)&&m.racers.length===8){if(!m.racers.every(r=>['s','x','v','heading','steer','jump'].every(k=>Number.isFinite(r[k]))))return;snapshotSeq=m.seq;remoteAt=performance.now();for(let i=0;i<8;i++)Object.assign(game.racers[i],m.racers[i]);game.phase=m.phase;game.elapsed=m.elapsed;game.countdown=m.countdown;networkPaused=m.paused===true;}}
function state(){return{type:'state',raceId,seq:++seq,phase:game.phase,elapsed:game.elapsed,countdown:game.countdown,paused,racers:game.racers.map(r=>({s:r.s,x:r.x,v:r.v,heading:r.heading,steer:r.steer,jump:r.jump,jumps:r.jumps,lap:r.lap,lapTimes:r.lapTimes,braking:r.braking,hit:r.hit,finishTime:r.finishTime}))};}
function showResults(){finished=true;audio.quiet();$('modal-title').textContent='What a ride!';const list=document.createElement('ol');for(const r of game.order()){const li=document.createElement('li');li.textContent=r.name+' · '+(r.finishTime===null?'Still racing':formatTime(r.finishTime))+' · '+r.jumps+' jumps';list.append(li);}$('modal-body').replaceChildren(list);$('modal-close').textContent='BACK TO MY GARAGE';$('modal').hidden=false;try{const key='jhw-monster-best-'+game.track.id,prior=Number(localStorage.getItem(key))||Infinity,best=game.racers[mode==='online'&&!room.host?1:0].finishTime;if(best&&best<prior)localStorage.setItem(key,String(best));}catch{}}
$('modal-close').onclick=()=>{$('modal-body').replaceChildren();$('modal').hidden=true;if(finished)garage();else setPaused(false);};
$('videos').onclick=()=>{if(running)setPaused(true);finished=false;$('modal-title').textContent='Meet the real trucks';$('modal-body').innerHTML='<p>Official Monster Jam highlights. Watch together with a grown-up.</p><div id="video-choices" class="actions"></div><div id="video-player"></div><p class="hint">YouTube playback and recommendations are controlled by YouTube.</p>';$('modal-close').textContent='BACK TO MY GARAGE';for(const [name,id]of[['Sparkle Smash','ofxeS2cIKjQ'],['Megalodon','f7LMEsxo0tA'],['Grave Digger','b5UFznClHo4']]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{const frame=document.createElement('iframe');frame.className='video-frame';frame.title=name+' · Monster Jam';frame.src='https://www.youtube-nocookie.com/embed/'+id+'?playsinline=1&rel=0';frame.allow='fullscreen; encrypted-media; picture-in-picture';frame.allowFullscreen=true;$('video-player').replaceChildren(frame);};$('video-choices').append(b);}$('modal').hidden=false;};
function loop(now){const dt=last?Math.min(.5,(now-last)/1000):0;last=now;if(running&&game){const guest=mode==='online'&&!room.host;const lost=guest&&now-remoteAt>3000;if(!paused&&!networkPaused&&!lost&&!guest&&!document.hidden){accumulator+=dt;while(accumulator>=1/60){const a=inputs[0].value(),b=mode==='split'?inputs[1].value():now-remoteAt<600?remoteInput:{gas:0,brake:1,steer:0};if(mode==='online'&&now-remoteAt>3000)game.racers[1].autopilot=true;else game.racers[1].autopilot=false;game.tick(1/60,{'truck-0':a,'truck-1':b});accumulator-=1/60;}for(const e of game.consumeEvents())audio.event(e);}if(mode==='online'&&room.joined&&now-lastSend>70){lastSend=now;if(room.host)room.send(state());else room.send({type:'input',raceId,seq:++seq,...(paused||document.hidden?{gas:0,brake:1,steer:0}:inputs[0].value())});}
 const count=mode==='split'?2:1;for(let view=0;view<count;view++){const index=guest?1:view,v=game.view(index),p=v.player;renderers[view].draw(v,now,dt);$('hud-'+view).innerHTML='<div><small>'+p.name+'</small><b>'+ordinal(v.rank)+' / 8</b></div><div><small>'+(game.cruise?'FREE DRIVE':'LAP '+p.lap+' / 3')+'</small><b>'+Math.round(p.v*2.237)+'<small> mph</small></b></div><div><small>JUMPS</small><b>'+p.jumps+'</b></div>';$('banner-'+view).textContent=lost?'RECONNECTING…':paused||networkPaused?'PIT STOP':game.phase==='countdown'?Math.max(1,Math.ceil(game.countdown)):p.finishTime!==null?'FINISH!':game.elapsed<1?'GO!':p.jump>.2?'BIG AIR!':'';}
 audio.update(game.racers[guest?1:0],!paused&&!networkPaused&&!lost&&!finished);if(!finished&&!game.cruise&&game.racers.slice(0,game.players).every(r=>r.finishTime!==null))showResults();}
 requestAnimationFrame(loop);}
preview();truckReady.then(preview);resize();requestAnimationFrame(loop);
