import {ANIMALS,SECTIONS,nextAnimal} from './data.mjs?v=1';
import {ZooAudio} from './audio.mjs?v=1';
const $=id=>document.getElementById(id),audio=new ZooAudio(),embedded=parent!==window;
const profile=['jace','halli','mommy','unique'].includes(new URLSearchParams(location.search).get('profile'))?new URLSearchParams(location.search).get('profile'):'guest';
const saveKey='jhw.zoo.passport.v1.'+profile;let visited=new Set();try{const data=JSON.parse(localStorage.getItem(saveKey)||'[]');if(Array.isArray(data))visited=new Set(data.filter(id=>ANIMALS.some(a=>a.id===id)));}catch{}
let section=null,selected=null,toastTimer;
function announce(text){$('status').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('status').textContent='',4500);}
function speak(text){if(audio.enabled&&!audio.speak(text))announce('Read-aloud is unavailable in this browser. The description is shown on the card.');}
function soundOn(){audio.unlock();$('sound').textContent='Sound on';$('sound').setAttribute('aria-pressed','true');}
function sceneImage(id){return new URL(id?'../../assets/zoo/'+id+'.webp':'../../assets/scenes/zoo-v1.webp',import.meta.url).href;}
function layout(){const v=$('viewport'),ratio=section?1.5:1672/941,w=Math.max(v.clientWidth,v.clientHeight*ratio);$('scene').style.width=w+'px';$('scene').style.height=w/ratio+'px';}
new ResizeObserver(layout).observe($('viewport'));
function save(){try{localStorage.setItem(saveKey,JSON.stringify([...visited]));}catch{}$('count').textContent=visited.size+'/30';}
function moveTo(id,read=true){audio.stop();section=SECTIONS.find(s=>s.id===id)||null;selected=null;if($('animal').open)$('animal').close();$('welcome').hidden=true;$('guide').hidden=false;document.body.classList.toggle('aquarium',Boolean(section?.water));$('scene-art').src=sceneImage(section?.id);$('scene-art').alt=section?section.name+' illustrated animal habitats':'Your approved zoo entrance';$('location').textContent=section?.name||'Zoo entrance';$('guide-line').textContent=section?.intro||'Choose a glowing sign to visit a habitat. The aquarium has two underwater galleries.';$('hotspots').replaceChildren();
 if(section){ANIMALS.filter(a=>a.section===section.id).forEach(a=>hotspot(a.name,a.x,a.y,()=>openAnimal(a.id),visited.has(a.id)));}
 else{const pos=[[18,37],[46,35],[75,30],[24,66],[58,64],[83,72]];SECTIONS.forEach((s,i)=>hotspot(s.name,...pos[i],()=>moveTo(s.id)));}
 for(const b of $('sections').children){if(b.dataset.section===section?.id)b.setAttribute('aria-current','location');else b.removeAttribute('aria-current');}
 layout();$('viewport').scrollTo({left:Math.max(0,($('scene').clientWidth-$('viewport').clientWidth)/2),top:0,behavior:'instant'});if(read)speak($('guide-line').textContent);
}
function hotspot(name,x,y,fn,found=false){const b=document.createElement('button');b.className='hotspot'+(found?' visited':'');b.textContent=name;b.style.left=x+'%';b.style.top=Math.min(88,y+13)+'%';b.onclick=fn;$('hotspots').append(b);}
function openAnimal(id){const a=ANIMALS.find(x=>x.id===id);if(!a)return;if(section?.id!==a.section)moveTo(a.section,false);audio.stop();selected=a;visited.add(a.id);save();$('animal-name').textContent=a.name;$('animal-place').textContent=SECTIONS.find(s=>s.id===a.section).name;$('description').textContent=a.description;$('diet').textContent=a.diet;$('portrait').style.backgroundImage=`url("${sceneImage(a.section)}")`;$('portrait').style.backgroundSize='300% 250%';$('portrait').style.backgroundPosition=`${Math.max(0,Math.min(100,(a.x-16.67)/66.66*100))}% ${Math.max(0,Math.min(100,(a.y-20)/60*100))}%`;$('portrait').setAttribute('aria-label','Illustration of '+a.name);$('call').textContent=['water','quiet'].includes(a.sound)?'Hear the habitat':'Hear '+a.soundLabel.toLowerCase();$('audio-note').textContent=['water','quiet'].includes(a.sound)?'Gentle habitat audio. This is not an animal voice.':'Playful sound imitation. Watch the outside video to see the real animal.';$('stop-number').textContent=(ANIMALS.indexOf(a)+1)+' / '+ANIMALS.length;if(!$('animal').open)$('animal').showModal();speak(a.name+'. '+a.description);for(const b of $('hotspots').children)if(b.textContent===a.name)b.classList.add('visited');
}
for(const s of SECTIONS){const b=document.createElement('button'),img=document.createElement('img'),span=document.createElement('span');b.dataset.section=s.id;img.src=sceneImage(s.id);img.alt='';span.textContent=s.name;b.append(img,span);b.onclick=()=>moveTo(s.id);$('sections').append(b);}
for(let i=0;i<20;i++){const b=document.createElement('i');b.style.left=(i*5)+'%';b.style.animationDelay=(-i*.8)+'s';b.style.animationDuration=(9+i%7)+'s';$('water').append(b);}
$('scene-art').onerror=()=>announce('This habitat picture could not load. Your animal buttons still work. Please try reloading.');
$('start').onclick=()=>{soundOn();moveTo('savanna',false);openAnimal(ANIMALS[0].id);};$('explore').onclick=()=>{soundOn();moveTo(null);};$('aquarium').onclick=()=>{soundOn();moveTo('reef');};$('map').onclick=()=>moveTo(null);$('next-section').onclick=()=>moveTo(SECTIONS[(SECTIONS.findIndex(s=>s.id===section?.id)+1)%SECTIONS.length].id);$('hear-guide').onclick=()=>{soundOn();speak($('guide-line').textContent);};
$('sound').onclick=()=>{if(audio.enabled){audio.mute();$('sound').textContent='Sound off';$('sound').setAttribute('aria-pressed','false');}else{soundOn();speak('Sound is on. Let us explore!');}};
$('read').onclick=()=>{soundOn();speak(selected.name+'. '+selected.description);};$('call').onclick=()=>{soundOn();audio.call(selected.sound);};
$('close-animal').onclick=()=>{$('animal').close();audio.stop();};$('animal').addEventListener('cancel',()=>audio.stop());
$('prev-animal').onclick=()=>openAnimal(nextAnimal(selected.id,-1).id);$('next-animal').onclick=()=>{if(selected===ANIMALS.at(-1)){audio.stop();$('animal').close();passport();}else openAnimal(nextAnimal(selected.id).id);};
function passport(){audio.stop();$('passport-message').textContent=visited.size===30?'You met all 30 animals! You are a zoo and aquarium explorer.':'You have met '+visited.size+' of 30 animals. Tap an animal to visit it.';$('stamps').replaceChildren();for(const a of ANIMALS){const b=document.createElement('button'),small=document.createElement('small');b.textContent=a.name;b.className=visited.has(a.id)?'found':'';small.textContent=visited.has(a.id)?'Discovered':'Visit this animal';b.append(small);b.onclick=()=>{$('passport-dialog').close();openAnimal(a.id);};$('stamps').append(b);}$('passport-dialog').showModal();}
$('passport').onclick=passport;$('close-passport').onclick=()=>$('passport-dialog').close();
$('watch').onclick=()=>{audio.stop();const a=selected;$('video-title').textContent=a.name+' — outside video';$('video-container').replaceChildren();$('source-link').href=a.video.url+(a.video.id&&a.video.start?'&t='+a.video.start+'s':'');if(a.video.id){const f=document.createElement('iframe');f.title=a.name+' video';f.src='https://www.youtube-nocookie.com/embed/'+a.video.id+'?rel=0&playsinline=1&start='+a.video.start+'&end='+a.video.end;f.allow='encrypted-media; picture-in-picture; fullscreen';f.referrerPolicy='strict-origin-when-cross-origin';$('video-container').append(f);$('video-note').textContent='A short viewing segment from the original publisher. If it cannot play here, use Open original video. The source controls ads and availability.';}else{$('video-container').textContent='Watch this animal on the source’s video page using the button below.';$('video-note').textContent='Opens another tab. Return here to keep your place in the tour. Some sources are live exhibit cameras rather than short clips.';}$('video-dialog').showModal();};
function closeVideo(){$('video-container').replaceChildren();}$('close-video').onclick=()=>{$('video-dialog').close();closeVideo();};$('video-dialog').addEventListener('close',closeVideo);
$('source-link').onclick=()=>audio.stop();
$('exit').onclick=()=>{audio.stop();if(embedded)parent.postMessage({channel:'jhw-zoo',type:'exit'},location.origin);else location.href='index.html';};
window.addEventListener('pagehide',()=>audio.stop());document.addEventListener('visibilitychange',()=>{if(document.hidden){audio.stop();closeVideo();}});save();layout();

if(embedded)parent.postMessage({channel:'jhw-zoo',type:'active'},location.origin);
