import {ASSETS,DESTINATIONS,WORDS,BOOK,LESSON} from './data.mjs?v=train-1';
import {TrainAudio} from './audio.mjs?v=train-1';
import {createTrip,tickTrip} from './engine.mjs?v=train-1';
import {TrainRenderer} from './render.mjs?v=train-1';
const $=id=>document.getElementById(id),stage=$('stage'),audio=new TrainAudio(),embedded=parent!==window;
const requested=new URLSearchParams(location.search).get('profile')?.replace('family.','');
let profile=['jace','halli'].includes(requested)?requested:'jace',destination=DESTINATIONS[0],intent='ride',screen='station',coins=new Set(),trip=null,renderer=null,raf=0,last=0,input={gas:false,brake:false},paused=false,autoBook=false,page=0,lesson=0,guide='',gentle=matchMedia('(prefers-reduced-motion: reduce)').matches,announced=new Set(),lastTick=0;
const art=(name,alt='',cls='scene-art')=>`<img class="${cls}" src="${ASSETS}${name}.webp" alt="${alt}" draggable="false">`;
const btn=(act,label,cls='',extra='')=>`<button data-act="${act}" class="${cls}" ${extra}>${label}</button>`;
const storage=()=>`jhw.train.v1.${profile}`;
function loadProgress(){try{const p=JSON.parse(localStorage.getItem(storage())||'{}');return {stamps:Array.isArray(p.stamps)?p.stamps.filter(id=>DESTINATIONS.some(d=>d.id===id)):[],page:Number.isInteger(p.page)?Math.min(9,Math.max(0,p.page)):0};}catch{return {stamps:[],page:0};}}
function saveProgress(update){try{localStorage.setItem(storage(),JSON.stringify({...loadProgress(),...update}));}catch{}}
function cue(text,speak=true,done){guide=text;$('cue').textContent=text;if(speak)audio.say(text,done);}
function setScreen(name,html){cancelAnimationFrame(raf);renderer?.destroy();renderer=null;input={gas:false,brake:false};audio.stop();screen=name;stage.innerHTML=html;stage.dataset.screen=name;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===(name==='book'?'story':name==='learn'||name==='lesson'?'learn':name==='ride'?'drive':'station')));window.scrollTo({top:0,behavior:'instant'});}
function station(read=false){autoBook=false;trip=null;const stamps=loadProgress().stamps;setScreen('station',`<section class="scene welcome">${art('station','A blue and pink train waits at Jace and Halli’s beautiful station.')}<div class="intro"><div class="eyebrow">Little explorers • big journeys</div><h1>Your next<br>adventure<br>starts here.</h1><p>A ticket, a window seat, and a whole wonderful world to discover.</p><div class="profiles" aria-label="Choose your explorer">${['jace','halli'].map(p=>btn('profile',`<strong>${p==='jace'?'Jace':'Halli'}</strong><small>${p==='jace'?'Little engineer':'Bubble express'}</small>`,profile===p?'selected':'',`data-profile="${p}" aria-pressed="${profile===p}"`)).join('')}</div><div class="cta">${btn('choose','Let’s buy a ticket →','primary')}${btn('drive','I want to drive','gold')}</div></div><div class="station-note">${stamps.length?`${stamps.length} of 4 destinations visited`:'Four destinations. So much to discover.'}<br>${profile==='halli'?'Halli’s train makes bubbles!':'All aboard, little engineer.'}</div></section>`);cue(profile==='halli'?'Hello, Halli! Your train makes bubbles. Tap the pink button to buy a ticket.':'Hello, Jace! Let’s ride a train. Tap the pink button to buy a ticket, or choose I want to drive.',read);}
function choose(mode=intent){intent=mode;autoBook=false;trip=null;setScreen('choose',`<section class="scene destination-scene">${art('station','')}<header class="section-heading"><div class="eyebrow">01 / Plan our trip</div><h2>Where shall we go?</h2><p>Choose a picture. Your adventure is waiting.</p></header><div class="destinations">${DESTINATIONS.map(d=>`<button class="destination" data-act="destination" data-destination="${d.id}" aria-label="Travel to the ${d.name}">${art(d.image,'','destination-art')}<strong>${d.name}</strong><small>${loadProgress().stamps.includes(d.id)?'Visited • ride again':'Take the '+(profile==='halli'?'bubble ':'')+'express'}</small></button>`).join('')}</div></section>`);cue('Where would you like to go? The zoo, the park, the city, or the beach? Tap a picture.');}
function ticket(){coins=new Set();setScreen('ticket',`<section class="scene panel-scene">${art('tickets','A ticket window with a ticket printer and play coins.')}<div class="scene-panel"><div class="eyebrow">02 / Ticket window</div><h2>One ticket to the ${destination.name.toLowerCase()}, please!</h2><p>Tap three pretend coins to pay for your trip.</p><div class="coins">${[1,2,3].map(n=>btn('coin',n,'coin',`data-coin="${n}" aria-label="Pay pretend coin ${n}"`)).join('')}</div><p id="coin-count" class="count">0 of 3 coins</p>${btn('print','Print my ticket','primary wide','id="print-ticket" disabled')}<p><small>Play coins · no real money</small></p></div></section>`);cue(`One ticket to the ${destination.name.toLowerCase()}, please. Tap the three gold coins. Let’s count!`);}
function printedTicket(){audio.ding();setScreen('printed',`<section class="scene panel-scene">${art('tickets')}<div class="scene-panel"><div class="eyebrow">Your ticket is ready</div><h2>Here you go, ${profile==='halli'?'Halli':'Jace'}!</h2><div class="ticket"><span>JACE & HALLI’S EXPRESS</span><strong>${destination.name}</strong><small>One little explorer + grown-up</small><small>Platform 1 · Window seat</small></div>${btn('platform','Go to the platform →','primary wide')}</div></section>`);cue(`Here is your ticket to the ${destination.name.toLowerCase()}! Keep it safe. Say, thank you! Now let’s go to the platform.`);}
function platform(){setScreen('platform',`<section class="scene panel-scene">${art('station','The train is stopped safely beside the platform.')}<div class="scene-panel boarding-panel"><div class="eyebrow">03 / Platform 1</div><h2>Our train is here!</h2><p>Stay with Mommy behind the line. Let everyone off first.</p>${btn('board','Show my ticket & board','primary wide')}</div></section>`);cue('Wait with Mommy behind the line. Our train has stopped. Let people get off first. Now show your ticket and walk onto the train with Mommy. Watch the little gap.');}
function board(){setScreen('board',`<section class="scene panel-scene">${art('family-carriage','Your approved illustration of Jace and Halli sitting beside Mommy on the train.')}<div class="scene-panel boarding-panel"><div class="eyebrow">04 / All aboard</div><h2>A window seat for you.</h2><p>Our next stop is the ${destination.name.toLowerCase()}. Ready?</p><div class="choice-buttons">${btn('ride-start','Sit & enjoy the ride','primary')}${btn('drive-start','Drive our pretend train','gold')}</div></div></section>`);cue('You’re on the train! Sit beside Mommy. Keep your feet down. Choose a window ride, or drive our pretend train.');}
function startRide(mode){intent=mode;trip=createTrip(destination,mode,profile==='halli');announced=new Set();paused=false;setScreen('ride',`<section class="ride"><canvas id="ride-canvas" class="ride-canvas" aria-label="Moving train scenery. Halli can tap floating bubbles to pop them."></canvas><div class="journey-hud"><div class="journey-info"><small>${profile==='halli'?'Halli’s bubble express':'Jace & Halli’s express'}</small><strong>Next stop: ${destination.name}</strong><progress id="progress" value="0" max="${trip.length}" aria-label="Journey progress"></progress></div><div class="speed"><b id="speed">0</b><span>SPEED</span></div></div><div class="word-tray">${(profile==='halli'?['Train','Tracks','Bubble']:['Train','Tracks']).map(word=>btn('word',word,'',`data-word="${word}"`)).join('')}</div><div class="driver-controls">${mode==='drive'?'<button id="go" class="pedal go" aria-label="Hold to move the train">▶ GO</button><button id="brake" class="pedal brake" aria-label="Hold to brake">■ STOP</button>':''}${btn('horn','Sound the horn')}${btn('view','Window view','', 'id="view-button"')}${btn('pause','Pause','', 'id="pause-button"')}${mode==='ride'?btn('take-over','I want to drive'):''}</div><div class="ride-paused" id="pause-cover" hidden><h2>A little station break</h2><p>Your train is waiting for you.</p>${btn('resume','Let’s keep going','primary')}</div></section>`);
 renderer=new TrainRenderer($('ride-canvas'),()=>{if(paused)return;trip.bubbles++;audio.pop();if(trip.bubbles===1)cue('Pop! You popped a bubble!');});renderer.gentle=gentle;
 for(const [id,key] of [['go','gas'],['brake','brake']]){const b=$(id);if(!b)continue;b.onpointerdown=e=>{e.preventDefault();audio.unlock();if(paused)return;input[key]=true;b.classList.add('held');b.setPointerCapture(e.pointerId);};const release=()=>{input[key]=false;b.classList.remove('held');};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;}
 cue(mode==='ride'?'All aboard! Sit back and watch the world roll by. Tap the horn, or try the window view.':profile==='halli'?'Halli, hold the green go button! Your train makes bubbles. Tap a bubble to pop it. I will help you stop.':'Hold the green go button to drive. Let go to slow down. Hold the red stop button at the signal and the station.');last=performance.now();lastTick=0;raf=requestAnimationFrame(frame);}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!paused){tickTrip(trip,input,dt);renderer.draw(trip,destination,dt);if(now-lastTick>120){$('speed').textContent=Math.round(trip.speed);$('progress').value=trip.distance;lastTick=now;}const remaining=trip.length-trip.distance;const signalGap=trip.signalAt-trip.distance;if(signalGap<200&&!trip.signalClear&&!announced.has('signal')){announced.add('signal');cue(trip.halli||trip.mode==='ride'?'A red signal. Our train will stop and wait.':'Red signal ahead! Let go of go and hold the red stop button.');}if(trip.atRed&&!announced.has('red')){announced.add('red');cue('Stop. We are waiting for the green signal.');}if(trip.signalClear&&!announced.has('green')){announced.add('green');audio.ding();cue('The signal is green. We can go!');}if(remaining<300&&!announced.has('station')){announced.add('station');cue(trip.halli||trip.mode==='ride'?'Here comes our station. We are slowing down.':'Our station is coming! Hold the red stop button for a gentle stop.');}if(trip.arrived){arrival();return;}}
 raf=requestAnimationFrame(frame);}
function arrival(){const finished={...trip};saveProgress({stamps:[...new Set([...loadProgress().stamps,destination.id])]});setScreen('arrival',`<section class="scene panel-scene">${art(destination.image,destination.name+' destination')}<div class="scene-panel arrival-panel"><div class="eyebrow">A wonderful journey</div><div class="stamp">EXPLORER<br>${destination.name.toUpperCase()}</div><h2>We made it!</h2><p>${destination.greeting}</p><p>${finished.halli?`${finished.bubbles} bubbles popped · `:''}Your ${destination.name} stamp is saved.</p><div class="choice-buttons">${btn('choose','Choose our next stop','primary')}${btn('story','Our train story','gold')}${destination.link?btn('visit','Visit the '+destination.name):btn('word','Say water','', 'data-word="Water"')}</div></div></section>`);audio.ding();cue(destination.greeting+' Wait until the train has stopped. Then walk off with Mommy. Well done, little explorer!');}
function pauseRide(value){paused=value;input={gas:false,brake:false};$('go')?.classList.remove('held');$('brake')?.classList.remove('held');$('pause-cover').hidden=!paused;$('pause-button').textContent=paused?'Resume':'Pause';if(paused)audio.stop();else cue(trip.mode==='ride'?'Let’s keep going.':'Ready? Hold go when you want to move.');}
function word(w){const item=WORDS.find(x=>x[0]===w);const line=item?.[1]||`Can you say, ${w}?`;cue(line,true,()=>{if(profile==='halli'){$('cue').textContent=`Your turn, Halli… “${w}”`;audio.later(()=>{$('cue').textContent=`Say it again: ${w}!`;audio.say(w+'. '+w+'. Good trying!');},3200);}});}
function showBook(index=loadProgress().page,read=true){page=Math.min(9,Math.max(0,index));saveProgress({page});const p=BOOK[page];setScreen('book',`<section class="book"><div class="book-top"><span>Jace & Halli’s storytime</span><strong>The Little Bubble Express</strong></div><article class="book-spread"><div class="book-picture">${art(p.image,p.title,'')}</div><div class="book-copy"><div class="eyebrow">Chapter of wonder · ${String(page+1).padStart(2,'0')}</div><h2>${p.title}</h2><p>${p.text}</p><p class="story-prompt">${p.prompt}</p>${btn('word','Say it: '+p.word,'word',`data-word="${p.word}"`)}</div></article><div class="book-controls">${btn('prev-page','← Back','',page===0?'disabled':'')}<div class="listen">${btn('read-page','Read to me')}${btn('auto-book',autoBook?'Pause story':'Read all pages','gold','id="auto-book"')}</div>${btn(page===9?'finish-book':'next-page',page===9?'The end →':'Next →','primary')}</div><div class="page-dots" aria-label="Choose a story page">${BOOK.map((_,i)=>btn('page','',i===page?'active':'',`data-page="${i}" aria-label="Story page ${i+1}" ${page===i?'aria-current="page"':''}`)).join('')}</div></section>`);cue(`Page ${page+1} of 10. ${p.title}. ${p.text} ${p.prompt}`,read,()=>{if(autoBook&&page<9)audio.later(()=>showBook(page+1,true),4000);else if(page===9){autoBook=false;if($('auto-book'))$('auto-book').textContent='Read all pages';}});}
function learn(){autoBook=false;setScreen('learn',`<section class="scene destination-scene">${art('night')}<header class="section-heading"><div class="eyebrow">Little things to learn</div><h2>Let’s learn about trains.</h2><p>Listen, point, and say it with us.</p></header><div class="learn-grid"><article class="learning-card">${art('tickets','A station ticket window','')}<div class="copy"><h3>My first train trip</h3><p>Five little steps: choose, buy a ticket, wait, board, and ride.</p>${btn('lesson','Show me how','primary')}</div></article><article class="learning-card">${art('bubble-bridge','A bubble-making train crosses a bridge','')}<div class="copy"><h3>Trains with Blippi</h3><p>A bright, musical introduction to trains. 4 minutes 24 seconds.</p>${btn('video','Watch the train video','gold')}</div><div class="word-grid">${WORDS.map(([w])=>btn('word',w,'',`data-word="${w}"`)).join('')}</div></article></div></section>`);cue('Let’s learn about train trips. Tap Show me how, watch Blippi’s train video, or tap a word to say it with me.');}
function showLesson(index=0){lesson=index;const p=LESSON[lesson];setScreen('lesson',`<section class="scene panel-scene">${art(p.image,p.title)}<div class="scene-panel"><div class="eyebrow">My first train trip · ${lesson+1} of 5</div><h2>${p.title}</h2><p>${p.line}</p><div class="choice-buttons">${btn('lesson-prev','← Back','',lesson===0?'disabled':'')}${btn(lesson===4?'choose':'lesson-next',lesson===4?'Try my own trip':'Next step →','primary')}</div></div></section>`);cue(p.line);}
function openVideo(){audio.stop();if(trip&&screen==='ride')pauseRide(true);const iframe=document.createElement('iframe');iframe.title='Trains for Children — Fun Train Song by Blippi';iframe.src='https://www.youtube-nocookie.com/embed/xzWLoGdx3DE?rel=0&playsinline=1&end=264';iframe.allow='autoplay; encrypted-media; picture-in-picture; fullscreen';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;$('player').replaceChildren(iframe);$('video').showModal();}
function nav(where){autoBook=false;if(where==='story')showBook();else if(where==='learn')learn();else if(where==='drive')choose('drive');else station(true);}
function exit(){audio.stop();cancelAnimationFrame(raf);if(embedded)parent.postMessage({channel:'jhw-train',type:'exit'},location.origin);else location.href='index.html';}
function visit(){if(!destination.link)return;audio.stop();if(embedded)parent.postMessage({channel:'jhw-train',type:'visit',destination:destination.id},location.origin);else location.href=destination.link;}
stage.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b||b.disabled)return;audio.unlock();const action=b.dataset.act;
 if(action==='profile'){profile=b.dataset.profile;station(true);}else if(action==='choose')choose('ride');else if(action==='drive')choose('drive');else if(action==='destination'){destination=DESTINATIONS.find(d=>d.id===b.dataset.destination);ticket();}else if(action==='coin'){const n=Number(b.dataset.coin);if(coins.has(n))return;coins.add(n);b.disabled=true;$('coin-count').textContent=coins.size+' of 3 coins';$('print-ticket').disabled=coins.size!==3;audio.ding();cue(coins.size===3?'Three! You paid three pretend coins. Now print your ticket.':['','One!','Two!'][coins.size]);}else if(action==='print'&&coins.size===3)printedTicket();else if(action==='platform')platform();else if(action==='board')board();else if(action==='ride-start')startRide('ride');else if(action==='drive-start')startRide('drive');else if(action==='horn'){trip.horns++;audio.horn();}else if(action==='view'){renderer.windowView=!renderer.windowView;b.textContent=renderer.windowView?'See our train':'Window view';b.classList.toggle('active',renderer.windowView);cue(renderer.windowView?'Look out of our window. What can you see?':'Look at our train rolling along the tracks.');}else if(action==='pause')pauseRide(!paused);else if(action==='resume')pauseRide(false);else if(action==='take-over'){const saved={...trip};startRide('drive');Object.assign(trip,saved,{mode:'drive'});}else if(action==='word')word(b.dataset.word);else if(action==='story')showBook();else if(action==='prev-page')showBook(page-1);else if(action==='next-page')showBook(page+1);else if(action==='page')showBook(Number(b.dataset.page));else if(action==='read-page')showBook(page);else if(action==='auto-book'){autoBook=!autoBook;if(autoBook){if(!audio.enabled){audio.enabled=true;updateSound();}showBook(page===9?0:page);}else{audio.stop();b.textContent='Read all pages';cue('Story paused. Tap Read to me whenever you’re ready.',false);}}else if(action==='finish-book'){station();cue('The end! You listened to all ten pages. Bye-bye, little bubble train.');}else if(action==='lesson')showLesson();else if(action==='lesson-prev')showLesson(lesson-1);else if(action==='lesson-next')showLesson(lesson+1);else if(action==='video')openVideo();else if(action==='visit')visit();else if(action==='beach-look')cue('Listen with your imagination. Swish, swish, swish. The waves are washing the sand. Can you make a gentle wave sound?');});
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{audio.unlock();nav(b.dataset.nav);});document.querySelector('.brand').onclick=e=>{e.preventDefault();station(true);};$('repeat').onclick=()=>{audio.unlock();audio.say(guide);};$('exit').onclick=exit;
function updateSound(){$('sound').textContent=audio.enabled?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(audio.enabled));$('sound').setAttribute('aria-label',audio.enabled?'Turn sound off':'Turn sound on');}
$('sound').onclick=()=>{audio.enabled=!audio.enabled;updateSound();if(audio.enabled){audio.unlock();audio.say(guide);}else{autoBook=false;audio.stop();if($('auto-book'))$('auto-book').textContent='Read all pages';}};
function voices(){const all=window.speechSynthesis?.getVoices()||[];const select=$('voice'),chosen=audio.voiceName;select.replaceChildren();select.add(new Option('Warm English voice (automatic)',''));for(const v of all.filter(v=>v.lang.startsWith('en')))select.add(new Option(v.name,v.name));select.value=chosen;$('voice-status').textContent=window.speechSynthesis?'Voice choices depend on this device.':'This browser does not offer narration. Instructions stay visible.';}
window.speechSynthesis?.addEventListener('voiceschanged',voices);$('grownup').onclick=()=>{audio.stop();if(screen==='ride')pauseRide(true);voices();$('preferences').showModal();};$('voice').onchange=e=>{audio.voiceName=e.target.value;audio.say('All aboard, little explorer. Let’s ride a train!');};$('motion').checked=gentle;$('motion').onchange=e=>{gentle=e.target.checked;document.body.classList.toggle('gentle',gentle);if(renderer)renderer.gentle=gentle;};$('close-video').onclick=()=>$('video').close();$('video').addEventListener('close',()=>$('player').replaceChildren());
window.addEventListener('keydown',e=>{if(screen!=='ride'||paused||e.target.matches('input,select,textarea'))return;if(['ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(e.key==='ArrowUp')input.gas=true;if(e.key==='ArrowDown'||e.key===' ')input.brake=true;});window.addEventListener('keyup',e=>{if(e.key==='ArrowUp')input.gas=false;if(e.key==='ArrowDown'||e.key===' ')input.brake=false;});
function suspend(){audio.stop();autoBook=false;if(screen==='ride')pauseRide(true);$('player').replaceChildren();if($('auto-book'))$('auto-book').textContent='Read all pages';}
window.addEventListener('blur',()=>{input={gas:false,brake:false};});document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',()=>{audio.stop();cancelAnimationFrame(raf);});
window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;if(e.data?.channel==='jhw-train'&&e.data.type==='pause')suspend();});
station();voices();if(embedded)parent.postMessage({channel:'jhw-train',type:'active'},location.origin);
