import {ASSETS} from './data.mjs';
export class TrainRenderer{
 constructor(canvas,onPop){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.onPop=onPop;this.images={};this.bubbles=[];this.clock=0;this.lastBubble=0;this.windowView=false;this.gentle=false;this.width=1;this.height=1;this.resize=new ResizeObserver(()=>this.size());this.resize.observe(canvas);this.size();for(const name of ['panorama','engine','station','zoo','park','city','beach']){const im=new Image();im.src=ASSETS+name+'.webp';this.images[name]=im;}this.tap=e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;for(let i=this.bubbles.length-1;i>=0;i--){const b=this.bubbles[i];if(Math.hypot(x-b.x,y-b.y)<Math.max(28,b.r+8)){this.bubbles.splice(i,1);this.onPop();return;}}};canvas.addEventListener('pointerdown',this.tap);}
 size(){const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);this.width=r.width;this.height=r.height;this.canvas.width=Math.round(r.width*d);this.canvas.height=Math.round(r.height*d);this.ctx.setTransform(d,0,0,d,0,0);}
 cover(im,x,y,w,h){if(!im?.complete||!im.naturalWidth)return;const scale=Math.max(w/im.width,h/im.height),iw=im.width*scale,ih=im.height*scale;this.ctx.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih);}
 round(x,y,w,h,r,fill){const c=this.ctx;c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();}
 draw(s,destination,dt){const c=this.ctx,w=this.width,h=this.height;this.clock+=dt;const im=this.images.panorama;c.fillStyle='#bddff0';c.fillRect(0,0,w,h);
 if(im.complete&&im.naturalWidth){const scale=Math.max(h/im.height,w/im.width),pw=im.width*scale,ph=im.height*scale,offset=(s.distance*(this.gentle?.25:.7))%pw;c.drawImage(im,-offset,0,pw,ph);c.drawImage(im,pw-offset,0,pw,ph);}
 if(s.distance>s.length-450){c.save();c.globalAlpha=Math.min(.92,(s.distance-s.length+450)/450);this.cover(this.images[destination.image],0,0,w,h);c.restore();}
 if(this.windowView){const frame=c.createLinearGradient(0,0,0,h);frame.addColorStop(0,'#bb7738');frame.addColorStop(.5,'#684325');frame.addColorStop(1,'#dba562');c.strokeStyle=frame;c.lineWidth=28;c.strokeRect(0,0,w,h);c.strokeStyle='#e8bd73';c.lineWidth=4;c.strokeRect(15,15,w-30,h-30);c.fillStyle='#09213588';c.fillRect(w*.485,0,w*.025,h);if(s.halli)this.drawBubbles(s,dt,w*.75,h*.8);return;}
 const ground=h*.87;c.fillStyle='#4b4e42';c.fillRect(0,ground,w,h-ground);const ballast=c.createLinearGradient(0,ground,0,h);ballast.addColorStop(0,'#b3a88e');ballast.addColorStop(1,'#665e52');c.fillStyle=ballast;c.fillRect(0,ground,w,24);
 const scroll=s.distance*3;for(let x=-45-(scroll%45);x<w+45;x+=45){c.fillStyle='#4b3326';c.fillRect(x,ground+3,23,17);c.fillStyle='#997052';c.fillRect(x,ground+2,23,4);}for(const y of [ground+3,ground+17]){c.fillStyle='#273f4b';c.fillRect(0,y,w,5);c.fillStyle='#ced7d7';c.fillRect(0,y,w,2);}
 const engine=this.images.engine;let tw=Math.min(w*.77,h*1.38),th=engine.naturalWidth?tw*engine.height/engine.width:tw*.5,tx=w*.05,ty=ground-th*.866;const sway=this.gentle?0:Math.sin(this.clock*12)*Math.min(1.3,s.speed/32);
 c.save();c.translate(tx,ty+sway);if(engine.complete&&engine.naturalWidth){c.save();c.shadowColor='#06131999';c.shadowBlur=12;c.shadowOffsetY=8;c.drawImage(engine,0,0,tw,th);c.restore();for(const [x,y] of [[.100,.764],[.366,.764],[.591,.748],[.709,.748],[.827,.747]]){const r=tw*.038;c.save();c.beginPath();c.arc(x*tw,y*th,r,0,Math.PI*2);c.clip();c.translate(x*tw,y*th);c.rotate(s.distance*.07);c.drawImage(engine,-x*tw,-y*th,tw,th);c.restore();}}c.restore();
 const funnelX=tx+tw*.86,funnelY=ty+th*.16;
 if(s.halli)this.drawBubbles(s,dt,funnelX,funnelY);else if(s.speed>0)for(let i=0;i<5;i++){const age=(this.clock*.5+i*.2)%1;c.globalAlpha=(1-age)*.2;c.fillStyle='#fff7e7';c.beginPath();c.arc(funnelX-age*95,funnelY-age*90,9+age*28,0,Math.PI*2);c.fill();c.globalAlpha=1;}
 const signalX=tx+tw*.92+(s.signalAt-s.distance)*1.3;if(signalX>-100&&signalX<w+100){c.fillStyle='#1c3540';c.fillRect(signalX-6,ground-h*.35,12,h*.35);this.round(signalX-23,ground-h*.44,46,75,20,'#153343');for(let i=0;i<2;i++){c.beginPath();c.arc(signalX,ground-h*.44+22+i*31,13,0,Math.PI*2);c.fillStyle=i===0?(!s.signalClear?'#ff645c':'#573b40'):(s.signalClear?'#71ed9b':'#284942');c.shadowColor=c.fillStyle;c.shadowBlur=12;c.fill();c.shadowBlur=0;}}
 if(s.length-s.distance<280){const x=tx+tw*.92+(s.length-s.distance)*1.3;c.fillStyle='#eedfc1';c.fillRect(x,ground-7,400,40);c.fillStyle='#efbb56';c.fillRect(x,ground-7,400,7);this.round(x+14,ground-90,160,44,7,'#17394a');c.fillStyle='#fff7e1';c.font='bold 17px system-ui';c.textAlign='center';c.fillText(destination.name+' station',x+94,ground-62);}
 }
 drawBubbles(s,dt,x,y){const c=this.ctx;if(this.clock-this.lastBubble>.65&&this.bubbles.length<16){this.bubbles.push({x,y,r:16+Math.random()*15,age:0,vx:-15-Math.random()*25});this.lastBubble=this.clock;}for(const b of this.bubbles){b.age+=dt;b.x+=b.vx*dt;b.y-=dt*(18+b.r*.45);c.save();c.globalAlpha=Math.max(0,1-b.age/7);const fill=c.createRadialGradient(b.x-b.r*.35,b.y-b.r*.35,0,b.x,b.y,b.r);fill.addColorStop(0,'#ffffffaa');fill.addColorStop(.65,'#97e5ff20');fill.addColorStop(.9,'#e7bafa99');fill.addColorStop(1,'#fcf3caaa');c.fillStyle=fill;c.strokeStyle='#faffffb0';c.lineWidth=2;c.beginPath();c.arc(b.x,b.y,b.r,0,Math.PI*2);c.fill();c.stroke();c.beginPath();c.strokeStyle='#fff';c.lineWidth=3;c.arc(b.x,b.y,b.r*.72,Math.PI*1.1,Math.PI*1.45);c.stroke();c.restore();}this.bubbles=this.bubbles.filter(b=>b.age<7&&b.y>-40);}
 destroy(){this.resize.disconnect();this.canvas.removeEventListener('pointerdown',this.tap);}
}
