import {ParkSession,GAMES} from './session.mjs?v=arcade-2';
import {ParkScene} from './scene.mjs?v=arcade-2';
import {ActivityCanvas as CanvasScene} from './activity-canvas.mjs?v=arcade-2';
const $=id=>document.getElementById(id),game=Object.hasOwn(GAMES,location.hash.slice(1))?location.hash.slice(1):'basketball',embedded=parent!==window;
const HELP={basketball:'One-on-one basketball. Drag to dribble or defend. Player 1 attacks the right hoop; Player 2 attacks the left. Shoot when you have the ball, jump to block when you don’t. Get close to steal. First to 11 wins.',softball:'Player 1 bats, Player 2 pitches. Watch the yellow ball reach the plate, then swing. Drag to aim or move the selected fielder. Throw to a base for an out. Three outs switches sides. One inning, with extra innings if tied.',fishing:'Drag left or right to choose your spot on the pier. Cast and wait for BITE! Tap Hook quickly. Hold Reel to bring the fish in, but release before the tension reaches 100%. Catch five fish together.',seesaw:'Each player sits at one end. Tap Pump when your seat is low. Take turns pushing to fill the meter and earn five stars together.',hide:'A new round gives hiders twelve seconds to move into the meadow. Drag to move. Tap Hide near a barrel, bush, hay bale or hut. Moving makes you come out. The seeker counts with a covered screen, then has sixty seconds to look. Move close and tap Search. Roles switch each round.',swim:'Drag to swim through the gold rings. Go under for a bubbly underwater dip, swim a circle, or visit the diving board at the near end and tap Dive. Collect eight rings together.',cook:'Pick up each recipe ingredient at the refrigerator, then carry it to the mixing counter. Stir, roll or chop six times. At the stove, cook and turn the food halfway through, then carry the plate to the serving table. Work together! Fruit salad does not need heating.'};
document.body.dataset.game=game;$('title').textContent=GAMES[game];$('help-title').textContent=GAMES[game];$('help-text').textContent=HELP[game];$('help').onclick=()=>$('instructions').showModal();$('close-help').onclick=()=>$('instructions').close();
let receivedAt=performance.now();const renderedPositions=new Map();
let id='',state=null,local=null,scene=null,last=performance.now(),controlKey='',reeling=false,move={x:0,z:0},pointer=null,origin=null,connected=false;
function send(body){if(!connected)return;if(local){try{const result=local.request({id},body);if(result.game)receive(result);}catch(e){$('message').textContent=e.message;}}else parent.postMessage({channel:'jhw-playpark',type:'command',body},location.origin);}
function receive(s){if(!id||!s?.game||s.game!==game||!s.members?.some(member=>member.id===id))return;state=s;receivedAt=performance.now();connected=true;$('loading').hidden=true;renderHUD();}
addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin||e.data?.channel!=='jhw-playpark')return;const d=e.data;if(d.type==='context'){id=d.id;receive(d.state);}if(d.type==='state')receive(d.state);if(d.type==='error'){$('message').textContent=d.error;if(!connected)$('loading').textContent=d.error+' Close this activity and choose another, or wait for a seat.';}if(d.type==='lost'){connected=false;$('loading').hidden=false;$('loading').textContent='The family room disconnected. Return to town and rejoin.';}});
function action(name){playSound(name);$('message').textContent='';send({op:'action',name,pitchId:state?.state.pitch?.id,pitchT:state?.state.pitch?.t});}
function buttons(items){const key=JSON.stringify(items);if(key===controlKey)return;controlKey=key;$('controls').replaceChildren();for(const [label,name]of items){const b=document.createElement('button');b.textContent=label;if(name==='reel'){b.className='reel';b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);reeling=true;send({op:'reel',down:true});};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{reeling=false;send({op:'reel',down:false});};}else b.onclick=()=>action(name);$('controls').append(b);}}
function renderHUD(){const s=state.state,p=state.members.find(m=>m.id===id),side=state.side,other=state.members.find(m=>m.id!==id);$('members').textContent=state.members.map(m=>m.name).join(' + ')+(local?' · practice':other?' · shared room':' · waiting for family');$('banner').textContent=s.message||'';let score='',items=[];$('countdown').hidden=true;
 if(game==='basketball'){score=state.members[0].name+' '+s.scores[0]+' : '+s.scores[1]+' '+(state.members[1]?.name||'Computer');items=s.finished?[['Play again','restart']]:[[s.basket.owner===side?'Shoot':'Jump / block','primary'],['Steal','secondary']];}
 if(game==='softball'){score=`${s.scores[0]} : ${s.scores[1]} · Inning ${s.inning} · ${s.outs} outs · ${s.balls} balls / ${s.strikes} strikes`;items=s.finished?[['Play again','restart']]:side===s.batting?[['Swing','swing'],['Contact / power','style'],['Run next base','advance'],['Hold','hold']]:[['Pitch','pitch'],['Fast','kind-fast'],['Changeup','kind-change'],['Drop','kind-drop'],['Switch fielder','switch'],['1st','throw-1'],['2nd','throw-2'],['3rd','throw-3'],['Home','throw-4']];}
 if(game==='fishing'){const f=p.fish;score=`Family catch: ${s.caught} / 5`;const desc={ready:'Choose your spot, then cast.',cast:'Casting…',waiting:'Wait for a bite…',bite:'BITE! Tap Hook!',fight:`Reel progress ${Math.round(f.progress*100)}% · Tension ${Math.round(f.tension*100)}% — ${f.tension>.7?'RELEASE!':'hold to reel'}`,caught:`You caught a ${f.species}!`,miss:'The fish got away. Try another cast.'};$('banner').textContent=desc[f.phase];items=['ready','miss','caught'].includes(f.phase)?[['Cast','cast']]:f.phase==='fight'?[['Hold to reel','reel']]:[['Hook','hook']];}
 if(game==='seesaw'){score=`${s.stars} / 5 stars · Push meter ${Math.round(s.energy*100)}%`;items=[['Pump!','pump']];}
 if(game==='hide'){const seeker=state.members.find(m=>m.id===s.seeker);score=s.phase==='waiting'?(state.members.length>=2?'Ready — start a round!':'Waiting for a second player'):`${seeker?.name||'Friend'} is seeking · ${Math.max(0,Math.ceil(s.left))}s`;if(s.phase==='waiting'&&state.members.length>=2)$('banner').textContent='Everyone is here. Tap Start round!';items=['waiting','done'].includes(s.phase)?[['Start round','start']]:p.id===s.seeker?[['Search here','search']]:[[p.hidden!==null?'Come out':'Hide here','hide']];if(s.phase==='hiding'&&p.id===s.seeker){$('countdown').hidden=false;$('countdown').textContent=`Close your eyes…\n${Math.ceil(s.left)}\nYour friends are hiding!`;}if(p.found)$('banner').textContent='You were found! Watch until the next round.';else if(p.hidden!==null)$('banner').textContent='You are hidden. Moving or tapping Come out reveals you.';}
 if(game==='swim'){score=`Rings together: ${s.score} / 8`;items=[[p.mode==='under'?'Come up':'Go under','under'],['Dive from board','dive'],['Swim in circles','circle']];if(!s.rings.length)items.push(['More rings','restart']);}
 if(game==='cook'){
  score=`${state.recipe[0]} · ${s.served} meals served`;
  if(s.step<3){$('banner').textContent=p.carry?'Carrying '+p.carry+' — bring it to the mixing counter':'Recipe: '+state.recipe[1][s.step]+' — collect it at the refrigerator';items=p.carry?[['Add to bowl','work'],['Put ingredient down','put-down']]:state.recipe[1].map((name,i)=>[name,'ingredient-'+i]);}
  else if(s.step===3){const verb=s.recipe===2?'Chop':s.recipe===1?'Roll':'Stir';$('banner').textContent=`Mixing counter: ${verb.toLowerCase()} ${s.work} / 6`;items=[[verb+' together','work']];}
  else if(s.step===4){const ready=s.recipe===2||(s.heat>=5&&s.flipped),turn=s.heat>=2.5&&!s.flipped;$('banner').textContent=ready?'Ready! Plate the food at the stove.':turn?'Turn the food so both sides cook.':s.heat>0?'Cooking… watch it turn golden.':'Take our food to the stove.';items=[[ready?'Plate food':turn?(s.recipe===0?'Flip pancakes':'Turn pizza'):'Start cooking','work']];}
  else {$('banner').textContent=p.carry==='plate'?'Carry the plate to the serving table.':'Help your friend serve our meal.';items=[['Serve our food','work']];}
 }

 if(['basketball','softball'].includes(game))$('hint').textContent=`You are Player ${side+1}. Drag to move or aim. Turn your phone sideways for a bigger field.`;if(game==='hide')$('hint').textContent='Drag to walk. Hedges and barrels are solid. Hide near a marked spot.';if(game==='cook')$('hint').textContent='Drag to walk around the counters. Your chef carries what you pick up.';if(game==='swim')$('hint').textContent='Drag to swim. The diving board is at the near end of the pool.';if(game==='seesaw')$('hint').textContent='Tap Pump when your seat is low. Take turns pushing.';if(game==='fishing')$('hint').textContent='Drag left or right to choose a spot on the pier.';$('score').textContent=score;canvas.dataset.playerX=String(p.x);canvas.dataset.playerZ=String(p.z);buttons(items);
}
function release(){move={x:0,z:0};pointer=null;reeling=false;$('joystick').style.display='none';send({op:'input',...move});send({op:'reel',down:false});}
const canvas=$('game');canvas.onpointerdown=e=>{if(pointer!==null)return;e.preventDefault();pointer=e.pointerId;try{canvas.setPointerCapture(pointer);}catch{}const rect=$('arena').getBoundingClientRect();origin={x:e.clientX,y:e.clientY};$('joystick').style.cssText=`display:block;left:${e.clientX-rect.left}px;top:${e.clientY-rect.top}px`;$('joystick').firstElementChild.style.transform='translate(0,0)';};canvas.onpointermove=e=>{if(e.pointerId!==pointer)return;const dx=e.clientX-origin.x,dz=e.clientY-origin.y,n=Math.max(42,Math.hypot(dx,dz));move={x:dx/n,z:dz/n};$('joystick').firstElementChild.style.transform=`translate(${move.x*29}px,${move.z*29}px)`;};canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=release;
const held=new Set();function keyboard(){move={x:Number(held.has('arrowright')||held.has('d'))-Number(held.has('arrowleft')||held.has('a')),z:Number(held.has('arrowdown')||held.has('s'))-Number(held.has('arrowup')||held.has('w'))};}addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k)){e.preventDefault();held.add(k);keyboard();}});addEventListener('keyup',e=>{held.delete(e.key.toLowerCase());keyboard();});addEventListener('blur',()=>{held.clear();release();});document.addEventListener('visibilitychange',()=>{if(document.hidden){held.clear();release();}});
setInterval(()=>{if(document.hidden||!connected)return;send({op:'input',...move});if(reeling)send({op:'reel',down:true});},100);
try{if(game==='basketball'||document.createElement('canvas').getContext('webgl2'))scene=new ParkScene(canvas,game);else scene=new CanvasScene(canvas,game);new ResizeObserver(()=>scene.resize()).observe(canvas);if(embedded)parent.postMessage({channel:'jhw-playpark',type:'context',game},location.origin);else{$('loading').replaceChildren();const p=document.createElement('p');p.textContent='Play with your family from the town’s Play Together button, or try the controls here.';const a=document.createElement('a');a.href='index.html';a.textContent='Open our family world';const b=document.createElement('button');b.textContent='Try solo practice';b.onclick=()=>{local=new ParkSession();id='practice';receive(local.request({id,name:'Mommy',profile:'mommy'},{op:'join',game}));$('message').textContent=['hide','seesaw'].includes(game)?'Explore here. This game needs a second device in a family room to start.':'Solo practice. Join a family room to play together.';};const select=document.createElement('select');select.setAttribute('aria-label','Choose practice game');for(const [key,name]of Object.entries(GAMES)){const o=document.createElement('option');o.value=key;o.textContent=name;o.selected=key===game;select.append(o);}select.onchange=()=>{location.hash=select.value;location.reload();};$('loading').append(p,select,a,b);}}catch(e){$('loading').textContent='This game could not start. Try reopening it in Safari or Chrome. '+e.message;}
let soundOn=false,audioContext;const audioButton=document.createElement('button');audioButton.textContent='Sound off';audioButton.setAttribute('aria-label','Toggle game sound');audioButton.onclick=()=>{soundOn=!soundOn;audioButton.textContent=soundOn?'Sound on':'Sound off';if(soundOn){audioContext||=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}};document.querySelector('header').append(audioButton);
function playSound(name){if(!soundOn||!audioContext)return;const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.connect(gain);gain.connect(audioContext.destination);const t=audioContext.currentTime;oscillator.type=name==='swing'?'triangle':'sine';oscillator.frequency.setValueAtTime(name==='swing'?420:name==='under'?260:650,t);oscillator.frequency.exponentialRampToValueAtTime(name==='swing'?80:140,t+.18);gain.gain.setValueAtTime(.04,t);gain.gain.exponentialRampToValueAtTime(.001,t+.22);oscillator.start();oscillator.stop(t+.23);}
if(game==='softball'){const view=document.createElement('button');view.textContent='Field view';view.onclick=()=>{scene.wide=!scene.wide;if(scene.softball)scene.softball.view=scene.wide?'field':'auto';view.textContent=scene.wide?'Batting view':'Field view';};document.querySelector('header').append(view);}
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(local&&connected){local.tick(dt);receive(local.snapshot(id));}if(state&&scene){const elapsed=local?0:Math.min(.12,(now-receivedAt)/1000);const view={...state,time:state.time+elapsed,state:{...state.state,time:(state.state.time||0)+elapsed,swing:Math.max(0,(state.state.swing||0)-elapsed)},members:state.members.map(p=>{if(p.concealed||!Number.isFinite(p.x)){renderedPositions.delete(p.id);return p;}let r=renderedPositions.get(p.id);if(!r||Math.hypot(r.x-p.x,r.z-p.z)>4)r={x:p.x,z:p.z};const k=1-Math.exp(-dt*18);r.x+=(p.x-r.x)*k;r.z+=(p.z-r.z)*k;renderedPositions.set(p.id,r);return {...p,...r};})};scene.draw(view,id,dt);}requestAnimationFrame(frame);}requestAnimationFrame(frame);
