// Perspective Canvas fallback: same host simulation and inputs when WebGL is unavailable.
import {CHARACTER_ART,loadCharacter} from '../characters.mjs';
import {SPOTS,STATIONS,HEDGES,HIDE_BOUND} from './session.mjs?v=hide-2';
import {BASES,runnerPosition} from './vendor/softball.mjs';
export class CanvasScene {
 constructor(canvas,game){this.canvas=canvas;this.c=canvas.getContext('2d');this.game=game;this.art={};this.camera={x:0,z:0};for(const id of Object.keys(CHARACTER_ART))loadCharacter(id).then(im=>this.art[id]=im);this.resize();}
 resize(){const ratio=Math.min(devicePixelRatio||1,1.5);this.w=this.canvas.clientWidth;this.h=this.canvas.clientHeight;this.canvas.width=this.w*ratio;this.canvas.height=this.h*ratio;this.c.setTransform(ratio,0,0,ratio,0,0);}
 point(x,z,y=0){const depth=Math.max(5,26+(this.camera.z-z)),k=Math.min(this.w/(['hide','cook'].includes(this.game)?12:18),this.h/10)*26/depth;return {x:this.w/2+(x-this.camera.x)*k,y:this.h*.52+(z-this.camera.z)*k*.46-y*k,k};}
 poly(points,fill,stroke){const c=this.c;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke();}}
 ground(x,z,w,d,fill){this.poly([[x-w/2,z-d/2],[x+w/2,z-d/2],[x+w/2,z+d/2],[x-w/2,z+d/2]].map(([x,z])=>this.point(x,z)),fill);}
 box(x,z,w,d,h,fill,top='#ecd1a2',side='#b58e61'){const a=this.point(x-w/2,z-d/2,h),b=this.point(x+w/2,z-d/2,h),e=this.point(x+w/2,z+d/2,h),f=this.point(x-w/2,z+d/2,h);this.poly([f,e,this.point(x+w/2,z+d/2),this.point(x-w/2,z+d/2)],fill);this.poly([b,e,this.point(x+w/2,z+d/2),this.point(x+w/2,z-d/2)],side);this.poly([a,b,e,f],top);}
 ellipse(x,y,rx,ry,fill,stroke){const c=this.c;c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=2;c.stroke();}}
 line(a,b,color,width=2){const c=this.c;c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}
 text(t,p,size=12,color='#23483e',back=true){const c=this.c;c.font=`800 ${size}px system-ui`;c.textAlign='center';const w=c.measureText(t).width;if(back){c.fillStyle='#fff7e9ed';c.beginPath();c.roundRect(p.x-w/2-7,p.y-size-3,w+14,size+9,7);c.fill();}c.fillStyle=color;c.fillText(t,p.x,p.y);}
 ball(x,z,y,r,color){const p=this.point(x,z,y),c=this.c;const gradient=c.createRadialGradient(p.x-r*p.k*.3,p.y-r*p.k*.4,1,p.x,p.y,Math.max(2,r*p.k));gradient.addColorStop(0,'#fff8d4');gradient.addColorStop(.25,color);gradient.addColorStop(1,'#426b4d');this.ellipse(p.x,p.y,r*p.k,r*p.k,gradient);}
 tree(x,z){const p=this.point(x,z);this.line(p,this.point(x,z,3),'#94704d',p.k*.23);for(let i=0;i<4;i++)this.ball(x+Math.sin(i*3)*.7,z+Math.cos(i*3)*.3,2.7+i*.25,1,i%2?'#8db569':'#6a9f55');}
 avatar(p,index,s){if(p.concealed||p.inside!=null||!Number.isFinite(p.x))return;const showName=!(this.game==='hide'&&['hiding','seeking'].includes(s.state.phase));const c=this.c,art=CHARACTER_ART[p.profile],im=this.art[p.profile];let x=p.x,z=p.z,y=0;if(this.game==='seesaw'){x=index===0?-3.5:3.5;z=0;y=1.2+Math.sin(s.state.angle)*x;}if(this.game==='swim'){y=-.65;if(p.mode==='dive')y=.3+Math.sin((1.5-p.animation)/1.5*Math.PI)*2.6;}const pos=this.point(x,z,y),shadow=this.point(x,z);this.ellipse(shadow.x,shadow.y+2,.45*pos.k,.13*pos.k,'#234d3e33');if(art&&im){const h=art.height3D*pos.k*(p.stance==='crouch'?.58:1),heading=p.heading||0,f=Math.abs(heading)>Math.PI*.75?2:Math.abs(heading)<.75?0:heading>0?1:3;const frame=art.frames[f],w=h*frame[2]/frame[3],bob=p.moving?Math.abs(Math.sin(s.time*11))*pos.k*.06:0;c.globalAlpha=this.game==='swim'&&p.mode==='under'?.4:1;c.drawImage(im,...frame,pos.x-w/2,pos.y-h-bob,w,h);c.globalAlpha=1;if(showName)this.text(p.name,{x:pos.x,y:pos.y-h-7},11);if(this.game==='swim'&&p.mode==='under')for(let i=0;i<5;i++){const b=this.point(x+Math.sin(i+s.time)*.3,z,((s.time+i*.4)%1.6));this.ellipse(b.x,b.y,3,3,'#e5ffff66','#defbff');}}else if(showName)this.text(p.name,{x:pos.x,y:pos.y-15},12);}
 hideProp(s){const c=this.c,p=this.point(s.x,s.z);if(s.kind==='barrel'){const top=this.point(s.x,s.z,1.7);c.fillStyle='#b7844e';c.fillRect(top.x-.85*p.k,top.y,1.7*p.k,p.y-top.y);this.ellipse(p.x,p.y,.85*p.k,.3*p.k,'#9b6e40');for(let i=-2;i<=2;i++)this.line({x:top.x+i*p.k*.3,y:top.y},{x:p.x+i*p.k*.3,y:p.y},'#946c42',2);for(const h of [.25,1.3]){const b=this.point(s.x,s.z,h);this.ellipse(b.x,b.y,.87*p.k,.22*p.k,'#63736a');}this.ellipse(top.x,top.y,.88*p.k,.3*p.k,'#d5ae78','#795e42');this.ellipse(top.x,top.y,.65*p.k,.2*p.k,'#564532');}else if(s.kind==='bush'){for(let i=0;i<6;i++)this.ball(s.x+Math.sin(i*2)*.6,s.z+Math.cos(i*2)*.5,.65+i%2*.4,.75,i%2?'#83ad60':'#56934f');for(let i=0;i<6;i++){const b=this.point(s.x+Math.sin(i*2)*.8,s.z+Math.cos(i)*.5,1.1);this.ellipse(b.x,b.y,3,3,'#e8a7ae');}}else if(s.kind==='hay'){this.box(s.x,s.z,2.5,1.3,1.2,'#d5af54','#f4d783','#a5803b');this.box(s.x-.3,s.z-.2,1.6,1,2,'#dfb85f','#f9de8d','#b79047');}else{this.box(s.x,s.z,2.4,2,2,'#cc9b64','#e2ba82');const a=this.point(s.x-1.5,s.z+1,2),b=this.point(s.x+1.5,s.z+1,2),top=this.point(s.x,s.z+1,3.2);this.poly([a,b,top],'#649d8c','#477666');const door=this.point(s.x,s.z+1,1.5),bottom=this.point(s.x,s.z+1);c.fillStyle='#695544';c.fillRect(door.x-.4*p.k,door.y,.8*p.k,bottom.y-door.y);}if(Math.hypot(s.x-this.camera.x,s.z-this.camera.z)<8)this.text(s.name,this.point(s.x,s.z,3.5),10);}
 draw(s,id,dt){const c=this.c,w=this.w,h=this.h,me=s.members.find(p=>p.id===id)||s.members[0];this.camera.x=['hide','cook'].includes(this.game)?me.x:0;this.camera.z=['hide','cook'].includes(this.game)?me.z:0;c.clearRect(0,0,w,h);const sky=c.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#b7e3ec');sky.addColorStop(.35,'#e6f0d4');sky.addColorStop(.36,'#a3c37a');sky.addColorStop(1,'#6b9d5b');c.fillStyle=sky;c.fillRect(0,0,w,h);this.ellipse(w*.83,h*.15,28,28,'#fff1b5');for(let i=0;i<9;i++)this.tree(i*5-20,-15-(i%3)*2);this.ground(0,0,this.game==='hide'?70:23,this.game==='hide'?70:20,'#8cb267');if(this.game==='hide'){for(let i=0;i<14;i++)this.ground(-.4,i*1.25-9,1.2,.8,'#d3c38e');}for(let i=0;i<80;i++){const p=this.point(Math.sin(i*3.1)*11,Math.cos(i*1.7)*10);this.line(p,{x:p.x+2,y:p.y-4},'#689959',1);}
 if(this.game==='hide'){for(const side of [-1,1])for(const y of [.4,1]){this.line(this.point(-29,side*29,y),this.point(29,side*29,y),'#d7bc87',3);this.line(this.point(side*29,-29,y),this.point(side*29,29,y),'#d7bc87',3);}const objects=[...HEDGES.map(o=>({z:o.z,draw:()=>{this.box(o.x,o.z,o.w,o.d,1.15,'#477b45','#79a458','#3e6e40');for(let z=-o.d/2;z<o.d/2;z+=.55)this.ball(o.x,o.z+z,1.1,.45,'#6d9952');}})),...SPOTS.map(spot=>({z:spot.z,draw:()=>this.hideProp(spot)})),...s.members.map((p,i)=>({z:p.z??-100,draw:()=>this.avatar(p,i,s)}))];objects.filter(o=>o.z-this.camera.z<12).sort((a,b)=>a.z-b.z).forEach(o=>o.draw());return;}
 if(this.game==='fishing'){this.camera.z=-2;this.ground(0,-13,42,31,'#60b4c7');for(let i=0;i<32;i++){const p=this.point(Math.sin(i*2)*18,-3-i%20);this.ellipse(p.x,p.y,(.3+Math.sin(s.time+i)*.08)*p.k,.055*p.k,'#9cd9dc');}for(let i=0;i<13;i++)this.box(0,1+i*.45,20,.4,.18,'#b68d58',i%2?'#d8b37e':'#cfaa71');s.members.forEach((p,i)=>{this.avatar(p,i,s);const f=p.fish;const tip=this.point(p.x+.4,2,2.2);this.line(this.point(p.x+.4,5,1.1),tip,'#735139',4);if(['cast','waiting','bite','fight'].includes(f.phase)){const t=f.phase==='cast'?Math.min(1,f.t/.8):1,at=this.point(p.x+(f.x-p.x)*t,5+(f.z-5)*t,f.phase==='cast'?Math.sin(t*Math.PI)*3:.15+Math.sin(s.time*8)*.07);this.line(tip,at,'#fff5ce',1);this.ellipse(at.x,at.y,5,7,i?'#ffe197':'#eb887c');if(f.phase==='fight'){const fp=this.point(f.x+Math.sin(s.time*4)*.3,f.z,.12);this.ellipse(fp.x,fp.y,14,5,'#87be86','#d7ebae');this.poly([{x:fp.x-12,y:fp.y},{x:fp.x-21,y:fp.y-6},{x:fp.x-21,y:fp.y+6}],'#689e6c');}}});return;}
 if(this.game==='swim'){this.ground(0,0,18,15,'#f0dfb9');this.ground(0,0,15,11,'#60c7dd');for(let i=-6;i<=6;i+=2)this.line(this.point(i,-5),this.point(i,5),'#a0e4ec',2);for(let i=0;i<12;i++){const p=this.point(Math.sin(i*8)*6,Math.cos(i*9)*4);this.ellipse(p.x,p.y,9+Math.sin(s.time+i)*3,2,'#b2e9ed');}for(const r of s.state.rings){const p=this.point(r.x,r.z,.2);this.ellipse(p.x,p.y,.43*p.k,.19*p.k,'#ffdf76','#b99845');this.ellipse(p.x,p.y,.27*p.k,.10*p.k,'#62c6d8');}this.box(0,6,1,3,1.1,'#8fae9e','#fff0b1');}
 if(this.game==='seesaw'){this.ground(0,0,13,7,'#d6ce91');this.box(0,0,.7,.8,1.1,'#769b94','#9fbbb2');const left=this.point(-4,0,1.2-Math.sin(s.state.angle)*4),right=this.point(4,0,1.2+Math.sin(s.state.angle)*4);this.line(left,right,'#d39e55',14);for(let i=0;i<5;i++){const p=this.point(i*1.2-2.4,-5,2);this.ellipse(p.x,p.y,9,9,i<s.state.stars?'#ffdf6d':'#bfc5a2','#fff3c2');}}
 if(this.game==='cook'){this.ground(0,0,22,18,'#ead9b7');this.box(0,-6,20,.2,4,'#f9e6c5','#fff0d6');for(let i=-8;i<=8;i+=4){const a=this.point(i-1,-5.8,3.4),b=this.point(i+1,-5.8,1.7);c.fillStyle='#97cbd0';c.fillRect(a.x,a.y,b.x-a.x,b.y-a.y);this.line({x:(a.x+b.x)/2,y:a.y},{x:(a.x+b.x)/2,y:b.y},'#fff9e5',3);}for(const [i,t]of STATIONS.entries()){this.box(t.x,t.z,3,1.5,1.3,i===2?'#5b7476':'#80aa99','#fff1d9');this.text(t.name,this.point(t.x,t.z,2.5),11);}for(let i=0;i<3;i++)this.ball(-6.8+i*.8,-4,1.55,.24,['#e9c46f','#ecaa75','#db8a7e'][i]);const bowl=this.point(0,-4,1.5);this.ellipse(bowl.x,bowl.y,.5*bowl.k,.2*bowl.k,'#c6947f');if(s.state.step>=4){const pan=this.point(6,-4,1.45);this.ellipse(pan.x,pan.y,.5*pan.k,.22*pan.k,'#f1ce77','#59706a');}if(s.state.heat>0&&s.state.step===4)for(let i=0;i<5;i++){const p=this.point(6+Math.sin(i+s.time)*.15,-4,1.7+(s.time*.5+i*.3)%1.5);this.ellipse(p.x,p.y,4,7,'#fff9e6aa');}}
 if(this.game==='softball'){this.camera={x:0,z:0};const map=(x,z,y=0)=>this.point(-x*.18,5-z*.18,y*.18);this.ground(0,-2,22,19,'#71a95b');const base=BASES.slice(0,4).map(p=>map(p.x,p.z));this.poly(base,'#d7b788');for(let i=0;i<4;i++){this.line(base[i],base[(i+1)%4],'#fff3d5',2);c.fillStyle='#fff8e2';c.fillRect(base[i].x-4,base[i].y-3,8,5);}const g=s.state;for(const [i,f]of g.fielders.entries()){const p=map(f.x,f.z);this.ellipse(p.x,p.y,7,7,i===g.selected?'#ffdb7c':'#6c77b1','#ffefd3');this.text(String(i+1),{x:p.x,y:p.y+3},8,'#fff',false);}s.members.forEach((p,i)=>{const batting=i===g.batting,f=g.fielders[g.selected];this.avatar({...p,x:batting?.15:-f.x*.18,z:batting?5:5-f.z*.18},i,s);});for(const r of g.runners){if(r.out||r.scored)continue;const p=runnerPosition(r),b=map(p.x,p.z);this.ellipse(b.x,b.y,5,5,'#f0b274');}const ball=map(g.ball.x,g.ball.z,g.ball.y);this.ellipse(ball.x,ball.y,5,5,'#ffef60','#cbbb36');if(g.phase==='pitch'){const plate=map(0,0),travel=g.pitch.t/(g.pitch.windup+g.pitch.duration);this.text(travel>.8?'SWING!':'Watch the pitch…',{x:w/2,y:h-25},16);}return;}
 s.members.slice().sort((a,b)=>a.z-b.z).forEach(p=>this.avatar(p,s.members.indexOf(p),s));
 }
}
