import * as T from './vendor/three.mjs';
import {SoftballScene} from './vendor/softball-scene.mjs';
import {drawBasketball} from './vendor/basketball.mjs';
import {CHARACTER_ART,loadCharacter} from '../characters.mjs';
import {SPOTS,STATIONS} from './session.mjs';
const palette=['#74d4ea','#ffba70','#e3a9ed','#ffe98d'];
export class ParkScene {
 constructor(canvas,game){this.canvas=canvas;this.game=game;this.art={};this.avatars=new Map();this.textures={};this.dynamic=[];this.mats=new Map();for(const id of Object.keys(CHARACTER_ART))loadCharacter(id).then(im=>{if(!im)return;this.art[id]=im;this.textures[id]=CHARACTER_ART[id].frames.map(([x,y,w,h])=>{const c=document.createElement('canvas');c.width=256;c.height=512;const ctx=c.getContext('2d');ctx.drawImage(im,x,y,w,h,128-256*w/h,0,512*w/h,512);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return tex;});});
  if(game==='basketball'){this.ctx=canvas.getContext('2d');this.resize();return;}
  if(game==='softball'){this.softball=new SoftballScene(canvas);this.scene=this.softball.scene;this.camera=this.softball.camera;this.renderer=this.softball.renderer;this.resize();return;}
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;
  this.scene=new T.Scene();this.scene.background=new T.Color(0xb6e3ed);this.scene.fog=new T.Fog(0xb6e3ed,42,105);this.camera=new T.PerspectiveCamera(46,1,.1,150);this.scene.add(new T.HemisphereLight(0xeafcff,0x7e914f,2));const sun=new T.DirectionalLight(0xffe4b8,2.6);sun.position.set(-12,24,14);this.scene.add(sun);
  this.box(0,-.3,0,65,.5,65,0x84b460);for(let i=0;i<32;i++){const a=i/32*Math.PI*2,r=22+(i%3)*3;this.tree(Math.cos(a)*r,Math.sin(a)*r,2.4+i%4*.5);}
  for(let i=0;i<7;i++){const cloud=new T.Group();for(let j=0;j<3;j++)this.sphere(j*1.2,0,0,1.3,0xfffbed,cloud).scale.set(1.5,.65,1);cloud.position.set(i*10-30,16+(i%2)*3,-28);this.scene.add(cloud);}
  if(game==='hide')this.hide();if(game==='fishing')this.fishing();if(game==='seesaw')this.seesaw();if(game==='swim')this.pool();if(game==='cook')this.kitchen();this.resize();
 }
 mat(color){if(!this.mats.has(color))this.mats.set(color,new T.MeshStandardMaterial({color,roughness:.8}));return this.mats.get(color);}
 mesh(geometry,color,x,y,z,parent=this.scene){const m=new T.Mesh(geometry,this.mat(color));m.position.set(x,y,z);parent.add(m);return m;}
 box(x,y,z,w,h,d,c,parent){return this.mesh(new T.BoxGeometry(w,h,d),c,x,y,z,parent);}
 sphere(x,y,z,r,c,parent){return this.mesh(new T.SphereGeometry(r,20,12),c,x,y,z,parent);}
 cylinder(x,y,z,r,h,c,parent){return this.mesh(new T.CylinderGeometry(r,r,h,24),c,x,y,z,parent);}
 ring(x,y,z,r,c,parent){const m=this.mesh(new T.TorusGeometry(r,.065,8,40),c,x,y,z,parent);m.rotation.x=Math.PI/2;return m;}
 label(text,x,y,z,width=3,parent=this.scene){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#fff7df';ctx.beginPath();ctx.roundRect(2,2,508,92,24);ctx.fill();ctx.fillStyle='#234a40';ctx.font='bold 35px system-ui';ctx.textAlign='center';ctx.fillText(text,256,61,475);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(width,width*96/512),new T.MeshBasicMaterial({map:tex,transparent:true,side:T.DoubleSide}));m.position.set(x,y,z);parent.add(m);return m;}
 tree(x,z,h){this.cylinder(x,h*.4,z,.2,h*.8,0x9b7150);this.sphere(x,h,z,h*.55,0x568e51);this.sphere(x-.6,h*.85,z+.3,h*.4,0x70a952);}
 fence(){for(let x=-11;x<=11;x+=1){this.box(x,.7,-11,.15,1.4,.15,0xe7d4a0);this.box(x,.7,9,.15,1.4,.15,0xe7d4a0);}for(const z of [-11,9])for(const y of [.45,1])this.box(0,y,z,23,.12,.12,0xcfac78);}
 hide(){this.fence();this.label('HIDE & SEEK MEADOW',0,4,-11,7);for(const s of SPOTS){if(s.kind==='barrel'){this.cylinder(s.x,.85,s.z,.9,1.7,0xa87945);for(const y of [.2,1.4])this.cylinder(s.x,y,s.z,.94,.13,0x576d65);this.cylinder(s.x,1.71,s.z,.74,.025,0x4f3c30);}if(s.kind==='bush'){for(let i=0;i<5;i++)this.sphere(s.x+Math.cos(i*2)*.65,.85+(i%2)*.3,s.z+Math.sin(i*2)*.5,.85,i%2?0x417f4c:0x65a454);for(let i=0;i<8;i++)this.sphere(s.x+Math.cos(i)*.9,1.3,s.z+Math.sin(i)*.8,.1,0xdd84a2);}if(s.kind==='hay'){this.box(s.x,.6,s.z,2.4,1.2,1.4,0xe8c369);this.box(s.x-.4,1.65,s.z,1.6,.9,1.2,0xf3d681);for(const x of [-.65,.6])this.box(s.x+x,.62,s.z+.72,.09,1.15,.03,0xa8863f);}if(s.kind==='hut'){this.box(s.x-1,1.1,s.z,.18,2.2,2,0xcda977);this.box(s.x+1,1.1,s.z,.18,2.2,2,0xcda977);this.box(s.x,1.1,s.z-1,2,2.2,.15,0xd9b687);const roof=this.mesh(new T.ConeGeometry(1.8,1,4),0x4c9386,s.x,2.7,s.z);roof.rotation.y=Math.PI/4;}this.label(s.name,s.x,3.2,s.z,2.5);}for(let i=0;i<30;i++){const x=Math.sin(i*12)*10,z=Math.cos(i*8)*8;this.cylinder(x,.16,z,.03,.3,0x38774c);this.sphere(x,.35,z,.11,i%2?0xf6e89b:0xf6a5ab);}}
 fishing(){this.water=this.box(0,-.04,-15,45,.12,32,0x59b9cc);this.water.material=new T.MeshPhongMaterial({color:0x43abc0,shininess:85,specular:0xc2f6ef});for(let i=0;i<15;i++)this.box(0,.1,7-i*.48,20,.18,.42,i%2?0xc59a61:0xd3ac75);for(const x of [-9,9])for(const z of [1,7])this.cylinder(x,-.1,z,.18,1.6,0x87684c);this.label('FAMILY FISHING PIER',0,3.8,8,6);this.ripples=[];for(let i=0;i<20;i++)this.ripples.push(this.ring(Math.sin(i*3)*19,.045,-3-(i*1.37)%24,.6+i%3*.3,0x88d6dd));for(let i=0;i<24;i++){const x=i%2?-12:12,z=-2-i*.7;this.cylinder(x,.45,z,.035,1.1,0x6c974f);this.cylinder(x,.98,z,.07,.3,0x957955);}this.bobbers=new Map();}
 seesaw(){this.fence();this.cylinder(0,.55,0,.45,1.1,0x687fa0);this.mesh(new T.ConeGeometry(1,.9,3),0xefb85c,0,.9,0).rotation.z=Math.PI;this.plank=new T.Group();this.plank.position.y=1.2;this.scene.add(this.plank);this.box(0,0,0,8,.22,.8,0xe9b76b,this.plank);for(const x of [-3.5,3.5]){this.box(x,.17,0,1.1,.12,1.1,x<0?0x75bfcb:0xe995a4,this.plank);this.cylinder(x,.65,.35,.06,.9,0xf5e9c3,this.plank);}this.label('SEESAW STARS',0,4,-5,6);this.starOrbs=[];for(let i=0;i<5;i++)this.starOrbs.push(this.sphere(i*1.1-2.2,3.1,-5,.25,0xb6b2a1));}
 pool(){this.box(0,-.05,0,18,.3,15,0xf3dfb5);this.box(0,.02,0,15,.1,11,0x51c5dd);for(const x of [-7.8,7.8])this.box(x,.15,0,.4,.25,12,0xfaf1d9);for(const z of [-5.8,5.8])this.box(0,.15,z,16,.25,.4,0xfaf1d9);for(let i=-6;i<=6;i+=2)this.box(i,.078,0,.04,.01,10,0x8fe1e9);this.box(0,1.1,6,1, .14,3.5,0xf6e6a6);for(const x of [-.42,.42]){this.cylinder(x,.5,7,.045,1,0xa6b8b6);for(let y=.2;y<1;y+=.25)this.box(0,y,7,.8,.06,.1,0xa6b8b6);}for(const x of [-10,10]){this.box(x,.6,-2,1.5,.2,3,0xf3ae9e);this.mesh(new T.ConeGeometry(2.3,.7,16),0xebbf6d,x,3,-2);this.cylinder(x,1.3,-2,.05,2.6,0xbda989);}this.label('POOL PARTY',0,3,-7,5);this.collectibles=[];for(let i=0;i<8;i++)this.collectibles.push(this.ring(0,.28,0,.45,0xffdf65));}
 kitchen(){this.box(0,-.02,0,22,.15,19,0xe9d8b5);this.box(0,2.1,-6,20,4.2,.2,0xffe7c3);for(let i=-8;i<=8;i+=4){this.box(i,2.7,-5.86,2.5,1.7,.1,0x87cad1);this.box(i,2.7,-5.75,.09,1.7,.1,0xfff8df);}for(const [i,s]of STATIONS.entries()){this.box(s.x,.6,s.z,3,1.2,1.5,i===2?0x536d70:0x74a598);this.box(s.x,1.25,s.z,3.2,.15,1.7,0xfff5de);this.label(s.name,s.x,2.6,s.z,3);}
  for(let i=0;i<3;i++){this.sphere(-6.8+i*.8,1.55,-4,.26,[0xf4d580,0xe49e69,0xec9f92][i]);this.cylinder(5.4+i*.55,1.36,-4,.22,.045,0x233f44);}this.bowl=this.sphere(0,1.4,-4,.5,0xd39e83);this.bowl.scale.y=.55;this.food=this.cylinder(6,1.45,-4,.55,.13,0xf2cb6b);this.steam=[];for(let i=0;i<5;i++)this.steam.push(this.sphere(6,2+i*.2,-4,.10,0xfff8e7));this.label('COOK SOMETHING TOGETHER',0,4.8,-6,8);}
 avatar(p,index){let a=this.avatars.get(p.id);if(!a){const mesh=new T.Mesh(new T.PlaneGeometry(1,1),new T.MeshBasicMaterial({transparent:true,alphaTest:.08,side:T.DoubleSide}));this.scene.add(mesh);const label=this.label(p.name,0,0,0,2);a={mesh,label};this.avatars.set(p.id,a);}const id=CHARACTER_ART[p.profile]?p.profile:null;a.mesh.visible=Boolean(id&&this.textures[id]&&!p.concealed&&Number.isFinite(p.x));a.label.visible=!p.concealed&&Number.isFinite(p.x);if(!a.mesh.visible&&!a.label.visible)return a;const height=id?CHARACTER_ART[id].height3D:1.8;let y=0,x=p.x,z=p.z;if(this.game==='seesaw'){x=index===0?-3.5:3.5;y=1.25+Math.sin(this.current.state.angle)*x;z=0;}if(this.game==='swim'){y=p.mode==='under'?-.65:-.6;if(p.mode==='dive'){const t=1.5-p.animation;y=.3+Math.sin(t/1.5*Math.PI)*2.6;}a.mesh.material.opacity=p.mode==='under'?.45:1;}
  const bob=p.moving?Math.abs(Math.sin(this.current.time*11))*.075:0;a.mesh.position.set(x,y+height/2+bob,z);a.mesh.scale.set(height*.5,height,1);a.mesh.quaternion.copy(this.camera.quaternion);if(id&&this.textures[id]){const heading=p.heading||0,frame=Math.abs(heading)>Math.PI*.75?2:Math.abs(heading)<.75?0:heading>0?1:3;a.mesh.material.map=this.textures[id][frame];a.mesh.material.needsUpdate=true;}a.label.position.set(x,y+height+.35,z);a.label.quaternion.copy(this.camera.quaternion);if(!id){a.label.position.y=y+1;}// Guests retain their name until approved character art is available.
  return a;}
 resize(){if(this.game==='basketball'){this.canvas.width=960;this.canvas.height=540;return;}if(this.softball){this.softball.resize();return;}const w=this.canvas.clientWidth,h=this.canvas.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 draw(s,id,dt){this.current=s;if(this.ctx){const c=this.ctx,g=s.state;drawBasketball(c,g,s.side,(c,p,i,g,selected)=>{const m=s.members[i],im=m&&this.art[m.profile];if(!im)return false;const art=CHARACTER_ART[m.profile],frame=art.frames[0],scale=.74+(p.y-90)/1500,x=480+(p.x-480)*scale,y=172+(p.y-90)*.68,h=art.height3D*42;const jump=g.basket.jumps[i]>0?Math.sin(g.basket.jumps[i]/.65*Math.PI)*16:0;c.fillStyle=selected?'#fff19aaa':'#183e3a44';c.beginPath();c.ellipse(x,y+1,20,6,0,0,Math.PI*2);c.fill();c.drawImage(im,...frame,x-h*frame[2]/frame[3]/2,y-h-jump,h*frame[2]/frame[3],h);c.font='bold 14px system-ui';c.textAlign='center';c.fillStyle='#fff';c.fillText(m.name,x,y-h-8-jump);return true;});return;}
  if(this.softball){for(const actor of [...this.softball.defenders,this.softball.batter])actor.body.visible=true;this.softball.draw(s.state,s.side,dt);const g=s.state;this.avatars.forEach(a=>{a.mesh.visible=false;a.label.visible=false;});for(let side=0;side<s.members.length;side++){const p=s.members[side],f=g.fielders[g.selected],bat=side===g.batting,actor=bat?this.softball.batter:this.softball.defenders[g.selected];const active=bat?!['live','throw','homer','foul'].includes(g.phase):true;actor.body.visible=false;if(active)this.avatar({...p,x:bat?.8:-f.x,z:bat?0:f.z,heading:0},side);}this.renderer.render(this.scene,this.camera);return;}
  const me=s.members.find(p=>p.id===id)||s.members[0],portrait=this.camera.aspect<1;let cx=0,cz=1,cy=15,back=19;if(this.game==='hide'||this.game==='cook'){cx=me?.x||0;cz=me?.z||0;cy=portrait?13:12;back=portrait?17:15;}if(this.game==='fishing'){cy=portrait?17:13;back=portrait?23:19;cz=-4;}if(this.game==='swim'){cy=portrait?21:17;back=portrait?23:19;}if(this.game==='seesaw'){cy=portrait?13:9;back=portrait?19:16;}this.camera.position.lerp(new T.Vector3(cx,cy,cz+back),1-Math.exp(-dt*5));this.camera.lookAt(cx,0,cz);
  const present=new Set(s.members.map(p=>p.id));for(const [key,a]of this.avatars)if(!present.has(key)){a.mesh.visible=false;a.label.visible=false;}s.members.forEach((p,i)=>this.avatar(p,i));
  if(this.game==='seesaw'){this.plank.rotation.z=s.state.angle;this.starOrbs.forEach((o,i)=>o.material=this.mat(i<s.state.stars?0xffd960:0xb6b2a1));}
  if(this.game==='swim'){this.collectibles.forEach((o,i)=>{const r=s.state.rings[i];o.visible=Boolean(r);if(r){o.position.set(r.x,.22+Math.sin(s.time*2+i)*.07,r.z);o.rotation.z=Math.sin(s.time+i)*.15;}});}
  if(this.game==='cook'){this.bowl.scale.y=.55+Math.sin(s.state.work)*.03;this.food.visible=s.state.step>=4;this.steam.forEach((o,i)=>{o.visible=s.state.heat>0&&s.state.step===4;o.position.y=1.8+(s.time*.6+i*.2)%1.2;});}
  if(this.game==='fishing'){for(const [key,b]of this.bobbers)if(!present.has(key))b.root.visible=false;s.members.forEach((p,i)=>{let b=this.bobbers.get(p.id);if(!b){const root=new T.Group();this.scene.add(root);const float=this.sphere(0,0,0,.17,i===0?0xee786e:0xf3cc65,root);const line=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xfff3d2}));this.scene.add(line);const rod=this.cylinder(0,0,0,.04,3,0x85593e);b={root,float,line,rod};this.bobbers.set(p.id,b);}const f=p.fish,active=['cast','waiting','bite','fight'].includes(f.phase);b.root.visible=active;b.line.visible=active;b.rod.position.set(p.x+.45,1.5,p.z-1);b.rod.rotation.x=-.7;const t=f.phase==='cast'?Math.min(1,f.t/.8):1,x=p.x+(f.x-p.x)*t,z=p.z+(f.z-p.z)*t,y=f.phase==='cast'?Math.sin(t*Math.PI)*3:.1+Math.sin(s.time*(f.phase==='bite'?18:3))*.07;b.root.position.set(x,y,z);if(active){b.line.geometry.dispose();b.line.geometry=new T.BufferGeometry().setFromPoints([new T.Vector3(p.x+.45,2.65,p.z-2),new T.Vector3(x,y,z)]);}});this.ripples.forEach((r,i)=>r.scale.setScalar(1+Math.sin(s.time+i)*.15));}
  this.renderer.render(this.scene,this.camera);
 }
}
